### ISSUE TITLE
fcitx切换模式导致firefox的菜单无法弹出

### ISSUE THREAD

**Issue by ditsing** [fcitx/fcitx#1]
fcitx有个功能：输入法切换到不激活状态时直接将raw string上屏。很喜欢这个功能，但是发现fcitx 4.2.4如果在firefox的地址栏或者搜索栏里使用这个功能，就会导致之后的firefox菜单（右键菜单、智能地址栏以及左上角菜单）弹出之后瞬间消失。

具体过程：
1、在搜索栏里输入中文
2、输入过程中切换输入法到英文
3、fcitx将未输入完成的拼音显示在搜索栏里
4、firefox菜单失效

fcitx 4.2.4-1，firefox 13.0.2，KDE 4.8.4, Archlinux

**Comment by 3togo** [comment]
fcitx works perfectly with gnome terminal , wps, chrome browser and etc in my installed Ubuntu. Only firefox could not work with fcitx.  I wonder whether it is a common problem.
