### ISSUE TITLE
Remapping capslock from .Xmodmap does not work as intended

### ISSUE THREAD

**Issue by jaseg** [fcitx/fcitx#148]
Hi,
I'm using a slightly customized variant of the US-international keyboard layout where I remapped the capslock key to act as a second escape key. Before using fcitx, I did this with the following shell script calling xkbcomp and xmodmap:

```
#!/bin/bash
# Remaps [TAB] to mean [ESCAPE] (nice for vim) and properly assigns the "Windows
# key" to MOD4 (nice for the awesome window manager)
# Also, sprinkles some unicode over unused or poorly used keys.
# <LGST> is that key next to left shift that is not found on US keyboards
xkbcomp - $DISPLAY<<EOF
xkb_keymap {
xkb_keycodes  { include "evdev+aliases(qwertz)"};
xkb_types     { include "complete"};
xkb_compat    { include "complete"};
xkb_symbols   {
    include "pc+us(altgr-intl)+inet(evdev)+group(alt_shift_toggle)+level3(ralt_switch)+capslock(escape)"
    key <LSGT> { [ doublelowquotemark, leftdoublequotemark, U2665, U2606 ] };
    key <AB01> { [ z, Z, U2190, U21E6 ] };
    key <AB02> { [ x, X, U2192, U21E8 ] };
    key <AB05> { [ b, B, U2714, U2718 ] };
    key <AB07> { [ m, M, mu,    U26A1 ] };
    key <AE01> { [ 1, exclam, U2610, exclamdown ] };
    key <AE02> { [ 2, at, U2611, dead_doubleacute ] };
    key <AE03> { [ 3, numbersign, U2612, dead_macron ] };
};
xkb_geometry  { include "pc(pc104)"};
};
EOF
xmodmap -e "add mod4 = Multi_key"
```

Now, for fcitx I generated a `.Xmodmap` using `xmodmap -pke`. In the xmodmap, the entries for the escape and capslock keys both correctly only contain escape, not capslock mappings. After starting fcitx, however, the capslock key will _both_ emit an escape keycode _and_ capslock the keyboard (which is extremely annoying). I have tracked this down to the fact that just xkbcomp is not enough to remap the caplock key, the xkbcomp script above is needed for that. Executing the script above solves the problem until a new keyboard is added to the system, fcitx is restarted or the fcitx input method is changed.

How am I supposed to do this remapping properly? As far as I can tell, the `.Xmodmap` file is a poor hack and a proper solution would require a custom xkb script to be loaded, though I do not know how to do that with fcitx. Any comments are appreciated.

**Comment by godhelpjun** [comment]
On my ubuntu 16.04,gnome desktop ,I use setxkbmap -o 'caps:swapescape'  to swap escape key with caps key.
every time I switch to fcitx,the swap effect disappears . 
I tried the following,none of those woks for me:
1.fcitx --disable fcitx-xkb
then it says:
(WARN-4779 /build/fcitx-PSoVA1/fcitx-4.2.9.1/src/module/dbus/dbusstuff.c:246) DBus Service Already Exists
(ERROR-4779 /build/fcitx-PSoVA1/fcitx-4.2.9.1/src/lib/fcitx/instance.c:440) Exiting.

2..use the config panel to disable(unchecked) the x keyboard integration addon

3.configure x keyboard integration addon ,add the file full file path to the 'apply this custom xmodmap script after layout changes',which file contains expression something like this: 'keycode 66 = ESCAPE',which works fine for xmodmap.

4.unchecked the option 'allow to override the system x keyboard setting'

it is really a pain when I using vim.
what I did wrong?
please help.thanks.

-

**Comment by Ipphig** [comment]
On your ~/.xinitrc, the first let fcitx run, the after let xmodmap read ~/.Xmodmap.

Something like this,
fcitx -dr &
sleep 2
xmodmap ~/.Xmodmap &

Adjust sleep 2 seconds with your need.  In my case 2 does the job.
