### ISSUE TITLE
ubuntu系统下chrome输入有漏字母现象

### ISSUE THREAD

**Issue by xuchen** [fcitx/fcitx#159]
fcitx版本为4.2.8.3-3~precise1，Ubuntu版本为12.04，chrome版本为最新32bit deb Version 35.0.1916.153.

输入时有些字母会漏出输入框直接打到屏幕上。比如说我打了这一段:

"直接打到屏幕上。比如说我打了这一段，原本的句子是"

原本的句子是：

"直接打到g品目 _[pingmu -> g没有进入输入框-> g品目，所以打出了"pinmu品目"]_ 上。比如说我打了这一段，b袁恩 _[yuanben-> b没有进入输入框-> b袁恩，所以打出了"yuanen袁恩"]_ 的句子是"

**Comment by laurence6** [comment]
我在 chrome://flags 里把 Experimental text input focus manager 关闭，问题就解决了

**Comment by pangyupo** [comment]
@laurence6 的确如此，多谢！

**Comment by chenzhiwei** [comment]
遇到同样的问题了，我的 `.xprofile` 文件内容如下，主要是用来让 Java 程序（eclipse）可以输入中文的。

```
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=xim
export GTK_IM_MODULE=xim
```

后来发现设置`*_IM_MODULE=xim`会导致在 Chromium Browser里输入中文出问题。

另外，多谢@laurence6 的解决方法。

**Comment by jobinson99** [comment]
github-atom 也有这问题，另外， Experimental text input focus manager 在chrome51找不到这个设置。

**Comment by einson136** [comment]
能跟作为一个小白的我说一下是如何操作的吗？
