### ISSUE TITLE
英文输入时出现下拉菜单和候选词，想知道如何关闭这个功能

### ISSUE THREAD

**Issue by xing-zhi** [fcitx/fcitx#161]
好像是更新系统后，fcitx在输入英文时出现了下拉菜单和候选词。开始还很觉得这个功能比较新奇，但是在使用过程中发现几个问题：1、在混合输入英文和数字时，需要先按[enter]键再输入数字；2、在输入密码时，身边的任何人都可以看到；3、在确认输入时，需要按[enter]键或者[space]键，这是不方便的。
不知道这是新功能还是不经意开启了这个功能，想知道如何关闭这个功能。

**Comment by wengxt** [comment]
This is a bug that only happens when there's no existing configuration, already fixed.
https://github.com/fcitx/fcitx/commit/bf10b85cc475ccfcf5a4135b21da830a4ddc78e8
