### ISSUE TITLE
ubuntu下 fcitx进程100%cpu问题

### ISSUE THREAD

**Issue by tacy** [fcitx/fcitx#183]
12472 18:50:04.518760563 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12474 18:50:04.518761555 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12475 18:50:04.518761854 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12481 18:50:04.518766672 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12482 18:50:04.518766961 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12484 18:50:04.518767919 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12485 18:50:04.518768209 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12494 18:50:04.518773065 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12496 18:50:04.518773323 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12497 18:50:04.518774307 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12498 18:50:04.518774604 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12505 18:50:04.518779420 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12506 18:50:04.518779711 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12507 18:50:04.518780668 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12508 18:50:04.518780961 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12517 18:50:04.518785792 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12518 18:50:04.518786085 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12520 18:50:04.518787042 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12522 18:50:04.518787319 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12529 18:50:04.518792054 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12530 18:50:04.518792350 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12531 18:50:04.518793296 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12532 18:50:04.518793577 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12540 18:50:04.518798409 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12541 18:50:04.518798712 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12543 18:50:04.518799661 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12544 18:50:04.518799957 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12553 18:50:04.518804769 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12554 18:50:04.518805034 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12555 18:50:04.518805979 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 
12556 18:50:04.518806261 2 fcitx (2445) < recvfrom res=-11(EAGAIN) data= tuple=NULL 
12562 18:50:04.518811045 2 fcitx (2445) > read fd=3(<p>pipe:[16006]) size=1 
12564 18:50:04.518811336 2 fcitx (2445) < read res=-11(EAGAIN) data= 
12566 18:50:04.518812297 2 fcitx (2445) > recvfrom fd=7(<u>) size=4096 

用sysdig看了一下,应该是fcitx进入了死循环了

tacy@tacy:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
tacy@tacy:~$ apt-cache policy fcitx
fcitx:
  已安装：  1:4.2.8.4-3~precise1
  候选软件包：1:4.2.8.4-3~precise1
  版本列表：
 *** 1:4.2.8.4-3~precise1 0
        500 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
     1:4.2.2-1~precise 0
        500 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu/ precise/main amd64 Packages
     1:4.2.0-1 0
        500 http://mirrors.ustc.edu.cn/ubuntu/ precise/universe amd64 Packages
tacy@tacy:~$ uname -a
Linux tacy 3.13.0-30-generic #55~precise1-Ubuntu SMP Fri Jul 4 21:52:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
tacy@tacy:~$ 

tacy@tacy:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:zh_CN:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

**Comment by seenxu** [comment]
archlinux下，fcitx+sogou同样的问题，时不时的cpu load 100%

**Comment by tacy** [comment]
简单办法就是不用sogou

**Comment by seenxu** [comment]
已经把sogou删除了，换回最原始的libpinyin。

sogou不仅仅会造成cpu load 100%，换回libpinyin我才发现，sogou还会造成大量的内存使用，没有sogou内存占用在40MB左右，用了sogou竟然会达到200MB。

**Comment by happyaron** [comment]
内存占用是正常的，搜狗在Windows和Mac上也需要同样多的内存。CPU 100%目前能定位是dbus调用的问题。

**Comment by Findxiaoxun** [comment]
同样出现了这个问题，而且偶尔很频繁。开机会出现dbus服务初始化失败。

**Comment by zhao-han** [comment]
同样问题 Ubuntu14.04
去掉搜狗 用回sunpinyin 问题解决 
具体拼音输入法选择可以参考https://wiki.archlinux.org/index.php/Fcitx_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#.E8.BE.93.E5.85.A5.E6.B3.95

**Comment by happyaron** [comment]
我觉得没必要再添加这些没用的细节了，目前可以确认是搜狗拼音在dbus调用遇到问题时出现无限重试导致的，但还没搞清楚到底怎样触发，也就无法很好地解决掉。在dbus初始化出错、系统休眠后醒来的情况比较容易重现。

**Comment by kowr** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

**Comment by daya0576** [comment]
Is this issued solved now?  
I'm using unbuntu16.04 with latest sogou-pingyin and keep running into this problem.

**Comment by FindHao** [comment]
@daya0576  Try fictx -r. It can restart fcitx and solve the problem temporarily.

**Comment by arisliang** [comment]
when `fcitx -r`, sogou-pinyini crashes, and not working anymore. Anyway to restart sogou-pinyin?
I copied this issue to sogou forum (http://pinyin.sogou.com/bbs/forum.php?mod=viewthread&tid=2715949&extra=page%3D1).

**Comment by FindHao** [comment]
@arisliang Try `sogou-qimpanel &`. Actually after `fcitx -r`, the sogou input method will restart it self when you try to input something.

**Comment by arisliang** [comment]
@FindHao I uninstalled sogou and use googlepin, never gave problems.

**Comment by ThinkSora** [comment]
The same problem with Sogou installed. I have to kill fcitx every single time. Once it was killed, there is no problem and Sogou can be used normally.

**Comment by leaderkent** [comment]
open the sogou setting panel, and then close it. It helps me :p

**Comment by Mauhing** [comment]
> The same problem with Sogou installed. I have to kill fcitx every single time. Once it was killed, there is no problem and Sogou can be used normally.

Same here.  Since this post is closed. Is there any solution?

**Comment by shouldsee** [comment]
有没有人debug一下到底是sogoupinyin哪里出问题了? sogoupinyin用的还不错但是偶尔爆load还是不爽的.
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
```
