### ISSUE TITLE
Feature request: verticle punctuation (豎排標點) for Chinese

### ISSUE THREAD

**Issue by Lv-Zheng** [fcitx/fcitx#185]
A plugin or a button that toggles the horizontal or vertical of Chinese punctuation will be cool.
如果添加一個可以切換漢字橫或豎排標點符號的button那就太好了。比如

——
︱︱

and
與

「」
﹁﹂

Now there is not such function, and thus it's hard to edit vertical Chinese paragraphs.
現在沒有這個功能，編輯豎排漢字時很不方便。

Many thanks.
謝謝。

Regards,
Lv Zheng (呂正)

**Comment by wengxt** [comment]
There is no much key on keyboard so it can't be added to punc module, but anyway you can use quickphrase or unicode module to do it.

https://fcitx-im.org/wiki/QuickPhrase
