### ISSUE TITLE
Fcitx loses focus whenever a Chrome Desktop Notification pops up

### ISSUE THREAD

**Issue by wzyboy** [fcitx/fcitx#188]
Starting from Chromium v35 (the first version that adopts Aura framework), I'm having great difficulty using fcitx within Chromium / Google Chrome.

Steps to reproduce:
1. Make sure "Show desktop notifications" is allowed.
2. Use fcitx to type some Chinese in a textbox on a web page.
3. Trigger a desktop notification (exempli gratia: Gmail new mail, Telegram new message, WeChat new message, Pushbullet new push).
4. Fcitx loses focus and your joyful typing experience with fcitx is disrupted and you can only type English letters. The input status cannot be restored by hitting Ctrl + Space. You can only (for example) switch to another window and switch back to get it restored.

I am not sure whether this is an issue with fcitx or a bug of Aura. But it's really annoying if you type a lot in Chromium and get loads of notifications.

I've tried "Share state among window", "Do not commit when unfocus a window", and "Show Input Method Hint after Input Method changed and focus in" options, but they were doing no good.

If this is really Chromium's fault, could developers of fcitx suggest some workarounds to this problem?

**Comment by wengxt** [comment]
Report to chromium.
