### ISSUE TITLE
Unicode input: unable to select candidate with Alt + Num in Chrome

### ISSUE THREAD

**Issue by wzyboy** [fcitx/fcitx#189]
Starting with Chromium v35 (the first version that adopts Aura framework), the Unicode input mode in fcitx cannot be used properly.

In other programs, key combination "Ctrl + Alt + Shift + u" enters Unicode input method (great feature 👍), you type some description of a Unicode character, and you can select the candidate with Alt + Num.

But in Chromium / Google Chrome v35+, when in Unicode input method, the combination Alt + Num is intercepted by Cr, not by fctix. So you get tab switching instead of candidate choosing. (You can only use mouse-click to choose a candidate)

I am not sure whether this is an issue with fcitx or a bug of Aura. But could developers of fcitx suggest some workarounds towards this problem?

Thanks.

**Comment by dsdshcym** [comment]
Same problem here.

And not only "Alt + N" keybindings. Ctrl keybindings are intercepted by Chrome too.

Ctrl + 字母 之类的快捷键也无法起作用

**Comment by wengxt** [comment]
If the key is grabbed by the application itself, then I have no way to workaround that.

You can use mouse to select the candidate anyway.
