### ISSUE TITLE
default value for Font Locale to display is zh_CN.UTF-8 not reflecting users' locale

### ISSUE THREAD

**Issue by nobuto-m** [fcitx/fcitx#193]
Even with using ja_JP.UTF-8 locale, `Font Locale to display` in fcitx config dialogue shows zh_CN.UTF-8. It's defined at:
https://github.com/fcitx/fcitx/blob/master/src/ui/classic/fcitx-classic-ui.desc#L30-L34

Preferably users' locale(LC_CTYPE) is shown in the field.

**Comment by wengxt** [comment]
Well that doesn't really affect anything as long as your fcitx is built with pango.
