### ISSUE TITLE
fcitx 在gnome3.16上无法唤出

### ISSUE THREAD

**Issue by lvzongting** [fcitx/fcitx#200]
fcitx 在gnome3.16上无法唤出。

好像是和gdm3.16 有关系，降级成gdm3.14就可以了。

参考这个帖子
https://bbs.archlinuxcn.org/viewtopic.php?pid=22951

**Comment by yuyichao** [comment]
Gnome 启动了 `ibus` 之类的问题 fcitx 也没什么可以修的...

**Comment by wengxt** [comment]
I don't have problem with gdm 3.16.

**Comment by lvzongting** [comment]
可能因为我的 gdm 3.16 后端是wayland导致的。

**Comment by wengxt** [comment]
如果你用 wayland 方式启动 gnome 的话也许是不能用吧

选择用 X 的方式呢？

**Comment by lvzongting** [comment]
我手动选择X方式是没问题的，可以运行。
现在的情况是，新安装的archlinux，pacman -S gnome gdm 之后就默认是wayland方式，而且我还没搜到如何换成X方式，现在临时换成slim了。gdm3.14就没这问题，以前是默认X模式如果是wayland需要添加GDM_BACKEND=wayland，而现在gdm3.16没有设置BACKEND这一项，但是默认是wayland了。

**Comment by wengxt** [comment]
输入密码后 gdm 有个齿轮选择 session，在那选择 X 可以吗？

让 gdm 运行 X 可以修改 /etc/gdm/custom.conf

2015-04-26 23:48 GMT-04:00 lvzongting <notifications@github.com>:

**Comment by lvzongting** [comment]
给力！

**Comment by lvzongting** [comment]
上游给出了临时解决办法 
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'fcitx'>}"
亲测可以。
