### ISSUE TITLE
Can't use extra trigger key to activate input method after using it to inactive

### ISSUE THREAD

**Issue by CzBiX** [fcitx/fcitx#203]
![20150506-225118-a1f8](https://cloud.githubusercontent.com/assets/760097/7495773/a0860d18-f442-11e4-9563-bbcc55cd9974.png)

如图所示，当勾选这个 checkbox 时，在激活输入法的情况下，按 Shift 可以关闭输入法，但是之后多次按下 Shift 无任何反应（无法激活输入法）。

Ubuntu 15.04 + fcitx 4.2.8.5

**Comment by wengxt** [comment]
This is by design. To simulate the behavior of shift under windows.

**Comment by CzBiX** [comment]
那么请问图中选项的正确理解方式是怎样的？

另外 Windows 8 中的微软拼音，总是可以使用 Shift 键在中文和英文状态中切换。
你说的行为是什么情况或输入法才会出现？

**Comment by wengxt** [comment]
fcitx 的拼音并不像微软拼音自己有两个状态。每个都是单独的输入法。

假设输入法配置为 键盘 英语 - 美国 和 微软拼音
win 8 两个之间用 super + space 切换。

shift 切换事用于模拟微软拼音内部的两个状态。默认在英语美国状态不能默认切回去，只有用 shift 切到英语美国的状态可以再用shift切回去。

**Comment by CzBiX** [comment]
这么说来我的理解并没有错。
在 Windows 8 中的输入法，Super + Space 用于切换 Input Method, Shift 用于切换 Input Method 中的 English/Chinese mode。
而 Fcitx 只有 Input Method 的切换操作。

我的问题是：
我的 fcitx 里添加了两个 Input Method: Keyboard - Chinese 和 Wubi
当我在 Wubi 状态下时，我可以按 Shift 切换到 Keyboard - Chinese。**接着** 按下 Shift，期望行为是切回到 Wubi，而实际上没有任何反应，会停留在 Keyboard - Chinese。

另外我测试了下不勾选 "Use extra trigger key only after using it to inactivate" 时，Shift 可以正常在 Input Method 中来回切换没有问题。

**Comment by wengxt** [comment]
我测试了一下没有重现你的问题

**Comment by CzBiX** [comment]
我全新安装了一个 Ubuntu 15.04 + fcitx 4.2.8.5 ，确认问题可以稳定重现。

在安装完系统后依次操作 System Settings -> Language Support -> Install / Remove Languages... ->
选中 Chinese (simplified) -> Apply Changes（此时会自动安装 fcitx, fcitx-sunpinyin 等）->
重启电脑 -> 到 fcitx 设置面板的 Input Method 移除 Keyboard - English，添加 Sunpinyin ->
打开 gedit -> Super + Space 切换到 Sunpinyin -> 正常输入中文 -> 按下 Shift（切换到了 Keyboard - English）-> 正常输入英文 -> 按下 Shift（无任何反馈）

**Comment by CzBiX** [comment]
@wengxt 这个问题有望修复吗？我在全新安装的 Ubuntu 15.04 上是可以稳定重现的。

**Comment by wengxt** [comment]
看起来是因为 ubuntu 的 super space 的实现是他们通过 dbus 控制 fcitx 自己实现的。

**Comment by wengxt** [comment]
而且为什么要移除 keyboard english ?
fcitx-diagnose 的输出是什么？

**Comment by CzBiX** [comment]
移除 Keyboard English 是因为还有个 Keyboard Chinese，我认为只要保留一个 Keyboard 就可以了。
fcitx-diagnose 的输出：http://pastebin.com/a6nxQrXh

**Comment by CzBiX** [comment]
我看了下代码，主要的问题应该是 [ime.c#L698](https://github.com/fcitx/fcitx/blob/4.2.8.5/src/lib/fcitx/ime.c#L698) 的 switchBySwitchKey 值不对。
调试了下，发现是因为收到了 dbus 的 SetCurrentIM 消息([ipc.c#L636](https://github.com/fcitx/fcitx/blob/4.2.8.5/src/frontend/ipc/ipc.c#L636))，然后在 [ime.c#L1096](https://github.com/fcitx/fcitx/blob/4.2.8.5/src/lib/fcitx/ime.c#L1096) 调用了 FcitxInstanceCloseIM，然后调用 FcitxInstanceChangeIMState，导致输入法认为之前不是通过 SwitchKey 关闭的输入法。

我对 dbus 不太了解，怀疑是 fcitx 通知 dbus 变更了输入法，然后 dbus 又通知了 fcitx 导致的？
@wengxt ，从这些信息能看出来什么吗？

**Comment by wengxt** [comment]
你能重新描述一次你重现问题的按键顺序吗（从你现在刚登录系统开始，添加删除那部分就不用了）

你可以用 dbus-monitor interface=org.fcitx.Fcitx.InputMethod member=SetCurrentIM 看看什么情况会出现 SetCurrentIM

**Comment by CzBiX** [comment]
输出如下：
```
$ dbus-monitor 'interface=org.fcitx.Fcitx.InputMethod,member=SetCurrentIM'                                                                                                                          130 ↵
signal sender=org.freedesktop.DBus -> dest=:1.167 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.167"
# 启动 gedit
# 按下 Super + Space, 这时输入法变成 sunpinyin
method call sender=:1.10 -> dest=:1.152 serial=3253 path=/inputmethod; interface=org.fcitx.Fcitx.InputMethod; member=SetCurrentIM
   string "sunpinyin"
# 按下 Super + Space, 这时输入法变成 keyboard
method call sender=:1.10 -> dest=:1.152 serial=3261 path=/inputmethod; interface=org.fcitx.Fcitx.InputMethod; member=SetCurrentIM
   string "fcitx-keyboard-cn"
# 按下 Super + Space, 这时输入法变成 sunpinyin
method call sender=:1.10 -> dest=:1.152 serial=3267 path=/inputmethod; interface=org.fcitx.Fcitx.InputMethod; member=SetCurrentIM
   string "sunpinyin"
# 按下 Shift, 这时输入法变成 keyboard
method call sender=:1.10 -> dest=:1.152 serial=3276 path=/inputmethod; interface=org.fcitx.Fcitx.InputMethod; member=SetCurrentIM
   string "fcitx-keyboard-cn"
# 按下 Shift, 无任何反应
```
日志输出和输入法的变更基本是同时的发生的，没法判断先后。

**Comment by wengxt** [comment]
我想尝试用 fcitx-remote -s 来模拟这个行为，如果 SetCurrentIM 在实际的 shift 处理之后发生，调用 FcitxInstanceChangeIMState 在 https://github.com/fcitx/fcitx/blob/4.2.8.5/src/lib/fcitx/ime.c#L1566 的 check 就已经返回了。

不过你还是可以试试上面的那个hack有没有用

**Comment by CzBiX** [comment]
我将这个 patch 应用到 v4.2.8.5 上，测试没有修正问题。
我尝试把变量内容打出来，在按下 Shift 切换时，currentIM->uniqueName 是 sunpinyin，而 name 是 fcitx-keyboard-cn。

**Comment by wengxt** [comment]
ˊ_>ˋ ……你看看到底是那个进程在不断 SetCurrentIM

qdbus org.freedesktop.DBus / org.freedesktop.DBus.GetConnectionUnixProcessID ":1.10"
（:1.10 换成你在 dbus-monitor 里面见到的 sender）

**Comment by CzBiX** [comment]
```
$ dbus-monitor 'interface=org.fcitx.Fcitx.InputMethod,member=SetCurrentIM'
signal sender=org.freedesktop.DBus -> dest=:1.200 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.200"
method call sender=:1.10 -> dest=:1.189 serial=4537 path=/inputmethod; interface=org.fcitx.Fcitx.InputMethod; member=SetCurrentIM
   string "sunpinyin"
method call sender=:1.10 -> dest=:1.189 serial=4543 path=/inputmethod; interface=org.fcitx.Fcitx.InputMethod; member=SetCurrentIM
   string "fcitx-keyboard-cn"
^C
$ qdbus org.freedesktop.DBus / org.freedesktop.DBus.GetConnectionUnixProcessID ":1.10"
16397
$ ps x | grep 16397
16397 ?        Ssl    0:04 /usr/lib/unity-settings-daemon/unity-settings-daemon

```

**Comment by wengxt** [comment]
I think you should report it to ubuntu.

Function call fcitx_input_method_activate in unity-settings-daemon is not necessary.

**Comment by CzBiX** [comment]
尝试注释掉 `unity-settings-daemon` 中的所有 `fcitx_input_method_activate` 调用之后问题解决了，测试中也没发现其他问题。
已提交到上游，https://bugs.launchpad.net/ubuntu/+source/unity-settings-daemon/+bug/1494331
