### ISSUE TITLE
KDE5 下窗口出现黑边

### ISSUE THREAD

**Issue by Nuk9** [fcitx/fcitx#204]
升级KDE5后发现fcitx的输入框如截图所示，该黑边出现在所有app下的输入框中。

![photo 2015-05-31 16 07 43](https://cloud.githubusercontent.com/assets/502017/7903589/66327216-07af-11e5-85e5-142db799412e.jpg)

操作系统： openSUSE 13.2
KDE版本： 5.3.1
fcitx版本：4.2.8.6

**Comment by dirtycold** [comment]
是不是皮肤的问题？
和你一样的环境，用默认皮肤和milk（带半透明）都没有这个情况.

**Comment by qunxyz** [comment]
可以试试关掉fcitx，然后删除~/.config/fcitx目录，再重启fcitx看看。很多奇怪的问题，可以这样解决，应该 是有些环境变量没检测好

**Comment by wengxt** [comment]
ˊ_＞ˋ？没混成？
如果有混成还出现问题再reopen
