### ISSUE TITLE
debian Jessie session crash when enable fcitx  

### ISSUE THREAD

**Issue by snowpanzor** [fcitx/fcitx#207]
I've installed fcitx through apt-get, xsession crash everytime when I tried to enable fcitx. i've  tried few days.Anyone can help?

david@PC:~$ fcitx --version
fcitx version: 4.2.8.5
david@PC:~$ fcitx
david@PC:~$ (INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-xkbdbus.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-quickphrase.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-vk.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-clipboard.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-lua.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-chttrans.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-x11.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-kimpanel-ui.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-autoeng.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-spell.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-imselector.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-punc.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-dbus.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-ipc.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-fullwidth-char.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-xim.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-xkb.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-keyboard.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-notificationitem.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-classic-ui.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-freedesktop-notify.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-unicode.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-googlepinyin.conf
(INFO-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/addon.c:151) Load Addon Config File:fcitx-remote-module.conf
(WARN-8072 /tmp/buildd/fcitx-4.2.8.5/src/module/dbus/dbusstuff.c:246) DBus Service Already Exists
(ERROR-8072 /tmp/buildd/fcitx-4.2.8.5/src/lib/fcitx/instance.c:437) Exiting.
^C
david@PC:~$ fcitx-diagnose 
# System Info:
1.  `uname -a`:

        Linux PC 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Debian
        Description:	Debian GNU/Linux 8.1 (jessie)
        Release:	8.1
        Codename:	jessie

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux 8.1 (jessie)

4.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
        NAME="Debian GNU/Linux"
        VERSION_ID="8"
        VERSION="8 (jessie)"
        ID=debian
        HOME_URL="http://www.debian.org/"
        SUPPORT_URL="http://www.debian.org/support/"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  Desktop Environment:

    Cannot determine desktop environment.

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            C.UTF-8
            en_US.utf8
            POSIX
            zh_CN
            zh_CN.gb2312
            zh_CN.gbk
            zh_CN.utf8
            zh_TW
            zh_TW.big5
            zh_TW.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LANGUAGE=en_US:en
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/david

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/david/.config`).

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx` (`/home/david/.config/fcitx`).

5.  Current user:

    The script is run as david (1000).

# Fcitx State:
1.  executable:

    Found fcitx at `/usr/bin/fcitx`.

2.  version:

    Fcitx version: `4.2.8.5`

3.  process:

    Found 2 fcitx processes:

         6619 fcitx
         6636 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` works properly.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx-configtool at `/usr/bin/fcitx-configtool`.

2.  Config GUI for gtk2:

    **Config GUI for gtk2 not found.**

3.  Config GUI for gtk3:

    Found `fcitx-config-gtk3` at `/usr/bin/fcitx-config-gtk3`.

4.  Config GUI for kde:

    **`kcmshell4` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

3.  XIM for Emacs:

    **Your LC_CTYPE is set to en_US.UTF-8 instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT4_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:
    Found fcitx im module for Qt4: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.
    Found fcitx im module for Qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.25` at `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.25

        Found fcitx im modules for gtk `2.24.25`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.14.5` at `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.14.5

        Found fcitx im modules for gtk `3.14.5`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx addon config directory: `/usr/share/fcitx/addon`.

2.  Addon List:

    1.  Found 24 enabled addons:

            fcitx-autoeng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-googlepinyin
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-lua
            fcitx-notificationitem
            fcitx-punc
            fcitx-quickphrase
            fcitx-remote
            fcitx-spell
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    **Cannot find file `fcitx-xkbdbus.so` of addon `fcitx-xkbdbus`.**

    **Cannot find file `fcitx-keyboard.so` of addon `fcitx-keyboard`.**

    **Cannot find file `fcitx-vk.so` of addon `fcitx-vk`.**

    **Cannot find file `fcitx-autoeng.so` of addon `fcitx-autoeng`.**

    **Cannot find file `fcitx-x11.so` of addon `fcitx-x11`.**

    **Cannot find file `fcitx-classic-ui.so` of addon `fcitx-classic-ui`.**

    **Cannot find file `fcitx-notificationitem.so` of addon `fcitx-notificationitem`.**

    **Cannot find file `fcitx-quickphrase.so` of addon `fcitx-quickphrase`.**

    **Cannot find file `fcitx-lua.so` of addon `fcitx-lua`.**

    **Cannot find file `fcitx-fullwidth-char.so` of addon `fcitx-fullwidth-char`.**

    **Cannot find file `fcitx-unicode.so` of addon `fcitx-unicode`.**

    **Cannot find file `fcitx-googlepinyin.so` of addon `fcitx-googlepinyin`.**

    **Cannot find file `fcitx-spell.so` of addon `fcitx-spell`.**

    **Cannot find file `fcitx-xim.so` of addon `fcitx-xim`.**

    **Cannot find file `fcitx-freedesktop-notify.so` of addon `fcitx-freedesktop-notify`.**

    **Cannot find file `fcitx-kimpanel-ui.so` of addon `fcitx-kimpanel-ui`.**

    **Cannot find file `fcitx-clipboard.so` of addon `fcitx-clipboard`.**

    **Cannot find file `fcitx-dbus.so` of addon `fcitx-dbus`.**

    **Cannot find file `fcitx-punc.so` of addon `fcitx-punc`.**

    **Cannot find file `fcitx-xkb.so` of addon `fcitx-xkb`.**

    **Cannot find file `fcitx-imselector.so` of addon `fcitx-imselector`.**

    **Cannot find file `fcitx-ipc.so` of addon `fcitx-ipc`.**

    **Cannot find file `fcitx-chttrans.so` of addon `fcitx-chttrans`.**

    **Cannot find file `fcitx-remote-module.so` of addon `fcitx-remote`.**

4.  User Interface:

    Found 2 enabled user interface addons:

        fcitx-classic-ui
        fcitx-kimpanel-ui

## Input Methods:
1.  Found 2 enabled input methods:

        fcitx-keyboard-us
        googlepinyin

2.  Default input methods:

    You have a keyboard input method "fcitx-keyboard-us" correctly added as your default input method.

# Log:
1.  `date`:

        Sun Jun 28 07:48:24 CST 2015

2.  `~/.config/fcitx/log/`:

        total 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` not found.
david@PC:~$

**Comment by wengxt** [comment]
What actually crashed your desktop session?
What's your desktop then?

**Comment by snowpanzor** [comment]
I was forced to quit current desktop,return to the login screen.The error occured when I used xmonad and xfce. It worked perfectly on my old laptop. The only difference I know is the debian on my laptop was upgrade from wheezy.

**Comment by snowpanzor** [comment]
突然脑抽下载了一个搜狗拼音，安装，然后apt-get install -f ,再次安装，在xfce下成功启用fcitx，但在xmonad下依然是一使用ctrl+space 就会退出，和按了mod+shift+Q一样

**Comment by DigitalPig** [comment]
Hi,

Could we reopen this issue for fcitx? I saw the exactly same error output after upgrading to jessy. Fcitx keeps complaining that no addon libraries can be detected.

And here is the diagnosis file:

# System Info:
1.  `uname -a`:

        Linux digitalpig-lenovo 4.2.0-1-amd64 #1 SMP Debian 4.2.6-1 (2015-11-10) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Debian
        Description:	Debian GNU/Linux unstable (sid)
        Release:	unstable
        Codename:	sid

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux unstable (sid)

4.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux stretch/sid"
        NAME="Debian GNU/Linux"
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  Desktop Environment:

    Desktop environment is `xfce`.

7.  Bash Version:

        BASH_VERSION='4.3.42(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0.0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            C.UTF-8
            en_GB.utf8
            en_US.utf8
            ja_JP.utf8
            POSIX
            zh_CN.utf8
            zh_TW.utf8

    2.  Current locale:

            LANG=en_US.utf8
            LANGUAGE=
            LC_CTYPE="en_US.utf8"
            LC_NUMERIC="en_US.utf8"
            LC_TIME="en_US.utf8"
            LC_COLLATE="en_US.utf8"
            LC_MONETARY="en_US.utf8"
            LC_MESSAGES="en_US.utf8"
            LC_PAPER="en_US.utf8"
            LC_NAME="en_US.utf8"
            LC_ADDRESS="en_US.utf8"
            LC_TELEPHONE="en_US.utf8"
            LC_MEASUREMENT="en_US.utf8"
            LC_IDENTIFICATION="en_US.utf8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/digitalpig

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/digitalpig/.config`).

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx` (`/home/digitalpig/.config/fcitx`).

5.  Current user:

    The script is run as digitalpig (1000).

# Fcitx State:
1.  executable:

    Found fcitx at `/usr/bin/fcitx`.

2.  version:

    Fcitx version: `4.2.9`

3.  process:

    Found 2 fcitx processes:

         5144 fcitx
         5162 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` works properly.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx-configtool at `/usr/bin/fcitx-configtool`.

2.  Config GUI for gtk2:

    **Config GUI for gtk2 not found.**

3.  Config GUI for gtk3:

    Found `fcitx-config-gtk3` at `/usr/bin/fcitx-config-gtk3`.

4.  Config GUI for kde:

    **`kcmshell4` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT4_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:
    Found fcitx im module for Qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx im module for Qt4: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.28` at `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.28

        Found fcitx im modules for gtk `2.24.28`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.18.5` at `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.18.5

        Found fcitx im modules for gtk `3.18.5`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx addon config directory: `/usr/share/fcitx/addon`.

2.  Addon List:

    1.  Found 31 enabled addons:

            fcitx-autoeng
            fcitx-autoeng-ng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-fullwidth-char-enhance
            fcitx-googlepinyin
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-lua
            fcitx-mozc
            fcitx-notificationitem
            fcitx-punc
            fcitx-punc-ng
            fcitx-quickphrase
            fcitx-remote
            fcitx-rime
            fcitx-sogoucloudpinyin
            fcitx-sogoupinyin
            fcitx-spell
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  Found 1 disabled addons:

            fcitx-light-ui

3.  Addon Libraries:

    **Cannot find file `fcitx-xkbdbus.so` of addon `fcitx-xkbdbus`.**

    **Cannot find file `fcitx-keyboard.so` of addon `fcitx-keyboard`.**

    **Cannot find file `fcitx-mozc.so` of addon `fcitx-mozc`.**

    **Cannot find file `fcitx-vk.so` of addon `fcitx-vk`.**

    **Cannot find file `fcitx-autoeng.so` of addon `fcitx-autoeng`.**

    **Cannot find file `fcitx-x11.so` of addon `fcitx-x11`.**

    **Cannot find file `fcitx-classic-ui.so` of addon `fcitx-classic-ui`.**

    **Cannot find file `fcitx-notificationitem.so` of addon `fcitx-notificationitem`.**

    **Cannot find file `fcitx-fullwidth-char-enhance.so` of addon `fcitx-fullwidth-char-enhance`.**

    **Cannot find file `fcitx-quickphrase.so` of addon `fcitx-quickphrase`.**

    **Cannot find file `fcitx-lua.so` of addon `fcitx-lua`.**

    **Cannot find file `fcitx-fullwidth-char.so` of addon `fcitx-fullwidth-char`.**

    **Cannot find file `fcitx-rime.so` of addon `fcitx-rime`.**

    **Cannot find file `fcitx-unicode.so` of addon `fcitx-unicode`.**

    **Cannot find file `fcitx-sogoupinyin.so` of addon `fcitx-sogoucloudpinyin`.**

    **Cannot find file `fcitx-googlepinyin.so` of addon `fcitx-googlepinyin`.**

    **Cannot find file `fcitx-spell.so` of addon `fcitx-spell`.**

    **Cannot find file `fcitx-xim.so` of addon `fcitx-xim`.**

    **Cannot find file `fcitx-freedesktop-notify.so` of addon `fcitx-freedesktop-notify`.**

    **Cannot find file `fcitx-kimpanel-ui.so` of addon `fcitx-kimpanel-ui`.**

    **Cannot find file `fcitx-autoeng-ng.so` of addon `fcitx-autoeng-ng`.**

    **Cannot find file `fcitx-clipboard.so` of addon `fcitx-clipboard`.**

    **Cannot find file `fcitx-light-ui.so` of addon `fcitx-light-ui`.**

    **Cannot find file `fcitx-punc-ng.so` of addon `fcitx-punc-ng`.**

    **Cannot find file `fcitx-dbus.so` of addon `fcitx-dbus`.**

    **Cannot find file `fcitx-punc.so` of addon `fcitx-punc`.**

    **Cannot find file `fcitx-xkb.so` of addon `fcitx-xkb`.**

    **Cannot find file `fcitx-imselector.so` of addon `fcitx-imselector`.**

    **Cannot find file `fcitx-ipc.so` of addon `fcitx-ipc`.**

    **Cannot find file `fcitx-chttrans.so` of addon `fcitx-chttrans`.**

    **Cannot find file `fcitx-remote-module.so` of addon `fcitx-remote`.**

    **Cannot find file `fcitx-sogoupinyin.so` of addon `fcitx-sogoupinyin`.**

4.  User Interface:

    Found 2 enabled user interface addons:

        fcitx-classic-ui
        fcitx-kimpanel-ui

## Input Methods:
1.  Found 2 enabled input methods:

        fcitx-keyboard-us
        sogoupinyin

2.  Default input methods:

    You have a keyboard input method "fcitx-keyboard-us" correctly added as your default input method.

# Log:
1.  `date`:

        Sat Nov 28 18:52:38 EST 2015

2.  `~/.config/fcitx/log/`:

        total 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` not found.

**Comment by JackieMium** [comment]
Exactly the same problem here. Debian Jessie, Xfce4, Fcitx with Google Pinyin. 
Whenever I try to input something with Fcitx on, desktop crash out and I'm back to lightdm login page. 
`fcitx-diagnose` output seemed the same as above.  Solution in #234 won't work.
