### ISSUE TITLE
 candidate window isn't located under composing string when HiDPI setting

### ISSUE THREAD

**Issue by makotokato** [fcitx/fcitx#211]
When using HiDPI setting on GNOME 3, candidate window is located on invalid position.

Env
=
GNOME 3.16
GTK 3.16
fcitx-mozc 1.4.2.8.5

Step
=
1. gsettings set org.gnome.desktop.interface scaling-factor 2
2. Restart GNOME Shell
3. Launch gnome-terminal
4. Input ああああ using fcitx-mozc

Result
=
Candidate window position isn't under composing string.

![screenshot from 2015-07-08 14-31-09](https://cloud.githubusercontent.com/assets/965338/8563810/dbda03e8-257e-11e5-9d97-7cf71b1b7b98.png)

**Comment by wengxt** [comment]
Hi, please check master and see if this is fixed.
https://github.com/fcitx/fcitx/commit/859681e8e6e1250654edf297948d3dcefef31c89
https://github.com/fcitx/fcitx/commit/c3e273f18af2160c916d7fad0a451ee230313e14
