### ISSUE TITLE
Do you have any ideas about fcitx-mozc breakage?

### ISSUE THREAD

**Issue by heathross** [fcitx/fcitx#212]
Mozc break downstream projects without any notice.
They say "we don't have enough engineering resources to make sure that
our changes do not break any downstream projects".
google/mozc#293
Do you have any ideas about this?
Please post it to #293.

**Comment by happyaron** [comment]
Not what we can control. Btw fcitx-mozc is now default for Ubuntu 15.10 under ja_JP locale.
