### ISSUE TITLE
選字框內是錯誤的字型，希望可以更正

### ISSUE THREAD

**Issue by laichiaheng** [fcitx/fcitx#216]
![](http://i.imgur.com/hB9OFGo.jpg)

![](http://i.imgur.com/ROIBUSv.jpg)

![](http://i.imgur.com/HTwn0Gw.jpg)

選字的字體和我實際輸出的完全不同，我是用思源黑體

**Comment by yuyichao** [comment]
这是字体设置的问题吧.....

**Comment by laichiaheng** [comment]
@yuyichao 我系統內設置了思源黑體，Firefox內文字也是思源黑體，但是選字框內的沒有改變

**Comment by yuyichao** [comment]
在输入法设置里面改字体.

**Comment by yuyichao** [comment]
根据你的 [配置工具和界面](https://fcitx-im.org/wiki/Integrate_with_Desktop/zh-cn) 在插件的选项里面改字体.

**Comment by laichiaheng** [comment]
@yuyichao 原來那邊也要設置，感謝了
