### ISSUE TITLE
vncserver里fcitx起不来

### ISSUE THREAD

**Issue by lenky0401** [fcitx/fcitx#218]
一，现场环境：
1，Server：ubuntu 14.10，安装了vnc4server，配置很简单：

lenky@lenky-Inspiron-545s:~$ cat .vnc/xstartup 
#!/bin/sh

#Uncomment the following two lines for normal desktop:
unset SESSION_MANAGER
#exec /etc/X11/xinit/xinitrc

#[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &

exec mate-session &
#exec xfce4-session &

通过vncserver :1启动。

2，Client，使用vncviewer 192.168.30.243:1
连接。

二，进入后，fcitx没启动，打开终端，执行fcitx，fcitx normally exit。
跟踪发现是FcitxXErrorHandler里调用了FcitxInstanceEnd，设置了destroy字段，导致fcitx退出。堆栈如下：
(gdb) p *event
$3 = {type = 0, display = 0x80d2678, resourceid = 2, serial = 98, error_code = 2 '\002', request_code = 128 '\20
0', minor_code = 2 '\002'}
(gdb) bt
#0  FcitxXErrorHandler (dpy=0x80d2678, event=0xbffff04c) at /home/lenky/fcitx/fcitx-4.2.8.5/src/module/x11/xerro
rhandler.c:88
#1  0xb79e427a in _XError (dpy=0x80d2678, rep=0x8469748) at ../../src/XlibInt.c:1463
#2  0xb79e131b in handle_error (dpy=dpy@entry=0x80d2678, err=0x8469748, in_XReply=0) at ../../src/xcb_io.c:213
#3  0xb79e13d6 in handle_response (dpy=dpy@entry=0x80d2678, response=0x8469748, in_XReply=0) at ../../src/xcb_io
.c:325
#4  0xb79e1c0e in _XEventsQueued (dpy=0x80d2678, mode=2) at ../../src/xcb_io.c:364
(More stack frames follow...)
#5  0xb79d3672 in XPending (dpy=0x80d2678) at ../../src/Pending.c:55
#6  0xb7b823a1 in X11ProcessEventRealInternal (x11priv=0x80d25e8) at /home/lenky/fcitx/fcitx-4.2.8.5/src/module/
x11/x11stuff.c:180
#7  0xb7b823dc in X11ProcessEvent (arg=0x80d25e8) at /home/lenky/fcitx/fcitx-4.2.8.5/src/module/x11/x11stuff.c:2
25
#8  0xb7f9b400 in RunInstance (arg=0x804c938) at /home/lenky/fcitx/fcitx-4.2.8.5/src/lib/fcitx/instance.c:328
#9  0xb7f9ac29 in FcitxInstanceRun (argc=2, argv=0xbffff424, fd=8) at /home/lenky/fcitx/fcitx-4.2.8.5/src/lib/fc
itx/instance.c:140
#10 0x08048e0e in main (argc=2, argv=0xbffff424) at /home/lenky/fcitx/fcitx-4.2.8.5/src/core/fcitx.c:80

三，尝试：
虽然不懂，但直接把FcitxInstanceEnd(x11handle->owner);注释掉，即这一行：
https://github.com/fcitx/fcitx/blob/master/src/module/x11/xerrorhandler.c#L91
前面加//

fcitx启动ok，竟然也可以使用。

四：求助：
目前云桌面用得越来越多，而且不用启动图形的远程桌面（vncserver这种）比其他方式（比如vino，fcitx没问题）要好，所以看能否解决这个问题？

我正在查，但相关知识明显不足，求各位大神指点。

**Comment by lenky0401** [comment]
直接忽略了，竟然也可以用，先就这样了，虽然不知道为什么会收到2号错误码。

**Comment by happyaron** [comment]
vino 没问题的话vnc方式就应该是没有问题的，但是目前rdp协议下有问题，然后如果直接跑X11 over tcp的话会出现有preedit且能正常commit，但看不到候选窗口的问题（界面配置为kimpanel协议的其他程序时）。
