### ISSUE TITLE
fcitx change keyboard key map

### ISSUE THREAD

**Issue by EvinceMoi** [fcitx/fcitx#221]
I use `xmodmap` to re-map some keys, but each time fcitx starts, the mapped key scheme losts, I need to execute `xmodmap` again. Is that expected?

**Comment by wengxt** [comment]
Yes. You can put your xmodmap stuff in ~/.Xmodmap and let fcitx load it for you.

https://fcitx-im.org/wiki/FAQ#xmodmap_settings_being_overwritten

**Comment by neilwangsprd** [comment]
so, if i use setxkbmap, what should i do? isn't it wiser to have a switch to control it ?
