### ISSUE TITLE
在 Salix linux 上 Fcitx 奇怪的行为。

### ISSUE THREAD

**Issue by zw963** [fcitx/fcitx#223]
相关的讨论在这里： http://forum.salixos.org/viewtopic.php?f=16&t=6123

写了很多，而且很罗嗦，而且英文太差，建议跳着看, 问题重现的步骤如下：

1. install skype with package (a 32bit qt application with lots of 32 bit library)
2. start emacs daemon with: `emacs --daemon'
3. start a emacsclient to connect to this daemon with: `emacsclient -nc 1.rb'
    if correctly, you will see a new emacs window is created. (ensure not started inside terminal)
4. active fcitx, it worked now.
5. 'Ctrl-x Ctrl-c' exit emacsclient.
6. run skype and exit skype (32bit qt application)
7. start emacsclient again with `emacsclient -nc 1.rb', create a new emacsclient window.
8. can not active fcitx with hotkey.

请问这是怎么回事儿？ 为什么 32bit qt 程序，造成 fcitx 在 emacs 中的快捷键失效？
这仍旧是 Emacs 的 bug 还是 fcitx 的 bug? 但是在其他应用程序中，却没事儿。

好吧，也许还是 Emacs 惹得祸，无论如何，请给一些提示, 谢谢。

另一个疑问：

```
Re: Emacs 24.3 with FCITX input methods[09/17 Update]

Postby tsuren » 6. Sep 2015, 18:12
Have you also tried this?
If I disable xim on emacs by adding:
    Emacs*UseXIM:false
in the ~/.Xresources, fcitx is not activated for sure with ctrl + space. My guess right now is probably fcitx is not fully compatible to emacs... 
```

我在想， 我用的 Emacs 是 GTK2 版本的。
```sh
GNU Emacs 24.3.1 (x86_64-slackware-linux-gnu, GTK+ Version 2.24.17)
```

为什么 Emacs 关闭 XIM 支持， Fcitx 的 GTK+ 模块并没有生效?

**Comment by wengxt** [comment]
我不认为这和 skype 有啥关系，单纯是 emacsclient 和输入法之间的问题吧

尽管 Emacs 是 gtk 的界面 ˊ_>ˋ ，但是他是直接用 libx11 的 xim 实现输入法支持的一个奇葩。

@yuyichao emacs 用户来说说

**Comment by zw963** [comment]
@wengxt 

>>   我不认为这和 skype 有啥关系，单纯是 emacsclient 和输入法之间的问题吧

如果不启动 Skype 或任何其他 32bit 程序， 例如： beyond compare 之类的，
貌似我的 emacsclient 和 fcitx 工作的好好的？

>> 尽管 Emacs 是 gtk 的界面 ˊ_>ˋ ，但是他是直接用 libx11 的 xim 实现输入法支持的一个奇葩。

很奇怪，为什么没有人给 Gnu emacs 提这个 issue ?

**Comment by zw963** [comment]
根据这篇文章的介绍，http://tech.memoryimprintstudio.com/?p=174

我做了如下事情：

1.  设定 ~/.Xresources
```sh
☠  $ cat ~/.Xresources 
Emacs*UseXIM:false
```

2. 在 Emacs 中设定 ``(setq inhibit-x-resources t)`` 为 true.
根据 Emacs 的 help 如下：

```sh
Documentation:
If non-nil, X resources, Windows Registry settings, and NS defaults are not used.
```

仍然可以激活 FCITX 输入法， 这说明什么？

但是启动一个 QT 32bit 应用程序， 仍然造成无法再次在 emacs 中激活，问题依旧。

**Comment by zw963** [comment]
再请教一个困扰我很久的一个问题：

```sh
export LANG=en_US.utf8
export LC_CTYPE=zh_CN.utf8
```
和 
```sh
export LANG=en_US.UTF-8
export LC_CTYPE=zh_CN.UTF-8
```
到底有啥区别？

**Comment by wengxt** [comment]
应该是为了在不同 Emacs 库之间能 share 代码，这不能算 bug 吧。
我又不写 emacs 的代码我也不知道很详细发生了什么。而且我按你的步骤也没重现问题 ˊ_>ˋ ……

$ emacs --version
GNU Emacs 24.5.1

locale 那个没啥区别，我在几年前曾遇见 gvim 用 .utf8 的 locale 时候显示不了中文，现在应该没什么关系了

**Comment by zw963** [comment]
在相关的讨论中,  发现了这个链接 
http://lists.gnu.org/archive/html/bug-gnu-emacs/2012-02/msg00761.html

请问这个问题在最新的版本中修复了吗？
