### ISSUE TITLE
[!] Fcitx 无法在Chrome等大部分软件中使用，已知只有mousepad可以用！

### ISSUE THREAD

**Issue by MuSamDu** [fcitx/fcitx#226]
#### 系统：
Xubunut 15.10 Wily Werewolf
#### 症状：
如题。且diagnose显示：   
>2.  `gtk-query-immodules`:
>
>    1.  gtk 2:
>
>        **无法找到 gtk 2 的 `gtk-query-immodules`.**
>
>        **无法找到 gtk 2 的 fcitx 输入法模块.**
>
>    2.  gtk 3:
>
>        **无法找到 gtk 3 的 `gtk-query-immodules`.**
>
>        **无法找到 gtk 3 的 fcitx 输入法模块.**
>

麻烦解决一下，谢谢！   
*****
# 附诊断信息：   
*****
msd@MSD-Xubuntu-Home:~$ fcitx-diagnose
# 系统信息:
1.  `uname -a`:

        Linux MSD-Xubuntu-Home 4.2.0-10-generic #12-Ubuntu SMP Tue Sep 15 19:43:01 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Ubuntu
        Description:	Ubuntu Wily Werewolf (development branch)
        Release:	15.10
        Codename:	wily

3.  `lsb_release -d`:

        Description:	Ubuntu Wily Werewolf (development branch)

4.  `/etc/lsb-release`:

        DISTRIB_ID=Ubuntu
        DISTRIB_RELEASE=15.10
        DISTRIB_CODENAME=wily
        DISTRIB_DESCRIPTION="Ubuntu Wily Werewolf (development branch)"

5.  `/etc/os-release`:

        NAME="Ubuntu"
        VERSION="15.10 (Wily Werewolf)"
        ID=ubuntu
        ID_LIKE=debian
        PRETTY_NAME="Ubuntu Wily Werewolf (development branch)"
        VERSION_ID="15.10"
        HOME_URL="http://www.ubuntu.com/"
        SUPPORT_URL="http://help.ubuntu.com/"
        BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

6.  桌面环境:

    桌面环境为 `xfce`。

7.  Bash Version:

        BASH_VERSION='4.3.42(1)-release'

# 环境:
1.  DISPLAY:

        DISPLAY=':0.0'

2.  键盘布局:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+cn+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "cn", "", ""

3.  Locale:

    1.  全部可用 locale:

            C
            C.UTF-8
            de_CH.utf8
            en_AG
            en_AG.utf8
            en_AU.utf8
            en_BW.utf8
            en_CA.utf8
            en_DK.utf8
            en_GB.utf8
            en_HK.utf8
            en_IE.utf8
            en_IN
            en_IN.utf8
            en_NG
            en_NG.utf8
            en_NZ.utf8
            en_PH.utf8
            en_SG.utf8
            en_US.utf8
            en_ZA.utf8
            en_ZM
            en_ZM.utf8
            en_ZW.utf8
            POSIX
            zh_CN.utf8
            zh_SG.utf8

    2.  当前 locale:

            LANG=zh_CN.UTF-8
            LANGUAGE=zh_CN:zh:en_US:en
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC=zh_CN.UTF-8
            LC_TIME=zh_CN.UTF-8
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY=zh_CN.UTF-8
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER=zh_CN.UTF-8
            LC_NAME=zh_CN.UTF-8
            LC_ADDRESS=zh_CN.UTF-8
            LC_TELEPHONE=zh_CN.UTF-8
            LC_MEASUREMENT=zh_CN.UTF-8
            LC_IDENTIFICATION=zh_CN.UTF-8
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/msd

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/msd/.config`)。

    3.  Fcitx 设置目录：

        当前 fcitx 设置目录是 `~/.config/fcitx` (`/home/msd/.config/fcitx`)。

5.  当前用户：

    脚本作为 msd (1000) 运行。

# Fcitx 状态:
1.  可执行文件:

    在 `/usr/bin/fcitx` 找到了 fcitx.

2.  版本:

    Fcitx 版本: `4.2.9`

3.  进程:

    找到了 2 个 fcitx 进程:

         8347 fcitx
         8432 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` 工作正常.

# Fcitx 配置界面:
1.  配置工具封装：

    在 `/usr/bin/fcitx-configtool` 找到了 fcitx-configtool。

2.  用于 GTK+-2.0 的配置界面：

    在 `/usr/bin/fcitx-config-gtk` 找到了 `fcitx-config-gtk`。

3.  用于 GTK+-3.0 的配置界面：

    在 `/usr/bin/fcitx-config-gtk3` 找到了 `fcitx-config-gtk3`。

4.  KDE 的配置界面：

    **`kcmshell4` 未找到.**

# 前端设置:
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了 "@im=fcitx".
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS:

    Xim 服务的名称与环境变量中设置的相同.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT4_IM_MODULE 已经正确地设为了 "fcitx".

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".

3.  Qt 输入法模块文件:
    找到了 Qt4 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.
    找到了 Qt5 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了 "fcitx".

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`.**

        **无法找到 gtk 2 的 fcitx 输入法模块.**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`.**

        **无法找到 gtk 3 的 fcitx 输入法模块.**

3.  Gtk 输入法模块缓存:

    1.  gtk 2:

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.28` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.28

        **无法输入法模块缓存 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 中找到 fcitx**

        **无法在缓存中找到 gtk 2 的 fcitx 输入法模块.**

    2.  gtk 3:

        在 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.16.6` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.16.6

        **无法输入法模块缓存 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 中找到 fcitx**

        **无法在缓存中找到 gtk 3 的 fcitx 输入法模块.**

4.  Gtk 输入法模块文件:

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在.

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在.

# 配置:
## Fcitx 插件:
1.  插件配置文件目录:

    找到了 fcitx 插件配置目录: `/usr/share/fcitx/addon`.

2.  插件列表:

    1.  找到了 30 个已启用的插件:

            fcitx-autoeng
            fcitx-autoeng-ng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-fullwidth-char-enhance
            fcitx-googlepinyin
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-lua
            fcitx-notificationitem
            fcitx-punc
            fcitx-punc-ng
            fcitx-quickphrase
            fcitx-remote
            fcitx-sogoucloudpinyin
            fcitx-sogoupinyin
            fcitx-spell
            fcitx-sunpinyin
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  找到了 0 个被禁用的插件:

3.  插件库:

    所有插件所需的库都被找到。

4.  用户界面:

    找到了 2 个已启用的用户界面插件:

        fcitx-classic-ui
        fcitx-kimpanel-ui

    Kimpanel 进程:

         8677 sogou-qimpanel

## 输入法:
1.  找到了 4 个启用的输入法:

        fcitx-keyboard-cn
        googlepinyin
        sogoupinyin
        sunpinyin

2.  默认输入法:

    您已经正确的将一个键盘输入法 "fcitx-keyboard-cn" 设为默认.

# 日志:
1.  `date`:

        2015年 09月 20日 星期日 14:39:40 CST

2.  `~/.config/fcitx/log/`:

        总用量 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` 未找到.

**Comment by happyaron** [comment]
打开 APT 的 Recommends，然后安装 fcitx-frontend-all.

**Comment by MuSamDu** [comment]
##Done! Thanks!!!
