### ISSUE TITLE
Combining GTK + XIM

### ISSUE THREAD

**Issue by wavexx** [fcitx/fcitx#231]
This is more of a support request than a real issue, so I apologize in advance.

In one application I'm working on (https://github.com/wavexx/screenkey) I'm opening an independent connection using Xlib and use XIM to perform key composition, which works just fine.

It seems, however, that if I also use GTK (pygtk in this case), a further call to XOpenIM() fails and returns NULL, despite the fact that I'm using an *independent* connection to the display server. The same approach using IBUS instead works as it should.

A minimal test case, written in python (2.7 + pygtk), is the following:

````
#!/usr/bin/env python
from ctypes import *
libX11 = CDLL('libX11.so.6')

class Display(Structure):
    pass

XOpenDisplay = libX11.XOpenDisplay
XOpenDisplay.argtypes = [c_char_p]
XOpenDisplay.restype = POINTER(Display)

class _XIM(Structure):
    pass

XIM = POINTER(_XIM)

class _XrmDatabase(Structure):
    pass

XrmDatabase = POINTER(_XrmDatabase)

XOpenIM = libX11.XOpenIM
XOpenIM.argtypes = [POINTER(Display), XrmDatabase, c_char_p, c_char_p]
XOpenIM.restype = XIM

import gtk

dpy = XOpenDisplay(None)
xim = XOpenIM(dpy, None, None, None)
if not xim:
    raise Exception("Cannot initialize input method")
````

If you comment out the import of gtk, there's no subsequent problem.
Do you have any idea as of why this fails? Some per-program state?
Is this expected?

I'm not familiar enough with fcitx (I'm trying to debug a reported issue), as I normally use ibus.

**Comment by wengxt** [comment]
I have no problem running your test program on my machine. And I don't see any reason that this can't work. After all, no one ever report gtk's xim im module doesn't work, in theory it's calling the same function.

Maybe paste your fcitx-diagnose output here and see what's going wrong.
