### ISSUE TITLE
Fcitx in Debian Sid cannot use any installed input method under en.US_UTF8 environment

### ISSUE THREAD

**Issue by DigitalPig** [fcitx/fcitx#234]
Hi,

I recently updated my system to Debian Sid. But the fcitx does not work anymore. I cannot add any input method into fcitx although I installed them. Here is the diagnosis file:

# System Info:
1.  `uname -a`:

        Linux digitalpig-lenovo 4.2.0-1-amd64 #1 SMP Debian 4.2.6-1 (2015-11-10) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Debian
        Description:	Debian GNU/Linux unstable (sid)
        Release:	unstable
        Codename:	sid

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux unstable (sid)

4.  `/etc/lsb-release`:

    `/etc/lsb-release` not found.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux stretch/sid"
        NAME="Debian GNU/Linux"
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  Desktop Environment:

    Desktop environment is `xfce`.

7.  Bash Version:

        BASH_VERSION='4.3.42(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0.0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  All locale:

            C
            C.UTF-8
            en_GB.utf8
            en_US.utf8
            ja_JP.utf8
            POSIX
            zh_CN.utf8
            zh_TW.utf8

    2.  Current locale:

            LANG=en_US.utf8
            LANGUAGE=
            LC_CTYPE="en_US.utf8"
            LC_NUMERIC="en_US.utf8"
            LC_TIME="en_US.utf8"
            LC_COLLATE="en_US.utf8"
            LC_MONETARY="en_US.utf8"
            LC_MESSAGES="en_US.utf8"
            LC_PAPER="en_US.utf8"
            LC_NAME="en_US.utf8"
            LC_ADDRESS="en_US.utf8"
            LC_TELEPHONE="en_US.utf8"
            LC_MEASUREMENT="en_US.utf8"
            LC_IDENTIFICATION="en_US.utf8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/digitalpig

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/digitalpig/.config`).

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx` (`/home/digitalpig/.config/fcitx`).

5.  Current user:

    The script is run as digitalpig (1000).

# Fcitx State:
1.  executable:

    Found fcitx at `/usr/bin/fcitx`.

2.  version:

    Fcitx version: `4.2.9`

3.  process:

    Found 2 fcitx processes:

         5144 fcitx
         5162 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` works properly.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx-configtool at `/usr/bin/fcitx-configtool`.

2.  Config GUI for gtk2:

    **Config GUI for gtk2 not found.**

3.  Config GUI for gtk3:

    Found `fcitx-config-gtk3` at `/usr/bin/fcitx-config-gtk3`.

4.  Config GUI for kde:

    **`kcmshell4` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT4_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:
    Found fcitx im module for Qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx im module for Qt4: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.28` at `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.28

        Found fcitx im modules for gtk `2.24.28`.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        Found immodules cache for gtk `3.18.5` at `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.18.5

        Found fcitx im modules for gtk `3.18.5`.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx addon config directory: `/usr/share/fcitx/addon`.

2.  Addon List:

    1.  Found 31 enabled addons:

            fcitx-autoeng
            fcitx-autoeng-ng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-fullwidth-char-enhance
            fcitx-googlepinyin
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-lua
            fcitx-mozc
            fcitx-notificationitem
            fcitx-punc
            fcitx-punc-ng
            fcitx-quickphrase
            fcitx-remote
            fcitx-rime
            fcitx-sogoucloudpinyin
            fcitx-sogoupinyin
            fcitx-spell
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  Found 1 disabled addons:

            fcitx-light-ui

3.  Addon Libraries:

    **Cannot find file `fcitx-xkbdbus.so` of addon `fcitx-xkbdbus`.**

    **Cannot find file `fcitx-keyboard.so` of addon `fcitx-keyboard`.**

    **Cannot find file `fcitx-mozc.so` of addon `fcitx-mozc`.**

    **Cannot find file `fcitx-vk.so` of addon `fcitx-vk`.**

    **Cannot find file `fcitx-autoeng.so` of addon `fcitx-autoeng`.**

    **Cannot find file `fcitx-x11.so` of addon `fcitx-x11`.**

    **Cannot find file `fcitx-classic-ui.so` of addon `fcitx-classic-ui`.**

    **Cannot find file `fcitx-notificationitem.so` of addon `fcitx-notificationitem`.**

    **Cannot find file `fcitx-fullwidth-char-enhance.so` of addon `fcitx-fullwidth-char-enhance`.**

    **Cannot find file `fcitx-quickphrase.so` of addon `fcitx-quickphrase`.**

    **Cannot find file `fcitx-lua.so` of addon `fcitx-lua`.**

    **Cannot find file `fcitx-fullwidth-char.so` of addon `fcitx-fullwidth-char`.**

    **Cannot find file `fcitx-rime.so` of addon `fcitx-rime`.**

    **Cannot find file `fcitx-unicode.so` of addon `fcitx-unicode`.**

    **Cannot find file `fcitx-sogoupinyin.so` of addon `fcitx-sogoucloudpinyin`.**

    **Cannot find file `fcitx-googlepinyin.so` of addon `fcitx-googlepinyin`.**

    **Cannot find file `fcitx-spell.so` of addon `fcitx-spell`.**

    **Cannot find file `fcitx-xim.so` of addon `fcitx-xim`.**

    **Cannot find file `fcitx-freedesktop-notify.so` of addon `fcitx-freedesktop-notify`.**

    **Cannot find file `fcitx-kimpanel-ui.so` of addon `fcitx-kimpanel-ui`.**

    **Cannot find file `fcitx-autoeng-ng.so` of addon `fcitx-autoeng-ng`.**

    **Cannot find file `fcitx-clipboard.so` of addon `fcitx-clipboard`.**

    **Cannot find file `fcitx-light-ui.so` of addon `fcitx-light-ui`.**

    **Cannot find file `fcitx-punc-ng.so` of addon `fcitx-punc-ng`.**

    **Cannot find file `fcitx-dbus.so` of addon `fcitx-dbus`.**

    **Cannot find file `fcitx-punc.so` of addon `fcitx-punc`.**

    **Cannot find file `fcitx-xkb.so` of addon `fcitx-xkb`.**

    **Cannot find file `fcitx-imselector.so` of addon `fcitx-imselector`.**

    **Cannot find file `fcitx-ipc.so` of addon `fcitx-ipc`.**

    **Cannot find file `fcitx-chttrans.so` of addon `fcitx-chttrans`.**

    **Cannot find file `fcitx-remote-module.so` of addon `fcitx-remote`.**

    **Cannot find file `fcitx-sogoupinyin.so` of addon `fcitx-sogoupinyin`.**

4.  User Interface:

    Found 2 enabled user interface addons:

        fcitx-classic-ui
        fcitx-kimpanel-ui

## Input Methods:
1.  Found 2 enabled input methods:

        fcitx-keyboard-us
        sogoupinyin

2.  Default input methods:

    You have a keyboard input method "fcitx-keyboard-us" correctly added as your default input method.

# Log:
1.  `date`:

        Sat Nov 28 18:52:38 EST 2015

2.  `~/.config/fcitx/log/`:

        total 0

3.  `~/.config/fcitx/log/crash.log`:

    `~/.config/fcitx/log/crash.log` not found.

**Comment by fu-sen** [comment]
Hi,

I encountered the same problem when you set the Fcitx Use the "export" in antiX-15:

https://gist.github.com/fu-sen/6661b6bb289617370c40

In many cases, this is used to set using the im-config, not encounter this problem.
antiX-15 because you are using SLiM to DM, im-config does not work.

If you have to recognize the Fcitx in export would be avoided in the setting using the im-config:

$ im-config -n fcitx

**Comment by fu-sen** [comment]
I found some of the same report:
https://github.com/fcitx/fcitx/issues/207
https://github.com/fcitx/fcitx/issues/197

**Comment by wengxt** [comment]
Most probably a configuration issue. Try to play with im-config. Or if you don't want to use it, remove it and follow https://fcitx-im.org/wiki/Configure_(Other) may help.

**Comment by fu-sen** [comment]
No. This might Fcitx has had a bug recently.

I use Fcitx in much Linux and, I grasp information of this neighborhood.

Fcitx it was working normally a few months ago and currently not running.

This is peculiar to Debian and may have a problem. (It there is a possibility of later jessie)
Because this does not occur in im-config, there are few reports of this problem,
but it may be necessary to be careful about these reports.

**Comment by wengxt** [comment]
I pretty sure usually this is a desktop environment problem or a distro tool problem, but not in fcitx itself. Report the problem here doesn't help (I don't use debian), if you think this is a issue you should report it to debian.

**Comment by DigitalPig** [comment]
Hi,

Thanks for the reply. I agree this is a Debian package issue because the issue vanished on Ubuntu. After installing fcitx, I have run im-config to set the fcitx as my main input. I have submitted a bug report to debian bug system as well. However, I'd like to try to fix the problem a little bit but I have no clue where to start.

Those libraries are all under /usr/lib/x86_64-linux-gnu. I guess maybe the fcitx is looking for those libraries in other places. Any idea how I can explicitly ask fcitx to look?

Thank you for the help again.

**Comment by DigitalPig** [comment]
OK. I found the reason why fcitx-diagnosis complains about library is because I don't have fcitx4-config in my path. I installed fcitx-lib-dev package and the complain goes away.

HOWEVER, I still cannot add any input method in my fcitx. I can see fcitx-rime plugins in the Addon tab by fcitx-configtool but the "Configure" button is grey....

**Comment by DigitalPig** [comment]
All right. Finally I solve the problem! (why I am still use English... =.=b)

Debian的Sid安装出来的fcitx-configtool有bug无法显示系统安装的全部输入法。work-around的方法是到$HOME/.config/fcitx/profile里面找到Enable IM List，手动修改你想使用的输入法为True。这样就可以用了。

**Comment by wengxt** [comment]
@DigitalPig what's the version of fcitx-config-gtk{,3}? Can you post a screenshot? or maybe you just forget to uncheck the "Only show current language".

**Comment by DigitalPig** [comment]
Mine version is fcitx-config-gtk3. I did uncheck "only show current language".
