### ISSUE TITLE
能否支持docker desktop

### ISSUE THREAD

**Issue by macrosun1985** [fcitx/fcitx#238]
# 使用docker构建的桌面eclipse，镜像leesah/eclipse，输入法无法使用
# Docker command

```
    docker run -v -d ~/workspace:/home/eclipse/workspace -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro leesah/eclipse
```
# System Info:
1.  `uname -a`:
   
   ```
   Linux pc01-sunh-dev 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
   ```
2.  `lsb_release -a`:
   
   ```
   No LSB modules are available.
   Distributor ID: LinuxMint
   Description:    Linux Mint 17.3 Rosa
   Release:    17.3
   Codename:   rosa
   ```
3.  `lsb_release -d`:
   
   ```
   Description:    Linux Mint 17.3 Rosa
   ```
4.  `/etc/lsb-release`:
   
   ```
   DISTRIB_ID=LinuxMint
   DISTRIB_RELEASE=17.3
   DISTRIB_CODENAME=rosa
   DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
   ```
5.  `/etc/os-release`:
   
   ```
   NAME="Ubuntu"
   VERSION="14.04.3 LTS, Trusty Tahr"
   ID=ubuntu
   ID_LIKE=debian
   PRETTY_NAME="Ubuntu 14.04.3 LTS"
   VERSION_ID="14.04"
   HOME_URL="http://www.ubuntu.com/"
   SUPPORT_URL="http://help.ubuntu.com/"
   BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
   ```
6.  Desktop Environment:
   
   Desktop environment is `mate`.
# Environment:
1.  DISPLAY:
   
   ```
   DISPLAY=':0.0'
   ```
2.  Keyboard Layout:
   1.  `setxkbmap`:
      
      ```
      xkb_keymap {
          xkb_keycodes  { include "evdev+aliases(qwerty)" };
          xkb_types     { include "complete"  };
          xkb_compat    { include "complete"  };
          xkb_symbols   { include "pc+us+inet(evdev)+terminate(ctrl_alt_bksp)"    };
          xkb_geometry  { include "pc(pc105)" };
      };
      ```
   2.  `xprop`:
      
      ```
      _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", "terminate:ctrl_alt_bksp"
      ```
3.  Locale:
   1.  All locale:
      
      ```
      C
      C.UTF-8
      en_AG
      en_AG.utf8
      en_AU.utf8
      en_BW.utf8
      en_CA.utf8
      en_DK.utf8
      en_GB.utf8
      en_HK.utf8
      en_IE.utf8
      en_IN
      en_IN.utf8
      en_NG
      en_NG.utf8
      en_NZ.utf8
      en_PH.utf8
      en_SG.utf8
      en_US.utf8
      en_ZA.utf8
      en_ZM
      en_ZM.utf8
      en_ZW.utf8
      POSIX
      zh_CN.utf8
      ```
   2.  Current locale:
      
      ```
      LANG=en_US.UTF-8
      LANGUAGE=
      LC_CTYPE="en_US.UTF-8"
      LC_NUMERIC=zh_CN.UTF-8
      LC_TIME="en_US.UTF-8"
      LC_COLLATE="en_US.UTF-8"
      LC_MONETARY=zh_CN.UTF-8
      LC_MESSAGES="en_US.UTF-8"
      LC_PAPER=zh_CN.UTF-8
      LC_NAME=zh_CN.UTF-8
      LC_ADDRESS=zh_CN.UTF-8
      LC_TELEPHONE=zh_CN.UTF-8
      LC_MEASUREMENT=zh_CN.UTF-8
      LC_IDENTIFICATION=zh_CN.UTF-8
      LC_ALL=
      ```
4.  Current user:
   
   The script is run as macrosun (1000).
# Fcitx State:
1.  executable:
   
   Found fcitx at `/usr/bin/fcitx`.
2.  version:
   
   Fcitx version: `4.2.8.3`
3.  process:
   
   Found 3 fcitx processes:
   
   ```
    5018 fcitx
    5022 fcitx-qimpanel
    5032 fcitx-dbus-watc
   ```
4.  `fcitx-remote`:
   
   `fcitx-remote` works properly.
# Fcitx Configure UI:
1.  Config Tool Wrapper:
   
   Found fcitx-configtool at `/usr/bin/fcitx-configtool`.
2.  Config GUI for gtk2:
   
   **Config GUI for gtk2 not found.**
3.  Config GUI for gtk3:
   
   Found `fcitx-config-gtk3` at `/usr/bin/fcitx-config-gtk3`.
4.  Config GUI for kde:
   
   **`kcmshell4` not found.**
# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:
   
   Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
   Xim Server Name from Environment variable is fcitx.
2.  XIM_SERVERS on root window:
   
   Xim server name is the same with that set in the environment variable.
## Qt:
1.  `${QT_IM_MODULE}`:
   
   **Environment variable QT_IM_MODULE is "xim" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
   **You are using xim in qt programs.**
   
   **To see some application specific problems you may have when using xim, check [Hall of Shame for Linux IME Support](http://fcitx-im.org/wiki/Hall_of_Shame_for_Linux_IME_Support). For other more general problems of using XIM including application freezing, see [here](http://fcitx-im.org/wiki/XIM).**
   
   **Please set environment variable QT_IM_MODULE to "fcitx" using the tool your distribution provides or add `export QT_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: QT_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#QT_IM_MODULE).**
2.  Qt IM module files:
   Found fcitx im module for Qt4: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.
   Found fcitx qt module: `/usr/lib/x86_64-linux-gnu/fcitx/qt/libfcitx-quickphrase-editor.so`.
   Found fcitx im module for Qt5: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
## Gtk:
1.  `${GTK_IM_MODULE}`:
   
   **Environment variable GTK_IM_MODULE is "xim" instead of "fcitx". Please check if you have exported it incorrectly in any of your init files.**
   **You are using xim in gtk programs.**
   
   **To see some application specific problems you may have when using xim, check [Hall of Shame for Linux IME Support](http://fcitx-im.org/wiki/Hall_of_Shame_for_Linux_IME_Support). For other more general problems of using XIM including application freezing, see [here](http://fcitx-im.org/wiki/XIM).**
   
   **Please set environment variable GTK_IM_MODULE to "fcitx" using the tool your distribution provides or add `export GTK_IM_MODULE=fcitx` to your `~/.xprofile`. See [Input Method Related Environment Variables: GTK_IM_MODULE](http://fcitx-im.org/wiki/Input_method_related_environment_variables#GTK_IM_MODULE).**
2.  `gtk-query-immodules`:
   1.  gtk 2:
      
      **Cannot find `gtk-query-immodules` for gtk 2**
      
      **Cannot find fcitx im module for gtk 2.**
   2.  gtk 3:
      
      **Cannot find `gtk-query-immodules` for gtk 3**
      
      **Cannot find fcitx im module for gtk 3.**
3.  Gtk IM module cache:
   1.  gtk 2:
      
      Found immodules cache for gtk `2.24.23` at `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
      Version Line:
      
      ```
      # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.23
      ```
      
      Found fcitx im modules for gtk `2.24.23`.
      
      ```
      "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
      
      Found immodules cache for gtk `2.24.23` at `/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
      Version Line:
      
      ```
      # Created by /usr/lib/i386-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.23
      ```
      
      **Failed to find fcitx in immodule cache at `/usr/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**
   2.  gtk 3:
      
      Found immodules cache for gtk `3.10.8` at `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
      Version Line:
      
      ```
      # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.10.8
      ```
      
      Found fcitx im modules for gtk `3.10.8`.
      
      ```
      "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
4.  Gtk IM module files:
   1.  gtk 2:
      
      All found Gtk 2 immodule files exist.
   2.  gtk 3:
      
      All found Gtk 3 immodule files exist.
# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:
   
   Found fcitx addon config directory: `/usr/share/fcitx/addon`.
2.  Addon List:
   1.  Found 38 enabled addons:
      
      ```
      fcitx-anthy
      fcitx-autoeng
      fcitx-chewing
      fcitx-chttrans
      fcitx-classic-ui
      fcitx-clipboard
      fcitx-cloudpinyin
      fcitx-dbus
      fcitx-freedesktop-notify
      fcitx-fullwidth-char
      fcitx-googlepinyin
      fcitx-hangul
      fcitx-imselector
      fcitx-ipc
      fcitx-keyboard
      fcitx-kimpanel-ui
      fcitx-libpinyin
      fcitx-lua
      fcitx-m17n
      fcitx-mozc
      fcitx-notificationitem
      fcitx-pinyin
      fcitx-pinyin-enhance
      fcitx-punc
      fcitx-quickphrase
      fcitx-remote
      fcitx-rime
      fcitx-sayura
      fcitx-spell
      fcitx-sunpinyin
      fcitx-table
      fcitx-unicode
      fcitx-unikey
      fcitx-vk
      fcitx-x11
      fcitx-xim
      fcitx-xkb
      fcitx-xkbdbus
      ```
   2.  Found 2 disabled addons:
      
      ```
      fcitx-light-ui
      fcitx-qw
      ```
3.  Addon Libraries:
   
   All libraries for all addons are found.
4.  User Interface:
   
   Found 2 enabled user interface addons:
   
   ```
   fcitx-classic-ui
   fcitx-kimpanel-ui
   ```
   
   Kimpanel process:
   
   ```
    5022 [fcitx-qimpanel]
   ```
## Input Methods:
1.  Found 2 enabled input methods:
   
   ```
   googlepinyin
   fcitx-keyboard-us
   ```
2.  Default input methods:
   
   **Your first (default) input method is googlepinyin instead of a keyboard input method. You may have trouble deactivate fcitx.**
# Log:
1.  `date`:
   
   ```
   Fri Dec 25 20:56:21 CST 2015
   ```
2.  `~/.config/fcitx/log/`:
   
   ```
   total 0
   -rw-r--r-- 1 macrosun macrosun 0 Dec 25 20:54 crash.log
   ```
3.  `~/.config/fcitx/log/crash.log`:

**Comment by WaferJay** [comment]
在容器中设置 `XMODIFIERS`，`QT_IM_MODULE` 和 `GTK_IM_MODULE` 三个环境变量应该就可以正常使用 `fcitx`。

```bash
docker run -v -d 
    -e DISPLAY
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro
    -e XMODIFIERS=@im=fcitx
    -e QT_IM_MODULE=fcitx
    -e GTK_IM_MODULE=fcitx
    leesah/eclipse
```

如果宿主的环境变量配置没问题，可以直接将宿主的环境变量设置到 `Docker` 容器。

```bash
docker run -v -d 
    -e DISPLAY
    -v /tmp/.X11-unix:/tmp/.X11-unix:ro
    -e XMODIFIERS
    -e QT_IM_MODULE
    -e GTK_IM_MODULE
    leesah/eclipse
```

**Comment by wengxt** [comment]
基本上来说，这是配置的问题，如果只是想用容器跑一些程序，推荐用 flatpak，它里面已经自带了输入法支持。

在其他容器中跑 X11，程序的话那就得考虑怎么让输入法和程序通信的问题
1、如果使用 xim（只要有 X 就可以用），那容器环境变量就要对应设置成 xim
2、如果要使用 im module 首先得 dbus 共享路径，其次还需要容器内安装了对应的 fcitx 的 im module，这也是推荐 flatpak 的原因：flatpak 的 runtime 已经内置了 fcitx 的。

**Comment by leimao** [comment]
> 在容器中设置 `XMODIFIERS`，`QT_IM_MODULE` 和 `GTK_IM_MODULE` 三个环境变量应该就可以正常使用 `fcitx`。
> 
> ```shell
> docker run -v -d \
>     -e DISPLAY \
>     -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
>     -e XMODIFIERS=@im=fcitx \
>     -e QT_IM_MODULE=fcitx \
>     -e GTK_IM_MODULE=fcitx \
>     leesah/eclipse
> ```
> 
> 如果宿主的环境变量配置没问题，可以直接将宿主的环境变量设置到 `Docker` 容器。
> 
> ```shell
> docker run -v -d \
>     -e DISPLAY \
>     -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
>     -e XMODIFIERS \
>     -e QT_IM_MODULE \
>     -e GTK_IM_MODULE \
>     leesah/eclipse
> ```
> 
> 另外，容器可能需要做好本地化。以及为了正常显示中文，还需设置好字体。
> 
> ```shell
> docker run -v -d \
>     -e DISPLAY \
>     -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
>     -e XMODIFIERS \
>     -e QT_IM_MODULE \
>     -e GTK_IM_MODULE \
>     -v /usr/share/fonts:/usr/share/fonts:ro \
>     -v /usr/lib/locale:/usr/lib/locale:ro \
>     -e LANG \
>     -e LC_ALL \
>     leesah/eclipse
> ```
> 
> 可以参考下这篇文章： [Docker容器的本地化](https://blog.wanfajie.com/2021/01/493)

根据我以往经验，如果Docker container里运行的是使用Wine的GUI程序，是可以使用fcitx输入法从host端输入中文的。
但是如果Docker container里运行的原生的Linux的GUI程序，比如说Firefox，fcitx输入法则完全无效。

不晓得有没有比较好的方法能够兼容原生Linux的GUI程序。

**Comment by leimao** [comment]
@WaferJay 《Docker容器的本地化》这篇文章中的demo似乎使用的就是Wine的Notepad程序。

**Comment by WaferJay** [comment]
你好 @leimao ，我试了一遍文章中写的使用 Wine 容器运行 notepad，发现不设置前面提到的几个环境变量是无法切换出输入法的。

我比较好奇你用 Docker 的 Wine 镜像运行了哪个程序，以及使用怎样的命令行参数可以切出输入法的。会不会是你使用的镜像已经在内部设置了这几个环境变量，或是你使用 docker-composer 配置文件中设置了而未注意到？

另外，我认为原生 Firefox 程序在容器中运行也是同样的原理，上面关于 Docker 运行 eclipse 的回答当时也是做过一遍确认了切换输入法和输入中文的问题。

虽然 eclipse 是运行在 JVM 上的、notepad 是运行在 Wine 兼容层上的、Firefox 直接运行在 Linux 上，但底层总归是使用 Linux 一套统一的图形接口。给 Firefox 设置好 `XMODIFIERS` 等环境变量应该也可以使用输入法。

你使用的 Firefox 镜像可以的话希望发我一份，我对此还是比较感兴趣的。

**Comment by leimao** [comment]
> 你好 @leimao ，我试了一遍文章中写的使用 Wine 容器运行 notepad，发现不设置前面提到的几个环境变量是无法切换出输入法的。
> 
> 我比较好奇你用 Docker 的 Wine 镜像运行了哪个程序，以及使用怎样的命令行参数可以切出输入法的。会不会是你使用的镜像已经在内部设置了这几个环境变量，或是你使用 docker-composer 配置文件中设置了而未注意到？
> 
> 另外，我认为原生 Firefox 程序在容器中运行也是同样的原理，上面关于 Docker 运行 eclipse 的回答当时也是做过一遍确认了切换输入法和输入中文的问题。
> 
> 虽然 eclipse 是运行在 JVM 上的、notepad 是运行在 Wine 兼容层上的、Firefox 直接运行在 Linux 上，但底层总归是使用 Linux 一套统一的图形接口。给 Firefox 设置好 `XMODIFIERS` 等环境变量应该也可以使用输入法。
> 
> 你使用的 Firefox 镜像可以的话希望发我一份，我对此还是比较感兴趣的。

你好， @WaferJay 。Docker里面如果运行的是Wine的程序，则可以通过设置
```
    -e XMODIFIERS=@im=fcitx \
    -e QT_IM_MODULE=fcitx \
    -e GTK_IM_MODULE=fcitx \
```
来进行输入法调度，这个是没有问题的。

如果是原生Linux程序，比如说这个简单的[Firefox的Docker镜像](https://leimao.github.io/blog/Docker-Container-GUI-Display/#Firefox)。即便是设置了上面几个环境变量，也无法切换fcitx输入法。您有兴趣的话可以玩一玩，因为这个镜像比较简单。

**Comment by leimao** [comment]
@WaferJay 另外关于Linux图形接口，这个我不是很熟悉。但是即便是Ubuntu的host系统，fcitx也不是可以在任意窗口切换并输入文字的。Steam就是最好的一个例子。

**Comment by WaferJay** [comment]
@leimao ，我或许知道为什么你切不出输入法了，这应该是和本地化有关。当挂载好字符集文件，输入法是可以正常切换出来的，缺少则切不出来。目前我也不了解具体原理。

这是我构建镜像时使用的 Dockerfile：

```dockerfile
FROM ubuntu:latest

ADD firefox/ /firefox
WORKDIR /firefox
RUN apt-get update && apt-get install -y libgtk-3-0 libdbus-glib-1-2 libx11-xcb1
CMD ["/firefox/firefox-bin"]
```

需要下载 [Firefox 96.0](https://download-ssl.firefox.com.cn/releases/firefox/96.0/zh-CN/Firefox-latest-x86_64.tar.bz2)，解压出的 `firefox` 文件夹与上面的 `Dockerfile` 放在同一目录进行构建。

![part](https://user-images.githubusercontent.com/17383312/149791766-11ea561a-0404-4465-a079-48543bd61e35.png)

就我的了解，在 Docker 容器中使用 fcitx 输入法的条件总结一下就是：

1. 在容器中成功启动 GUI 程序。
2. 设置好 `XMODIFIERS`、 `QT_IM_MODULE`、`GTK_IM_MODULE` 环境变量。
3. 设置好 `/usr/lib/locale` 下的字符集文件，以及 `LANG`、`LC_*` 等环境变量。

这和我在 https://github.com/fcitx/fcitx/issues/238#issuecomment-778591469 中提到的文章内容上是一致的。

至于 steam，我还是更倾向于系统环境配置有问题。

**Comment by leimao** [comment]
@WaferJay 您好。我尝试着build了你的Docker image和用了下面的命令重复你的启动。还是无法复现你的结果。
```
$ docker run -it --rm -v $XAUTHORITY:/root/.Xauthority:ro -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v /usr/lib/locale:/usr/lib/locale:ro -e LANG -v /usr/share/fonts:/usr/share/fonts:ro -e XMODIFIERS=@im=fcitx -e QT_IM_MODULE=fcitx -e GTK_IM_MODULE=fcitx firefox:0.0.1
```
![reproduction](https://user-images.githubusercontent.com/17606112/149819162-0de4ef99-efc7-4012-be11-77561eb4811f.png)

那这么看起来，要么是我的输入法有问题，要么就是locale下面的字符集的问题。

我用的是fcitx的[Google-Pinyin](https://leimao.github.io/blog/Ubuntu-Gaming-Chinese-Input/)，不晓得你用的是什么输入法。

这个是我的本地的locale的文件
```
$ ls /usr/lib/locale/
C.UTF-8  locale-archive
```
是不是少了中文的locale？

**Comment by WaferJay** [comment]
客气了 @leimao ，我想应该不是字符集文件的问题，因为你的 host 系统可以正常使用中文。从容器中的 Firefox 输出的内容看，也没有报字符集文件格式错误之类的问题。

虽然我不是很确定具体的原因，但我觉得可以从以下几个方面排查问题：

1. 检查容器 `LANG` 环境变量。你的 host 可能并没有本地化设置成中文，中文一般是 `zh_CN.UTF8` / `zh_CN.GB2312` 等，要具体看 `locale-archive` 中打包了哪些中文字符集。
2. 比对容器和 host 的 `XMODIFIERS`、 `QT_IM_MODULE`、`GTK_IM_MODULE` 环境变量是否和你 host 一致。
3. 不使用 host 的 `/usr/lib/locale`，而是在容器中生成 `locale-archive`。对于 Ubuntu 镜像，没记错的话有个 `locales-all` 包可以装好所有字符集文件。

希望能对你有所帮助。

**Comment by wengxt** [comment]
@leimao https://fcitx-im.org/wiki/FAQ#Is_it_Java.2C_Xterm.2C_wine.2C_or_some_other_non-Gtk.2FQt_Application.3F

如果要用 XIM 的话，你的问题参见

**Comment by mooction** [comment]
我也遇到了无法在Docker内使用 fcitx 的问题，不过我的宿主机是 fcitx5。

```yaml
version: '3.7'
services:
  gedit:
    build:
      context: .
    image: gedit:latest
    tty: true
    ipc: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/lib/locale:/usr/lib/locale:ro
      - /usr/share/X11/locale/:/usr/share/X11/locale/:ro
      - /usr/share/fonts:/usr/share/fonts:ro
    environment:
      - QT_DEBUG_PLUGINS=1
      - QT_QPA_PLATFORM=xcb
      - QT_IM_MODULE=fcitx
      - XMODIFIERS=@im=fcitx
      - GTK_IM_MODULE=fcitx
      - DISPLAY=unix${DISPLAY}
      - GDK_SCALE
      - GDK_DPI_SCALE
      - LANG
      - LC_ALL
```

```Dockerfile
FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  --no-install-recommends procps xserver-xorg xinit libxinerama1 xdg-utils \
  libnss3 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libasound2 gedit \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

CMD /usr/bin/gedit
```

```bash
xhost +si:localuser:root
docker-compose up
```

**Comment by crazyn2** [comment]
> 客气了 @leimao ，我想应该不是字符集文件的问题，因为你的 host 系统可以正常使用中文。从容器中的 Firefox 输出的内容看，也没有报字符集文件格式错误之类的问题。
> 
> 虽然我不是很确定具体的原因，但我觉得可以从以下几个方面排查问题：
> 
>     1. 检查容器 `LANG` 环境变量。你的 host 可能并没有本地化设置成中文，中文一般是 `zh_CN.UTF8` / `zh_CN.GB2312` 等，要具体看 `locale-archive` 中打包了哪些中文字符集。
> 
>     2. 比对容器和 host 的 `XMODIFIERS`、 `QT_IM_MODULE`、`GTK_IM_MODULE` 环境变量是否和你 host 一致。
> 
>     3. 不使用 host 的 `/usr/lib/locale`，而是在容器中生成 `locale-archive`。对于 Ubuntu 镜像，没记错的话有个 `locales-all` 包可以装好所有字符集文件。
> 
> 
> 希望能对你有所帮助。

请问下你有在ubuntu22.04上试过吗
