### ISSUE TITLE
当在GNOME中HiDPI模式下使用Chrome/Chromium输入框错位.

### ISSUE THREAD

**Issue by FireZ-ZLF** [fcitx/fcitx#240]
当在GNOME中HiDPI模式下使用Chrome/Chromium输入框错位.

环境
GNOME 3.18
GTK2 2.24.29
GTK3  3.18.6
Chromium 48.0.2564.82 (64-bit)

![截图](https://cloud.githubusercontent.com/assets/7223991/12551890/d4707844-c3a8-11e5-9344-df2c161205bd.png)

PS:其他的GUI程序正常

**Comment by wengxt** [comment]
https://code.google.com/p/chromium/issues/detail?id=475718

**Comment by heavytail** [comment]
@wengxt 
Compiling chromium with "use_gtk3=1" resolves this issue.
