### ISSUE TITLE
fcitx creates blank (zero-size?) xembed icon on KDE

### ISSUE THREAD

**Issue by cuihaoleo** [fcitx/fcitx#241]
Steps to reproduce:
1. kill plasmashell (sometimes I can reproduce without this) and fcitx
2. start xembedsniproxy
3. run fcitx (you will get some error outputs from xembedsniproxy)
4. run plasmashell

Results:
blank and unresponsive xembed icon shows in Plasma tray. fcitx's SNI tray icon works well.
Then if you kill fcitx, the icon is still there (maybe this part is an issue of xembedsniproxy). Only after xembedsniproxy killed and restarted, the icon would disappear.

I blame fcitx for this bug because of following evidences:
1. If you replace xembedsniproxy with another xembed sysicon app (like stalonetray) when blank icon is there, you will get a good and functional xembed tray icon (together with SNI tray icon showing in Plasma panel, they both work!).
2. If you start stalonetray instead of xembedsniproxy before plasmashell is running and run fcitx, stalonetray also output some errors (though it doesn't show an blank icon).

[Here](https://bugs.kde.org/show_bug.cgi?id=358719) is a (maybe) relative bug report in KDE's bug tracker.

Platform:
fcitx 4.2.9.1
KDE plasma 5.5.4
Arch Linux x86_64

Attachments:
![screenshot_20160205_102150](https://cloud.githubusercontent.com/assets/889871/12836283/4d24a3f4-cbf2-11e5-8bca-dbcb1b064f67.png) a screenshot
[xembedsniproxy.txt](https://github.com/fcitx/fcitx/files/118551/xembedsniproxy.txt) Terminal outputs of xembedsniproxy (I added a blank line before running fcitx)

**Comment by wengxt** [comment]
Please try master see if it helps. But xembedsniproxy indeed has its own problem though.

**Comment by cuihaoleo** [comment]
Yeah, lt's fixed now.

But I also notice that now tray icon won't show in xembed systray, even when plasmashell is not running. Does the fix break the compatibility of xembed tray?

**Comment by wengxt** [comment]
statusnotifier service is provided by kded5, not plasma.

**Comment by wengxt** [comment]
So fcitx still think there's status notifier service. To play with it you need to kill xembedsniproxy and kded5, then start another tray, and see if start kded5 will make xembed tray disappear.

**Comment by cuihaoleo** [comment]
wow, thanks for explanation.
