### ISSUE TITLE
fcitx dropping keystrokes

### ISSUE THREAD

**Issue by cdown** [fcitx/fcitx#242]
fcitx seems to be dropping keystrokes for me:

```
% uname -a 
Linux laoxiang 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
% fcitx --version
fcitx version: 4.2.9.1
```

You can see the problem here (trying to type "为什么丢按键" with sunpinyin):

![dr](https://cloud.githubusercontent.com/assets/660663/12859417/f28df1b4-cc4d-11e5-8d26-5b3eb1d92817.gif)

Any ideas?

**Comment by happyaron** [comment]
Check your fcitx GTK2 IM Module status.

**Comment by cdown** [comment]
谢了，install GT2以后问题解决 :)
