### ISSUE TITLE
如何修改英文上屏热键(默认是Enter)

### ISSUE THREAD

**Issue by amosbird** [fcitx/fcitx#246]
我想使用`Ctrl-l`作为英文上屏热键, 同时使用`Ctrl-h`作为退格键

**Comment by yuyichao** [comment]
可以试试 https://github.com/yuyichao/fcitx-keytheme

**Comment by amosbird** [comment]
谢谢, 我配置了以下两个热键 ![](http://i.imgur.com/ugV9cCq.png), 退格生效了, 回车没有效果, 直接穿过了`fcitx`
