### ISSUE TITLE
托盘图标的问题（Breeze 主题）

### ISSUE THREAD

**Issue by guoyunhe** [fcitx/fcitx#247]
KDE 5 Breeze 图标主题下，英文键盘图标 48px 的彩色 SVG 而不是 22px 的黑白 SVG。

![spectacle zk6262](https://cloud.githubusercontent.com/assets/5836790/13366296/10789cd8-dce3-11e5-9451-15ecb9151c6a.png)

![input-keyboard](https://cloud.githubusercontent.com/assets/5836790/13366475/0b1810ba-dce4-11e5-8fe4-e3ead82f32a0.png)

![input-keyboard](https://cloud.githubusercontent.com/assets/5836790/13366426/c76b3f18-dce3-11e5-9dc5-4db8f821e10a.png)

不知道是 Fcitx 的问题，还是 Breeze 图标的问题，还是我电脑的问题……

Fcitx 英文键盘用的是图标 fcitx-kbd 还是 input-keyboard?

**Comment by wengxt** [comment]
$ qdbus org.fcitx.Fcitx /StatusNotifierItem org.kde.StatusNotifierItem.IconName
input-keyboard

**Comment by wengxt** [comment]
bug is in plasma-framework.

**Comment by wengxt** [comment]
Fixed in upstream http://commits.kde.org/plasma-framework/066cf0a0d7b46c60fccb945dbc0e9f858c4d6967

**Comment by guoyunhe** [comment]
great.
