### ISSUE TITLE
**无法找到 gtk 2／3 的 fcitx 输入法模块.**

### ISSUE THREAD

**Issue by yellowbean** [fcitx/fcitx#253]
# 系统信息:
1.  `uname -a`:

        Linux xxx 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Debian
        Description:	Debian GNU/Linux 8.3 (jessie)
        Release:	8.3
        Codename:	jessie

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux 8.3 (jessie)

4.  `/etc/lsb-release`:

    `/etc/lsb-release` 未找到.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
        NAME="Debian GNU/Linux"
        VERSION_ID="8"
        VERSION="8 (jessie)"
        ID=debian
        HOME_URL="http://www.debian.org/"
        SUPPORT_URL="http://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  桌面环境:

    无法确定桌面环境。

# 环境:
1.  DISPLAY:

        DISPLAY=':0'

2.  键盘布局:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+inet(evdev)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us", "", ""

3.  Locale:

    1.  全部可用 locale:

            C
            C.UTF-8
            en_US.utf8
            POSIX
            zh_CN
            zh_CN.gb18030
            zh_CN.gb2312
            zh_CN.gbk
            zh_CN.utf8

    2.  当前 locale:

            LANG=zh_CN.UTF-8
            LANGUAGE=
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /root

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/root/.config`)。

    3.  Fcitx 设置目录：

        当前 fcitx 设置目录是 `~/.config/fcitx` (`/root/.config/fcitx`)。

5.  当前用户：

    脚本作为 root (0) 运行。

    1.  `sudo` 环境变量：

        SUDO_COMMAND 没有设定。

        SUDO_USER 没有设定。

        SUDO_UID 没有设定。

        SUDO_GID 没有设定。

    2.  以管理员运行：

        **你可能以 `root` 或者 `sudo` 登录运行此脚本。这意味着两种情况，要么你有安全问题或该脚本的结果可能不准确。有关更多信息，请参见 [以root身份运行不好的原因](https://www.google.com/search?q=以root身份运行不好的原因) 或者 [sudo的环境变量](https://www.google.com/search?q=sudo的环境变量) 。**

# Fcitx 状态:
1.  可执行文件:

    在 `/usr/bin/fcitx` 找到了 fcitx.

2.  版本:

    Fcitx 版本: `4.2.8.5`

3.  进程:

    找到了 2 个 fcitx 进程:

        27450 fcitx
        27467 fcitx-dbus-watc

4.  `fcitx-remote`:

    **无法连接到 fcitx.**

# Fcitx 配置界面:
1.  配置工具封装：

    在 `/usr/bin/fcitx-configtool` 找到了 fcitx-configtool。

2.  用于 GTK+-2.0 的配置界面：

    在 `/usr/bin/fcitx-config-gtk` 找到了 `fcitx-config-gtk`。

3.  用于 GTK+-3.0 的配置界面：

    在 `/usr/bin/fcitx-config-gtk3` 找到了 `fcitx-config-gtk3`。

4.  KDE 的配置界面：

    **`kcmshell4` 未找到.**

# 前端设置:
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了 "@im=fcitx".
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS:

    Xim 服务的名称与环境变量中设置的相同.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".

3.  Qt 输入法模块文件:
    找到了 fcitx 的 qt 模块: `/usr/lib/x86_64-linux-gnu/fcitx/qt/libfcitx-libpinyin-dictmanager.so`.
    找到了 Qt4 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/qtim-fcitx.so`.
    找到了 Qt5 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了 "fcitx".

2.  `gtk-query-immodules`:

    1.  gtk 2:
/usr/bin/fcitx-diagnose:行1236: /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/gtk-query-immodules-2.0: 权限不够

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/gtk-query-immodules-2.0` 找到了未知 gtk 版本的 `gtk-query-immodules`.

        **无法在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/gtk-query-immodules-2.0` 的输出重找到 fcitx.**

        **无法找到 gtk 2 的 `gtk-query-immodules`.**

        **无法找到 gtk 2 的 fcitx 输入法模块.**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`.**

        **无法找到 gtk 3 的 fcitx 输入法模块.**

3.  Gtk 输入法模块缓存:

    1.  gtk 2:

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.25` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.25

        已找到 gtk `2.24.25` 的 fcitx 输入法模块.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/gtk.immodules` 找到了未知 gtk 版本的输入法模块缓存.

        **无法输入法模块缓存 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/gtk.immodules` 中找到 fcitx**

    2.  gtk 3:

        在 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了未知 gtk 版本的输入法模块缓存.

        **无法输入法模块缓存 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 中找到 fcitx**

        **无法找到 gtk 3 的输入法模块缓存**

        **无法在缓存中找到 gtk 3 的 fcitx 输入法模块.**

4.  Gtk 输入法模块文件:

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在.

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在.

# 配置:
## Fcitx 插件:
1.  插件配置文件目录:

    找到了 fcitx 插件配置目录: `/usr/share/fcitx/addon`.

2.  插件列表:

    1.  找到了 29 个已启用的插件:

            fcitx-autoeng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-googlepinyin
            fcitx-imselector
            fcitx-ipc
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-libpinyin
            fcitx-lua
            fcitx-notificationitem
            fcitx-pinyin
            fcitx-pinyin-enhance
            fcitx-punc
            fcitx-quickphrase
            fcitx-remote
            fcitx-spell
            fcitx-sunpinyin
            fcitx-table
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  找到了 1 个被禁用的插件:

            fcitx-light-ui

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面:

    找到了 2 个已启用的用户界面插件:

        fcitx-classic-ui
        fcitx-kimpanel-ui

## 输入法:
1.  找到了 9 个启用的输入法:

        fcitx-keyboard-us
        pinyin
        shuangpin
        wubi
        wbpy
        pinyin-libpinyin
        shuangpin-libpinyin
        zhuyin-libpinyin
        googlepinyin

2.  默认输入法:

    您已经正确的将一个键盘输入法 "fcitx-keyboard-us" 设为默认.

# 日志:
1.  `date`:

        2016年 03月 29日 星期二 00:09:37 HKT

2.  `~/.config/fcitx/log/`:

        总用量 4
        -rw-r--r-- 1 root root 44 3月  21 00:28 crash.log

3.  `~/.config/fcitx/log/crash.log`:

        fcitx: BadWindow (invalid Window parameter)

----
不知道该怎么办，已经3天了。无进展，在i3wm环境下配置，按照https://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-hans
进行
    gtk-query-immodules-2.0 --update-cache
    gtk-query-immodules-3.0 --update-cache

也没有用，求助，谢谢

**Comment by wengxt** [comment]
装 fcitx-frontend-gtk{2,3}
