### ISSUE TITLE
用QT5.5.1编译出来的程序，无法调用fcitx输入法。

### ISSUE THREAD

**Issue by linux0ne** [fcitx/fcitx#254]
1、我在使用一款叫qTox的即时交流软件，https://github.com/tux3/qTox/ , 这是它的主页，不错。

2、但是不论怎么弄我都没法在这个软件里用上fcitx输入法，我试过clone fcitx-qt到本地，然后编译之，得到so文件。可是这样做还是没用。

3、我想知道还有哪个角度是我没有想到的，或者有人愿意试一下这个软件不，不过软体本身，只为fcitx输入法的调用 。  请大家帮忙想想办法。

我的qTox ID：qtox0nhome@utox.org   欢迎大家加我，只是我还用不上中文，呵。

**Comment by yuyichao** [comment]
https://github.com/fcitx/fcitx/issues/227

**Comment by linux0ne** [comment]
@yuyichao 感谢你的指导，我看了那个帖子，他的方法说得不详细，我无法理解“将输入法模块环境变量调整到最前面”这句话具体怎么操作，即使我是ubuntu操作系统。

**Comment by linux0ne** [comment]
@yuyichao 
这里扩展问一个问题，在fcitx wiki中我看到下面一句话，我不理解，如果你懂，可否详细教教我：

“fcitx从4.1开始包含GTK和Qt的原生输入法模块。强烈推荐使用原生的输入法模块来代替XIM，因为这样能避免无法解决的问题”

这里的“代替”该怎么做？？

**Comment by yuyichao** [comment]
https://fcitx-im.org/wiki/Configure_%28Ubuntu%29

**Comment by linux0ne** [comment]
@yuyichao 
1、关于“代替”的部分我学到了，谢谢。

2、关于这个fcitx 在qTox中使用的问题，我还是没有得到解决办法，我在这里贴一下我用fcitx-diagnose得到的结果，结果中显示我已经正确的设置了qt5的输入法为fcitx了呀！！！  疯了。

http://paste.ubuntu.com/15576605/                  请到这里查看结果。

**Comment by yuyichao** [comment]
... 我本来记得 #227 里面提了, qt5 版本不一样的 fcitx-qt5 没法用.

**Comment by linux0ne** [comment]
@yuyichao "qt5 版本不一样的 fcitx-qt5 没法用" —— 这个要怎么理解 ？？  

我现在的qt是5.5.1，我在这个环境下一步步的编译fcitx-qt5后，得到那个.so文件还不可以么？ 

若说我在qt5.4里编译得到的.so文件放到qt5.5编译得到的程序中去用，那肯定不好使！

**Comment by linux0ne** [comment]
@yuyichao 
1、我按 http://my.oschina.net/lieefu/blog/505363?fromerr=wqNFRv1V   这个文章中的办法编译得到了.so文件，并放到指定的位置里面去，但是在运行qtox的时候悲剧了，显示段核心转储错误……    用原来的旧.so文件起码还能看到程序界面，现在啥都看不到了，只在终端里有这么一个提示。
2、编译完xkbc后，发现在qtox的输入框里输入英文时，输入小写字母竟然成了大写（大写锁定没有开），按一下英文的“.”字符，竟然出了">"的情况，日，竟然还带shift功能 ？？？？    这可怎么办呢？？



PS:
上面的那个地址里用到的ECM和XKBC文件在我这里下载的时候都是用得最新的高版本的，编译时正常难过，这个不会有影响吧？
