### ISSUE TITLE
Current language indication in tray for Keyboard input methods

### ISSUE THREAD

**Issue by lambda-terra** [fcitx/fcitx#255]
It's impossible to distinguish current keyboard layout for 'Keyboard' input methods from tray icon.

![screenshot from 2016-04-02 21-32-21](https://cloud.githubusercontent.com/assets/16095702/14227261/ca1819a0-f923-11e5-8a63-195eb7e52f69.png)

**Comment by wengxt** [comment]
I don't know why I disable this feature in the beginning.. probably I didn't have a good idea about what to display at that time. Hopefully this is what you want (You'll see a "ru"/"us" along with the icon in your case).
