### ISSUE TITLE
Uninstall on ubuntu leads to login loop. 

### ISSUE THREAD

**Issue by osev7** [fcitx/fcitx#256]
I don't know if this is the right place to report this, but I was using fcitx on Ubuntu 14.04 from the PPA. I switched back to ibus and uninstalled fcitx. I got stuck on a login loop. After reinstalling fcitx, I can log in fine. 

 Apparently I'm not the only one with this problem:
http://askubuntu.com/questions/705319/cannot-uninstall-fcitx-without-causing-a-login-loop

**Comment by wengxt** [comment]
Please report to launchapd. More like a packaging issue/settings to me.
