### ISSUE TITLE
fcitx-configtool里看不到输入法

### ISSUE THREAD

**Issue by micturkey** [fcitx/fcitx#258]
# 系统信息:
1.  `uname -a`:
   
   ```
   Linux raspberrypi 4.4.7-v7+ #876 SMP Tue Apr 12 22:28:41 BST 2016 armv7l GNU/Linux
   ```
2.  `lsb_release -a`:
   
   ```
   No LSB modules are available.
   Distributor ID: Raspbian
   Description:    Raspbian GNU/Linux 8.0 (jessie)
   Release:    8.0
   Codename:   jessie
   ```
3.  `lsb_release -d`:
   
   ```
   Description:    Raspbian GNU/Linux 8.0 (jessie)
   ```
4.  `/etc/lsb-release`:
   
   `/etc/lsb-release` 未找到.
5.  `/etc/os-release`:
   
   ```
   PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
   NAME="Raspbian GNU/Linux"
   VERSION_ID="8"
   VERSION="8 (jessie)"
   ID=raspbian
   ID_LIKE=debian
   HOME_URL="http://www.raspbian.org/"
   SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
   BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
   ```
6.  桌面环境:
   
   桌面环境为 `lxde`。
# 环境:
1.  DISPLAY:
   
   ```
   DISPLAY=':1.0'
   ```
2.  键盘布局:
   1.  `setxkbmap`:
      
      ```
      XKB extension not present on :1.0
      ```
   2.  `xprop`:
      
      ```
      _XKB_RULES_NAMES:  no such atom on any window.
      ```
3.  Locale:
   1.  全部可用 locale:
      
      ```
      C
      C.UTF-8
      en_GB.utf8
      POSIX
      zh_CN
      zh_CN.gb18030
      zh_CN.gb2312
      zh_CN.gbk
      zh_CN.utf8
      ```
   2.  当前 locale:
      
      ```
      LANG=zh_CN.UTF-8
      LANGUAGE=
      LC_CTYPE="zh_CN.UTF-8"
      LC_NUMERIC="zh_CN.UTF-8"
      LC_TIME="zh_CN.UTF-8"
      LC_COLLATE="zh_CN.UTF-8"
      LC_MONETARY="zh_CN.UTF-8"
      LC_MESSAGES="zh_CN.UTF-8"
      LC_PAPER="zh_CN.UTF-8"
      LC_NAME="zh_CN.UTF-8"
      LC_ADDRESS="zh_CN.UTF-8"
      LC_TELEPHONE="zh_CN.UTF-8"
      LC_MEASUREMENT="zh_CN.UTF-8"
      LC_IDENTIFICATION="zh_CN.UTF-8"
      LC_ALL=
      ```
4.  目录：
   1.  主目录：
      
      ```
      /home/pi
      ```
   2.  `${XDG_CONFIG_HOME}`:
      
      环境变量 `XDG_CONFIG_HOME` 是设定为 `/home/pi/.config` 。
      
      `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/pi/.config`)。
   3.  Fcitx 设置目录：
      
      当前 fcitx 设置目录是 `~/.config/fcitx` (`/home/pi/.config/fcitx`)。
5.  当前用户：
   
   脚本作为 pi (1000) 运行。
# Fcitx 状态:
1.  可执行文件:
   
   在 `/usr/bin/fcitx` 找到了 fcitx.
2.  版本:
   
   Fcitx 版本: `4.2.8.5`
3.  进程:
   
   找到了 3 个 fcitx 进程:
   
   ```
     887 fcitx <defunct>
     900 fcitx
     925 fcitx-dbus-watc
   ```
4.  `fcitx-remote`:
   
   **无法连接到 fcitx.**
# Fcitx 配置界面:
1.  配置工具封装：
   
   在 `/usr/bin/fcitx-configtool` 找到了 fcitx-configtool。
2.  用于 GTK+-2.0 的配置界面：
   
   **未找到 gtk2 的配置界面.**
3.  用于 GTK+-3.0 的配置界面：
   
   在 `/usr/bin/fcitx-config-gtk3` 找到了 `fcitx-config-gtk3`。
4.  KDE 的配置界面：
   
   **`kcmshell4` 未找到.**
# 前端设置:
## Xim:
1.  `${XMODIFIERS}`:
   
   环境变量 XMODIFIERS 已经正确地设为了 "@im=fcitx".
   从环境变量中获取的 Xim 服务名称为 fcitx.
2.  根窗口上的 XIM_SERVERS:
   
   Xim 服务的名称与环境变量中设置的相同.
## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:
   
   环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".
2.  qt5 - `${QT_IM_MODULE}`:
   
   环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".
3.  Qt 输入法模块文件:
   找到了 Qt5 的输入法模块: `/usr/lib/arm-linux-gnueabihf/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
   找到了 Qt4 的输入法模块: `/usr/lib/arm-linux-gnueabihf/qt4/plugins/inputmethods/qtim-fcitx.so`.
## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:
   
   环境变量 GTK_IM_MODULE 已经正确地设为了 "fcitx".
2.  `gtk-query-immodules`:
   1.  gtk 2:
      
      **无法找到 gtk 2 的 `gtk-query-immodules`.**
      
      **无法找到 gtk 2 的 fcitx 输入法模块.**
   2.  gtk 3:
      
      **无法找到 gtk 3 的 `gtk-query-immodules`.**
      
      **无法找到 gtk 3 的 fcitx 输入法模块.**
3.  Gtk 输入法模块缓存:
   1.  gtk 2:
      
      在 `/usr/lib/arm-linux-gnueabihf/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.25` 的输入法模块缓存.
      版本行:
      
      ```
      # Created by /usr/lib/arm-linux-gnueabihf/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.25
      ```
      
      已找到 gtk `2.24.25` 的 fcitx 输入法模块.
      
      ```
      "/usr/lib/arm-linux-gnueabihf/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
   2.  gtk 3:
      
      在 `/usr/lib/arm-linux-gnueabihf/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.14.5` 的输入法模块缓存.
      版本行:
      
      ```
      # Created by /usr/lib/arm-linux-gnueabihf/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.14.5
      ```
      
      已找到 gtk `3.14.5` 的 fcitx 输入法模块.
      
      ```
      "/usr/lib/arm-linux-gnueabihf/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
      "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 
      ```
4.  Gtk 输入法模块文件:
   1.  gtk 2:
      
      找到的全部 Gtk 2 输入法模块文件均存在.
   2.  gtk 3:
      
      找到的全部 Gtk 3 输入法模块文件均存在.
# 配置:
## Fcitx 插件:
1.  插件配置文件目录:
   
   找到了 fcitx 插件配置目录: `/usr/share/fcitx/addon`.
2.  插件列表:
   1.  找到了 29 个已启用的插件:
      
      ```
      fcitx-autoeng
      fcitx-chttrans
      fcitx-classic-ui
      fcitx-clipboard
      fcitx-cloudpinyin
      fcitx-dbus
      fcitx-freedesktop-notify
      fcitx-fullwidth-char
      fcitx-googlepinyin
      fcitx-imselector
      fcitx-ipc
      fcitx-keyboard
      fcitx-kimpanel-ui
      fcitx-lua
      fcitx-notificationitem
      fcitx-pinyin
      fcitx-pinyin-enhance
      fcitx-punc
      fcitx-quickphrase
      fcitx-remote
      fcitx-spell
      fcitx-sunpinyin
      fcitx-table
      fcitx-unicode
      fcitx-vk
      fcitx-x11
      fcitx-xim
      fcitx-xkb
      fcitx-xkbdbus
      ```
   2.  找到了 1 个被禁用的插件:
      
      ```
      fcitx-light-ui
      ```
3.  插件库: 
   
   所有插件所需的库都被找到。
4.  用户界面:
   
   找到了 2 个已启用的用户界面插件:
   
   ```
   fcitx-classic-ui
   fcitx-kimpanel-ui
   ```
## 输入法:
1.  找到了 5 个启用的输入法:
   
   ```
   fcitx-keyboard-us
   sunpinyin
   googlepinyin
   pinyin
   shuangpin
   ```
2.  默认输入法:
   
   您已经正确的将一个键盘输入法 "fcitx-keyboard-us" 设为默认.
# 日志:
1.  `date`:
   
   ```
   2016年 04月 15日 星期五 11:31:27 CST
   ```
2.  `~/.config/fcitx/log/`:
   
   ```
   总用量 4
   -rw-r--r-- 1 pi pi 63 4月  15 11:30 crash.log
   ```
3.  `~/.config/fcitx/log/crash.log`:
   
   ```
   fcitx: BadValue (integer parameter out of range for operation)
   ```

![qq20160415-0](https://cloud.githubusercontent.com/assets/1297392/14551794/1bb39ba0-030a-11e6-9521-ac164e1e60ef.png)

**Comment by zhaidoudou123** [comment]
看不到输入法而且ctrl+space也没有作用
另外,我是vnc连上去的,~/.vnc/xstartup里也加了环境变量了
会不会是因为用了vnc的原因?

**Comment by wengxt** [comment]
需要通过 fcitx 的 dbus 配置实际的输入法，在 xstartup 里面开头加上 

eval `dbus-launch --sh-syntax`

试试看。

**Comment by zhaidoudou123** [comment]
@wengxt 是加在#!/bin/sh下方第一行吗?
如果是的,我试了一下,还是不行

**Comment by wengxt** [comment]
有 dbus-daemon 在运行吗

**Comment by zhaidoudou123** [comment]
@wengxt ps -ef|grep dbus结果如下

> message+   420     1  0 00:08 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
> pi         674     1  0 00:09 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
> pi         895   681  0 00:09 ?        00:00:00 /usr/bin/ssh-agent /usr/bin/dbus-launch --exit-with-session /usr/bin/im-launch x-session-manager
> pi         899     1  0 00:09 ?        00:00:00 /usr/bin/dbus-launch --exit-with-session /usr/bin/im-launch x-session-manager
> pi         902     1  0 00:09 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
> pi         950   878  0 00:09 ?        00:00:00 /usr/bin/ssh-agent /usr/bin/dbus-launch --exit-with-session /usr/bin/im-launch x-session-manager
> pi         953     1  0 00:09 ?        00:00:00 /usr/bin/dbus-launch --exit-with-session /usr/bin/im-launch x-session-manager
> pi         954     1  0 00:09 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
> pi        1003     1  0 00:09 ?        00:00:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --config-file /usr/share/fcitx/dbus/daemon.conf
> pi        1007     1  0 00:09 ?        00:00:00 /usr/bin/fcitx-dbus-watcher unix:abstract=/tmp/dbus-tgYHU82C5M,guid=caa7f09e4db0883a2664e07e57110d84 1003
> pi        1263  1237  0 00:11 pts/0    00:00:00 grep --color=auto dbus
>

**Comment by kinglionsz** [comment]
这个问题经常会遇到。

我发现你已经启用了
fcitx-classic-ui
fcitx-kimpanel-ui

但是fcitx-configtool里看不到输入法。

我是这样解决问题的：

重新下载安装上述库的包：

https://packages.debian.org/zh-cn/sid/amd64/fcitx-ui-classic/download
https://packages.debian.org/zh-cn/buster/amd64/fcitx-module-kimpanel/download

sudo dpkg -i fcitx-ui-classic_4.2.9.9-1_amd64.deb
sudo dpkg -i fcitx-module-kimpanel_4.2.9.6-5+deb10u1_amd64.deb
如果提示安装版本被降低了， 再次升级 sudo aptitude install fcitx-module-kimpanel

最后看一下，OK。
fcitx-configtool

enjoy it

**Comment by micturkey** [comment]
> @[micturkey](https://github.com/micturkey) @[wengxt](https://github.com/wengxt) 这个问题经常会遇到。
> 
> 我发现你已经启用了 fcitx-classic-ui fcitx-kimpanel-ui
> 
> 但是fcitx-configtool里看不到输入法。
> 
> 我是这样解决问题的：
> 
> 重新下载安装上述库的包：
> 
> https://packages.debian.org/zh-cn/sid/amd64/fcitx-ui-classic/download https://packages.debian.org/zh-cn/buster/amd64/fcitx-module-kimpanel/download
> 
> sudo dpkg -i fcitx-ui-classic_4.2.9.9-1_amd64.deb sudo dpkg -i fcitx-module-kimpanel_4.2.9.6-5+deb10u1_amd64.deb 如果提示安装版本被降低了， 再次升级 sudo aptitude install fcitx-module-kimpanel
> 
> 最后看一下，OK。 fcitx-configtool
> 
> enjoy it
> <img alt="fcitx-configtool里看不到输入法" width="960" src="https://user-images.githubusercontent.com/51827261/284459223-eb7076a7-3285-4b27-b202-23000dbb0365.png">

谢谢！这是好多年以前的问题，当时我发现是只要vnc连上去就看不到输入法，直接插线从显示器看就没问题。
不过环境已经没了好久了，这个issue我应该把它关掉😂
