### ISSUE TITLE
fcitx 特殊键盘布局下的bug

### ISSUE THREAD

**Issue by scinart** [fcitx/fcitx#261]
Ubuntu 16.04 fcitx 4.2.9.1 （全新安装）

当我的系统键盘选择dvorak，而拼音键盘却选择qwerty布局时，当激活fcitx拼音输入法后，使用的布局却仍然是dvorak布局。这时如果点系统右上角的图标一次，则拼音输入法变成正常的qwerty布局，但是只要按ctrl+space切换到英文，再切换成拼音，拼音键盘的布局又变成了dvorak布局。

简而言之，输入法设置中的configure->[Input Method]->keyboard layout这个选项，基本已经失效了。

之前使用的 fcitx 4.2.8.3  没有这个问题

**Comment by happyaron** [comment]
贴一下 fcitx-diagnose 的输出？

**Comment by scinart** [comment]
http://paste.ubuntu.com/16127979/

这里不得不提到我改变过``/usr/share/X11/xkb/symbols/us``和``/usr/share/X11/xkb/rules/evdev.xml``，添加了名字叫``sci``的键盘布局，但我相信这种情况与我是否自定义键盘布局没有关系。

**Comment by scinart** [comment]
``4.2.8.4`` works fine. However this problem appears in ``4.2.8.5``

**Comment by scinart** [comment]
各位开发大哥，谁来看一下这个bug啊。。。``T_T``

**Comment by scinart** [comment]
@happyaron 能复现这个bug么。。？

**Comment by wengxt** [comment]
´_>` 前一段时间在另一个 report 研究之后，这个不是 fcitx 的 bug，是 unity-settings-daemon 也要一起来设置键盘布局的问题。

See: https://github.com/fcitx/fcitx-hangul/issues/4

那个是随机出现的，你说的那个 commit 不可能和这个有关系。 git 里面的代码加了一些 workaround ……不过应该你还是直接执行一下

 gsettings set org.gnome.settings-daemon.plugins.keyboard active false 

最方便。

**Comment by wengxt** [comment]
哦，如果非要说有关系的话……就是因为 ubuntu 的那个集成 fcitx 的代码使用了这个 api 如果你 revert 了相当于就是把它搞坏导致加载不了了…和上面的命令意外起到了同一个效果。

**Comment by scinart** [comment]
11个月前提的问题终于解决了。

我刚给https://github.com/fcitx/fcitx/commit/f634890a80d36deec9293d3cc4864f568eab23aa原作者发邮件抱怨过应该不是巧合。
