### ISSUE TITLE
Kubuntu 16.04下，fcitx会在托盘或者Status & Notifications添加一个空图标

### ISSUE THREAD

**Issue by Frederick888** [fcitx/fcitx#267]
登入后
![snapshot11](https://cloud.githubusercontent.com/assets/4507647/15455279/bd7432f6-2092-11e6-92d0-138c6f9035b3.png)
执行`fcitx-autostart`后（蓝牙和邮件之间有个空白）
![snapshot12](https://cloud.githubusercontent.com/assets/4507647/15455280/bd766f12-2092-11e6-88fc-7e7c16fe4b6b.png)
少数情况下系统托盘没有空图标，然而会在Status & Notifications折叠菜单中添加一个空行

**Comment by wengxt** [comment]
https://bugs.kde.org/show_bug.cgi?id=358719

See comment 11.
