### ISSUE TITLE
4k屏幕输入框偏移

### ISSUE THREAD

**Issue by fuchanglin** [fcitx/fcitx#274]
输入法的输入框在4k屏幕下显示的位置不对，比如应该显示的位置是(100,100)，我觉得它显示在了(50,50) ==～
系统ubuntu 16.04 LTS, fcitx版本4.2.9.1

**Comment by wengxt** [comment]
哪个程序？如果是 chromium 的话是他自己的问题。
其他的 gtk3/qt5 4.2.9.1 和 fcitx-qt5 1.0.4 之后应该都已修复。

**Comment by wengxt** [comment]
FYI: https://code.google.com/p/chromium/issues/detail?id=475718

**Comment by fuchanglin** [comment]
您好，的确是Chrome 51有这个问题，系统Terminal下是好的。
WebStorm下输入框也有问题，显示在了程序的左下角。

**Comment by wengxt** [comment]
webstorm 是基于 java 的，所有 java 的程序都这样，只能上游解决。（除了用 native toolkit eclipse 之外）
