### ISSUE TITLE
多语言 spell check

### ISSUE THREAD

**Issue by deva1985** [fcitx/fcitx#275]
因为平时有同时用到英语和德语, 请问有没有办法让 spell hint 功能同时检查两种语言?

**Comment by wengxt** [comment]
装对应的词典(hunspell-{en,de})，不过目前语言和键盘布局对应语言是绑定的

**Comment by deva1985** [comment]
感谢答复
就说现在无法实现?
我用aspell, 对应的词典都有安装. 就是希望比如在德语键盘布局(de-de)时能同时检查英语和德语词典

**Comment by wengxt** [comment]
混杂语言有其他的问题…相似的单词是哪个语言不好确定，那些库并没有在多语言之间决定权重的能力

如果是单纯实现一个切换词典的功能是否可以接受？…

**Comment by deva1985** [comment]
可以的
work around 比没有好 ^_^

**Comment by deva1985** [comment]
抱歉, 请问如何实现一个切换词典的功能呢?
