### ISSUE TITLE
大家好,linuxmint安装fcitx,新手一枚,请教大家一个很新手的问题.

### ISSUE THREAD

**Issue by skybai1987** [fcitx/fcitx#277]
网上找了不少教程了,看的也累啊.就是为了整明白fcitx.
我把我想问的整理在下面,先感谢帮忙的朋友.
第一,fcitx查资料说是一个输入法框架,那么我们在安装的时候,到底要安装哪些,用apt-cache search fcitx,在大堆出来,不知安装哪些,也不知那些有什么用,很糊涂的.如果是一个框架,那么最开始要安装哪些文件.(说下我的理解,fcitx是一个框架,先把框架安装好,然后再安装自己需要的输入法.)

第二,就是安装完毕后,相关配置的事.像什么fcitx-ui-qimpanel,我安装这个文件,别然电脑右下角有一个小企鹅的图标出来,但是点里面的输入法配置,结果里面什么输入法,也没有显示.然后只好卸载.

第三,虽然我安装下面的文件,现在能使用了.但是真不知道完不完美,还有没用的,也装上了.真体也不知道这些文件有什么用.网上资料也找过了.真恨不得,有没有一篇文章能详细介绍一下fcitx全面的.

`apple@apple-virtual-machine ~ $ dpkg --get-selections|grep fcitx
fcitx						install
fcitx-bin					install
fcitx-config-common				install
fcitx-config-gtk				install
fcitx-config-gtk2				install
fcitx-data					install
fcitx-frontend-all				install
fcitx-frontend-fbterm				install
fcitx-googlepinyin				install
fcitx-libs:amd64				install
fcitx-libs-gclient:amd64			install
fcitx-m17n					install
fcitx-module-dbus				install
fcitx-module-x11				install
fcitx-modules					install
fcitx-table					install
fcitx-table-wbpy				install
fcitx-tools					install
fcitx-ui-classic				install
fcitx-ui-light					install
fcitx-ui-qimpanel				install
gir1.2-fcitx-1.0				install
`
比如,fcitx-ui-qimpanel	这个文件不安装,那么在输入法状态图标那里配置输入法的时候,就不会显示出来已安装的输入法,在input method那一项.后面的appearance里面也是空的.

总的来说,如果能有一篇详情的说明文档就好了.把fcitx整明白.
希望得到大家的帮忙,再次感谢了....

**Comment by wengxt** [comment]
issue is not asking question. Please use maillist. fcitx@googlegroups.com
