### ISSUE TITLE
Fwd: KDE Launcher needs a space-prefix for all Fcitx inputs. [reproducible]

### ISSUE THREAD

**Issue by cheese** [fcitx/fcitx#279]
https://bugzilla.redhat.com/show_bug.cgi?id=1357739

Description of problem:

KDE Launcher ignores the first character from Fcitx input.

Version-Release number of selected component (if applicable):
Fcitx: 4.2.9.1-2.fc24

How reproducible:
It always happens.

Steps to Reproduce:
1. Click on the KDE Launcher button on bottom left.
2. You would see a similar to Windows "Start Menu" with a list of "Favorites" applications.
3. Switch to Simplified Chinese (Pinyin) input by right clicking on the Fcitx tray icon (Should be a keyboard) OR from its status bar. The default switching of input languages, "Control + Space" does not work in the KDE launcher but works in KWrite, Chrome, Firefox etc.
4. Type "fanghuoqiang" without the quotes.

Actual results:
The first suggestion from LibPinyin is "f昂火枪" (Pronounced as "f-anghuoqiang" without quotes) which has no actual meaning in Chinese. Literally, it means "f-emotionally fire gun". However, this is the result because KDE Launcher treats the first character ("f") as English while the rest ("anghuoqiang") from LibPinyin instead and hence LibPinyin could not guess the word without the "f" (My LibPinyin did not set to those fuzzy inputs or to guess / autocorrect incomplete Pinyin so as to reduce the candidate entries).

KDE Launcher shows no result from the above f昂火枪 input.

Expected results:
I am expecting the first suggestion from LibPinyin as "防火墙" (It means "Firewall" without quotes).

防火墙 is one of the keyword in KDE Launcher that will launch the GUI module to configure the firewall after root password is given subsequently.

Additional info:
1) The issue applies to other Chinese inputs from fcitx as well, from Wubi to other Traditional Chinese inputs.
2) The switching of input language via "Control + Space" works ONLY if I type a "space" (And thus the KDE Launcher goes into search mode).

The issue does not apply at all when the KDE Launcher is at "Application Menu" mode that resembles more like Windows 98 start menu than Windows 10.

However, the issue is different when the KDE Launcher is using full screen mode similar to Ubuntu's Unity Desktop Launcher. In Full Screen mode, it ignores the original (Current) input settings but does not require a space prefix when the change language input (Default: "Control + Space") is done twice (For a system with only English US input and one other fcitx Chinese input).

The video as attachment can be viewed here:

https://vid.me/xPiw

Please use Chrome or Firefox to view as Konqueror does not work well.

**Comment by wengxt** [comment]
you should ask kde launcher to fix its input method support.
