### ISSUE TITLE
show preedit string as underline

### ISSUE THREAD

**Issue by lbngoc** [fcitx/fcitx#281]
I installed fcitx in previous OS Linux Mint 17 as it was working perfect, but after I upgrade to LM 18, when I typing, the preedit string is shown on a popup. I think it does not look good, it's better if shown as inline with underline format. How can I change this settings ?

**Comment by wengxt** [comment]
Try press ctrl alt p to toggle this, if doesn't work, check whether you install fcitx-frontend-gtk2,3, qt4,5 as need.
