### ISSUE TITLE
.desktop file is missing Version and TryExec tags

### ISSUE THREAD

**Issue by yurivict** [fcitx/fcitx#282]
I think these tags are desirable in general.

**Comment by wengxt** [comment]
I never know that TryExec or Version are required tags. They don't commonly exists in desktop files on my system. Why would you want me to add them?

**Comment by yurivict** [comment]
You are right, these aren't required. TryExec is used to determine if the package is really installed, or this is a stray desktop file. wireshark, qTox, virtualbox, mpv and others use it.

These aren't super important, just somewhat useful, but are also easy to add.

**Comment by wengxt** [comment]
but why would fcitx and fcitx's desktop file be packaged in different packages? If that happens, it must be a packaging issue.

**Comment by wengxt** [comment]
I don't see why it's useful, close it. Feel free to reopen if you have more justification.
