### ISSUE TITLE
fcitx can't terminate and system hangs for 90 seconds during shutdown occasionally

### ISSUE THREAD

**Issue by chih7** [fcitx/fcitx#286]
I am use fcitx + rime.
After upgrading to systemd 230, I am occasionally experiencing this problem.

Attached the shutdown log

```
Aug 06 09:42:46 archlinux systemd[1]: Stopped MariaDB database server.
Aug 06 09:44:13 archlinux systemd[1]: session-c2.scope: Stopping timed out. Killing.
Aug 06 09:44:13 archlinux systemd[1]: session-c2.scope: Killing process 1024 (fcitx) with signal SIGKILL.
Aug 06 09:44:13 archlinux systemd[1]: Stopped Session c2 of user chih.
Aug 06 09:44:13 archlinux systemd[1]: session-c2.scope: Unit entered failed state.
Aug 06 09:44:13 archlinux systemd[1]: Removed slice User Slice of chih.
```

```
Aug 06 22:42:45 archlinux systemd[1]: Stopped Simple Desktop Display Manager.
Aug 06 22:44:11 archlinux systemd[1]: session-c2.scope: Stopping timed out. Killing.
Aug 06 22:44:11 archlinux systemd[1]: session-c2.scope: Killing process 1027 (fcitx) with signal SIGKILL.
Aug 06 22:44:11 archlinux systemd[1]: Stopped Session c2 of user chih.
Aug 06 22:44:11 archlinux systemd[1]: session-c2.scope: Unit entered failed state.
Aug 06 22:44:11 archlinux systemd[1]: Removed slice User Slice of chih.
Aug 06 22:44:11 archlinux systemd[1]: Stopping Login Service...
```

**Comment by wengxt** [comment]
please enable debug-shell.service. when this happens, go to tty9 and use following command to get a backtrace (better save it under your root home directory so you can execute it easily).

You'll get a gdb.bt  (debug-shell's pwd is / ).

    gdb --pid=`pidof fcitx` -batch-silent  -ex "set logging overwrite on" -ex "set logging file gdb.bt" -ex "set logging on" -ex "set pagination off" -ex "handle SIG33 pass nostop noprint" -ex "echo backtrace:\n" -ex "thread all apply backtrace full" -ex "echo \n\nregisters:\n" -ex "info registers" -ex "echo \n\ncurrent instructions:\n" -ex "x/16i \$pc" -ex "echo \n\nthreads backtrace:\n" -ex "thread apply all backtrace" -ex "set logging off"

**Comment by chih7** [comment]
After some upgrade (I do not know which package),  the problem no longer occurs.
