### ISSUE TITLE
候选框在hidpi时候的跟随

### ISSUE THREAD

**Issue by intijk** [fcitx/fcitx#293]
换了新环境以后测了测新的4k，我是在Ubuntu 14.04的unity 环境下。一般为了照顾dpi问题会在display里面设置scale for menu and title bars 为2，但是fcitx的输入候选框只能在这个值为1的时候才能正确的跟随，当我设为2的时候候选框的位置正好是实际位置偏左上的二分之一处。

在此汇报下此问题。

**Comment by happyaron** [comment]
Ubuntu 上也报很久了，麻烦看一下吧

https://bugs.launchpad.net/ubuntu/+source/fcitx/+bug/1454200

**Comment by intijk** [comment]
我看到目前状态是confirmed了，代码上已经修了吗，我可以自己装新版修复这个bug吗

**Comment by wengxt** [comment]
这个不是早就 fix 了吗？……

https://github.com/fcitx/fcitx/commit/c3e273f18af2160c916d7fad0a451ee230313e14

如果只是 qimpanel 那不关我事。

**Comment by intijk** [comment]
这个问题貌似依旧在chrome里存在。Firefox里测试是好的。

**Comment by wengxt** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=774974
