### ISSUE TITLE
系统托盘是否支持KDE工作空间主题图标？

### ISSUE THREAD

**Issue by guoyunhe** [fcitx/fcitx#294]
目前 Fcitx 的输入法图标，包括英文键盘，拼音，谷歌拼音，SunPinyin，Libpinyi，都是存放在图标主题的 apps 子文件夹的。在 KDE 5 的 Breeze 系统下里，这些 fcitx-* 图标也是放在 apps 下面的，使用的是一些黑白线条的图标。

![spectacle b15152](https://cloud.githubusercontent.com/assets/5836790/18964543/03a3ceee-8682-11e6-8860-484f2638f4eb.png)

KDE 的 Breeze 图标制作小组正在进行 apps 文件夹的清理，apps 下面的图标将全部变成彩色，而非 App 的图标，比如拼音，会被移动到 Plasma 工作空间主题里（就像 Amarok）或者 status 里。

在他们完成这个操作后，在 KDE 5 里面的 Fcitx 托盘图标就会变回原来的彩色 PNG 了，与系统主题不协调。

他们给出两种解决方案：

1. 优先使用 Plasma 桌面主题的图标，这需要 TrayIcon 继承 KStatusNotifierItem 类并用 `setIconByName( "fcitx-pinyin" )` 来设置图标。当主题图标不存在的时候，再使用使用系统图标。
2. 优先使用 status 图标，Breeze 的 fcitx-* 图标都会移动到 status 文件夹里面。在 KDE 5 / Breeze 里面，这些图标和托盘图标是一样风格的。

**Comment by wengxt** [comment]
ˊ_>ˋ 反正是 status notification item 系统是啥就用啥

**Comment by guoyunhe** [comment]
貌似 KDE 4 的时候可以改一个 input.svgz 就把 input-keyboard 的图标替换掉，但是现在 KDE 5 不行了。

Fcitx 可以用自身皮肤里的 input-keyboard.png 吗？这样还可以用皮肤来实现和 KDE 5 一致的主题。

**Comment by guoyunhe** [comment]
现在 Fcitx 英文键盘在 KDE 5 里看起来是这样子的，用的是 devices/input-keyboard 这个图标，但却是 64px 大图标，而不是 22px 小图标。这个是由 Fcitx 决定的还是 KDE 决定的？

![spectacle d31341](https://cloud.githubusercontent.com/assets/5836790/18992775/ca350932-8728-11e6-84c1-5db5e14a7508.png)

![spectacle h31341](https://cloud.githubusercontent.com/assets/5836790/18992991/cbba8330-8729-11e6-86e5-d0dd9acd67e3.png)

![spectacle o31341](https://cloud.githubusercontent.com/assets/5836790/18993015/e52674b4-8729-11e6-81ee-0b254d9f7bf7.png)

**Comment by wengxt** [comment]
╮(￣▽￣)╭ 反正不是我的问题。

按我对 plasma theme 的了解你得把这个 input-keyboard 加入到 input.svgz 里面去

**Comment by guoyunhe** [comment]
已经把 input-keyboard 加到 input.svgz 里面，然而并不管用…

**Comment by wengxt** [comment]
那肯定是你的姿势不对，我复制了一个图标粘贴一下改了 id 就管用了（图中鼠标图案）
![spectacle gz2247](https://cloud.githubusercontent.com/assets/259684/19000158/e7fe52f8-86f5-11e6-8365-ec4425207600.png)

**Comment by guoyunhe** [comment]
我再试试！

你是改了 `/usr/share/plasma/desktoptheme/default/icons/input.svgz` 这个文件吗？是不是需要清理缓存才能生效？

**Comment by wengxt** [comment]
我不想改系统文件所以我就是保存到 ~/.local/share/plasma/desktoptheme/default/icons/input.svgz 了，但肯定都一样

你试试重启一下 plasma 或者切换一下主题再切回来

**Comment by guoyunhe** [comment]
我还是不成功，已经重启 Plasma 切换主题并删除了 cache ……能把你修改的 input.svgz 文件借我用用吗！

**Comment by wengxt** [comment]
已发到你邮箱

重要的就是对象名称和 label 都要是 input-keyboard

**Comment by guoyunhe** [comment]
我成功了！我操作时候有两个错误：

1. SVGZ 文件里只改了 ID
2. 只清除了 plasma theme 缓存，没有清除 plasma svg 缓存

我试着搞一搞键盘和拼音的图标，看看能不能整合进 Plasma 里面。

感谢！

**Comment by wengxt** [comment]
fcitx 图标很多的……不要光搞这几个，比如全角半角

kimpanel 上显示的图标更多你可以看看。

**Comment by guoyunhe** [comment]
OK

**Comment by guoyunhe** [comment]
这个图标好大！是 Kpimpanel Widget 自定的图标尺寸，还是图标不适配？

![spectacle h21834](https://cloud.githubusercontent.com/assets/5836790/19003522/e9c718ea-8759-11e6-938b-695dc5e64faa.png)

**Comment by wengxt** [comment]
单纯是和面板一样大，新版托盘最大大小变了所以你觉得大…

**Comment by guoyunhe** [comment]
感觉可以协调一下，与 KDE 托盘使用几个固定尺寸同步。KDE 好像只有 16，22，32 这三个尺寸。
