### ISSUE TITLE
For "fcitx/pull/301": Suggestion doesn't help to prevent fcitx crash.

### ISSUE THREAD

**Issue by ghostplant** [fcitx/fcitx#302]
Sorry to say that your suggestion does not work as well, I tried "fcitx --disable fcitx-xkb" but crashed for another reason:

dependency not satisfied: fcitx-xkbdbus depends on fcitx-xkb, fcitx-dbus. Exiting.
Then, I tried "fcitx --disable fcitx-xkbdbus" and "fcitx --disable fcitx-xkbdbus,fcitx-xkb" but all crashed as well.

All my executions are on a fresh Ubuntu OS and VNC server environment.
Any other suggestions?

I tested that Ignoring BadValue error from Xlib is a solution that works.

**Comment by wengxt** [comment]
Then your error doesn't come from xkb. That error message will not crash fcitx. In any case, ignore an X error is not the right way to go.

**Comment by wengxt** [comment]
What's your vnc server? I tried tigervnc localily and didn't reproduce the problem.

**Comment by ghostplant** [comment]
I use Ubuntu 16.04 and vncserver which is installed from official repository. Fcitx only launched correctly on original desktop (DISPLAY=:0), but crash on vncserver(DISPLAY=:1). Many people reported this previously but no solution was given. I go through the source code and found that it's closed for BadValue exception.
NOET: All packages are installed from Ubuntu repository, so fcitx is currently unable to startup under vncserver in Ubuntu 16.04 Server/Desktop/..

**Comment by wengxt** [comment]
which package provides your vncserver command?

**Comment by ghostplant** [comment]
In vncserver, I firstly run "eval $(dbus-launch --sh-syntax)",  then:

if I run fcitx directly, it crashes for BadValue exception;
if I run fcitx --disable fcitx-xkb, it exited for unsatified dependency;
if I run fcitx --disable fcitx-xkb,fcitx-xkbdbus , it still exited but with no reason reported;

if I recompile the fcitx with the BadValue ignorance from Ubutnu 16.04 Xlib, it works sucessfully.

**Comment by ghostplant** [comment]
apt-get install vnc4server
