### ISSUE TITLE
fcitx导致cpu100%问题

### ISSUE THREAD

**Issue by lmq3342xja** [fcitx/fcitx#305]
(gdb) bt
#0  0x00007f4371a3a7ad in accept () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f436804f329 in UdAccept (listenfd=12)
    at /home/kylin/fcitx/fcitx-4.2.9.1/src/module/remote/remote.c:129
#2  RemoteProcessEvent (p=0x5597bbd16060)
    at /home/kylin/fcitx/fcitx-4.2.9.1/src/module/remote/remote.c:151
#3  0x00007f437207a78e in RunInstance (arg=arg@entry=0x5597bb5c3120)
    at /home/kylin/fcitx/fcitx-4.2.9.1/src/lib/fcitx/instance.c:332
#4  0x00007f437207b170 in FcitxInstanceRun (argc=1, argv=0x7ffe3f916f08, fd=3)
    at /home/kylin/fcitx/fcitx-4.2.9.1/src/lib/fcitx/instance.c:140
#5  0x00005597bb10bfec in main (argc=1, argv=0x7ffe3f916f08)
    at /home/kylin/fcitx/fcitx-4.2.9.1/src/core/fcitx.c:80

**Comment by lmq3342xja** [comment]
int UdAccept(int listenfd)
{
    for (;;) {
        int newsock = 0;
        struct sockaddr_un cliaddr;
        socklen_t len = sizeof(struct sockaddr_un);

        newsock = accept(listenfd, (struct sockaddr *)&cliaddr, &len);
        if (newsock < 0) {
            if (errno == EINTR) {
                continue; /* signal */
            }
        }

        return newsock;
    }
}
额，不明原因

**Comment by daya0576** [comment]
你好,我也一直遇到这个问题  你最后解决了吗?

thx

**Comment by lmq3342xja** [comment]
@daya0576 这是个概率性bug...重启fcitx就好了

**Comment by daya0576** [comment]
概率性bug?! 但经常出现, 只能放弃搜狗拼音了.
