### ISSUE TITLE
Fcitx won't work in JavaFX application

### ISSUE THREAD

**Issue by Gabirel** [fcitx/fcitx#309]
Hello, there！

Fcitx won't work in JavaFX application with Linux.

I've tried in windows. Yes. JavaFX do seem to support Chinese. 
However it won't work in my `Linux (Fedora24)`.
NOT EVEN Chinese, Japanese or Korean.

I don't know how to solve it. 

Help ME,please!!
> Extra: I can type Japanese, or Chinese and korean in JavaFX application who is compiled in IDEA. But I can't type any characters in stand-alone JavaFX application.

**Comment by wengxt** [comment]
Check this pls https://fcitx-im.org/wiki/FAQ

**Comment by Gabirel** [comment]
Yes, the problem  is that `Ctrl`+`Space` does not call Fcitx. I set hotkey `Ctrl+Space` and `Super+Space` instead of the single `Ctril+Space` . It works for me, although I don't know why.

> Reference: https://fcitx-im.org/wiki/FAQ#When_use_Ctrl_.2B_Space.2C_Fcitx_cannot_be_triggered_on

Thanks
