### ISSUE TITLE
Question about Zhengma table (fcitx-table-extra)

### ISSUE THREAD

**Issue by SRGOM** [fcitx/fcitx#310]
This should belong to #fcitx/fcitx-table-extra but I don't see the issue tab there so asking here if I can get any help. Does anyone know where can I get more information about the  the licensing terms for the Zhengma tables?

 I will be using it on a personal computer and will be making money by selling the content typed using it directly.

**Comment by marguerite** [comment]
Zhengma is now public domain. Its patent expired at 2009 

see README of fcitx-table-extra.

**Comment by SRGOM** [comment]
Thanks @marguerite
