### ISSUE TITLE
Ubuntu 16.04 repository

### ISSUE THREAD

**Issue by colibris79** [fcitx/fcitx#311]
Hi there. I would like to install fcitx last version in Mint 18 (Ubuntu 16.04) but I've just found that the repository does not support Xenial. Are you planning to include it or is there any other way to install last version?

**Comment by yuyichao** [comment]
That's an issue for the distribution.

**Comment by colibris79** [comment]
Sorry and thanks for your answer! Has anyone tell them already? If not I can do it in

**Comment by wengxt** [comment]
I don't know which repo you mean, but the offical repo has the latest version.

http://packages.ubuntu.com/xenial/fcitx-bin

**Comment by colibris79** [comment]
My bad... I thought it had the same version as trusty (4.2.8.1). Thanks, wengxt
