### ISSUE TITLE
Often losting a letter when I use sunpinyin to type Chinese

### ISSUE THREAD

**Issue by Sevenskey** [fcitx/fcitx#312]
The screenshot below illustrates this strange behavior.

![img_20161212_105318](https://cloud.githubusercontent.com/assets/10772756/21086656/851f174c-c059-11e6-8ec4-ec1c9d0df65c.jpg)

Originally I want to type "shang" , but the letter "n" pops out the black input area and presents to the text area.

The behavior often appears since I reinstall my operate system two months ago.

My operate system: Arch Linux with version 4.8.12-3
Fcitx version: 4.2.9.1

**Comment by wengxt** [comment]
应该是没装 fcitx-gtk2/3 并设置 GTK_IM_MODULE 为 fcitx ?

可以贴一个 fcitx-diagnose 输出看看。

**Comment by Sevenskey** [comment]
@wengxt 非常感谢你的提醒！
