### ISSUE TITLE
fcitx is Not Compatible with the newest harfbuzz-1.4.1-1

### ISSUE THREAD

**Issue by z7fir** [fcitx/fcitx#317]
After I upgrade harfbuzz to 1.4.1, it occurs: 

**(ERROR-31381 /build/fcitx/src/fcitx-4.2.9.1/src/lib/fcitx/module.c:61) Module: open /usr/lib/fcitx/fcitx-vk.so fail /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
(ERROR-31381 /build/fcitx/src/fcitx-4.2.9.1/src/lib/fcitx/ime.c:432) fcitx-keyboard-cm-mmuock already exists
(ERROR-31381 /build/fcitx/src/fcitx-4.2.9.1/src/lib/fcitx/ui.c:192) UI: open /usr/lib/fcitx/fcitx-classic-ui.so fail /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates**

When I type something, no panel pops up.

**Comment by yuyichao** [comment]
Rebuild fcitx/freetype2/whatever links to harfbuzz

**Comment by wengxt** [comment]
it's a packaging issue, please report to your distribution.

**Comment by z7fir** [comment]
Thanks. It's a issue of the freetype2-infinality package.

**Comment by xTpx** [comment]
请问这个 fcitx-keyboard-cm-mmuock 是什么东西？
在配置文件里貌似默认关闭 fcitx-keyboard-cm-mmuock:False
但是启动 fcitx 总是提示 (ERROR-11879 ime.c:432) fcitx-keyboard-cm-mmuock already exists
虽说并不影响使用。
