### ISSUE TITLE
ctrl+shift+u 快捷键不能显示 u̲ 字符提示

### ISSUE THREAD

**Issue by fourcels** [fcitx/fcitx#318]
安装 `fcitx` 后, `ctrl+shift+u` 快捷键 不能显示 u̲ 提示输入 unicode
![screenshot - 01092017 - 09 12 32 am](https://cloud.githubusercontent.com/assets/1042568/21755297/a9e32d26-d64c-11e6-9531-f869bbe16252.png)

系统环境
```bash
~ ᐅ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie

~ ᐅ fcitx -v
fcitx version: 4.2.8.5

```

**Comment by wengxt** [comment]
这是 gtk simple im module 提供的功能，fcitx 的 im module 不实现这种功能。你可以考虑使用 fcitx 的类似功能，用 ctrl + shift + alt + u 触发 https://fcitx-im.org/wiki/Unicode

**Comment by fourcels** [comment]
@wengxt 
只是  u̲  字符不能出现
输入 `ctrl+shift+u`  `ae` `enter` 还是能正常出现 `unicode` 字符 `®`

我对比了下 `ibus`

![screenshot - 01092017 - 09 53 56 am](https://cloud.githubusercontent.com/assets/1042568/21755641/16f0777a-d652-11e6-933c-56462cf79932.png)

关闭了 `Embed preedit text in application window` 情况跟 `fcitx` 一样不能显示 u̲  字符, 开启后就正常了

**Comment by wengxt** [comment]
´_>` 好吧但是我还是不在乎这个功能。这是一个 Gtk Only 的功能而且明显同时占用了输入法的 preedit 来显示 u 下划线，不和输入法冲突也只是运气问题。而且 fcitx 提供了更强的替代功能。

**Comment by fourcels** [comment]
@wengxt 
当用户无意识的输入 `ctrl+shift+u` 快捷键后, 没有任何提示, 字符却不能输入了,  这时用户可能不知道自己在 `unicode` 输入模式, 也不知道如何退出
