### ISSUE TITLE
sudo打开的图形程序不能切换？？

### ISSUE THREAD

**Issue by V0idk** [fcitx/fcitx#319]
还是我设置问题

**Comment by wengxt** [comment]
https://fcitx-im.org/wiki/FAQ/zh-hans#.E5.9C.A8.E4.B8.80.E8.88.AC.E7.94.A8.E6.88.B7.E7.9A.84_X_.E4.B8.8B_.E8.BF.90.E8.A1.8C_Root_.E6.9D.83.E9.99.90.E7.9A.84.E7.A8.8B.E5.BA.8F

**Comment by V0idk** [comment]
你太快了 兄弟佩服@wengxt

**Comment by V0idk** [comment]
等下，现在sudo打开的程序能去切换了，gksu还是不能切换。@wengxt

**Comment by wengxt** [comment]
同理 ´_>` 。
