### ISSUE TITLE
输入酷安的ku'an时，fcitx会崩溃

### ISSUE THREAD

**Issue by Sherlock-Holo** [fcitx/fcitx#320]
如果输入酷安的ku'an时，fcitx会崩溃。
使用fcitx-libpinyin
表现为输入ku后跟着 ' 就fcitx立即退出
百分百重现

**Comment by Sherlock-Holo** [comment]
>
3.  `~/.config/fcitx/log/crash.log`:

        =========================
        FCITX 4.2.9.1 -- Get Signal No.: 11
        Date: try "date -d @1485230804" if you are using GNU date ***
        ProcessID: 22397
        fcitx[0x40159b]
        /usr/lib/libc.so.6(+0x330b0)[0x7f3f36b060b0]
        /usr/lib/libc.so.6(+0x97b42)[0x7f3f36b6ab42]
        /usr/lib/libfcitx-core.so.0(FcitxMessagesMessageConcatLast+0x21)[0x7f3f374d2bc1]
        /usr/lib/fcitx/fcitx-libpinyin.so(+0x5127)[0x7f3f214d7127]
        /usr/lib/fcitx/fcitx-libpinyin.so(+0x6652)[0x7f3f214d8652]
        /usr/lib/libfcitx-core.so.0(FcitxInstanceDoInputCallback+0x1ba)[0x7f3f374d143a]
        /usr/lib/libfcitx-core.so.0(FcitxInstanceProcessKey+0x651)[0x7f3f374d1b11]
        /usr/lib/fcitx/fcitx-ipc.so(+0x5987)[0x7f3f1fda6987]
        /usr/lib/libdbus-1.so.3(+0x25873)[0x7f3f36154873]
        /usr/lib/libdbus-1.so.3(dbus_connection_dispatch+0x3c4)[0x7f3f36145ef4]
        /usr/lib/fcitx/fcitx-dbus.so(+0x21a8)[0x7f3f363811a8]
        /usr/lib/libfcitx-core.so.0(+0xa216)[0x7f3f374c5216]
        /usr/lib/libfcitx-core.so.0(FcitxInstanceRun+0x210)[0x7f3f374c5be0]
        fcitx[0x400f76]
        /usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7f3f36af3291]
        fcitx(_start+0x29)[0x400fe9]
>

**Comment by wengxt** [comment]
please use fcitx/fcitx-libpinyin#21 .
