### ISSUE TITLE
How to trigger pinyin-stroke-input (笔画筛选)

### ISSUE THREAD

**Issue by bohrshaw** [fcitx/fcitx#322]
I suppose the stoke-input feature should be triggered by a key which I don't know what it is. I tried `Tab` but it doesn't work. @yuyichao

**Comment by yuyichao** [comment]
No it doesn't need to be trigged by a key.

**Comment by bohrshaw** [comment]
Could you provide an example illustrating how stroking is used? I'm not sure which key coresponds to which stroke, as I don't find any reference about this feature. It would be nice to extend <https://fcitx-im.org/wiki/PinyinEnhance>.

As for the design, if the stroke-mode is triggered by a key, then it can support Shuangpin. Do you consider this as an option?

**Comment by yuyichao** [comment]
![spectacle n27099](https://cloud.githubusercontent.com/assets/712232/23102946/50f8e4c2-f680-11e6-829c-8e33f930c25e.png)

> As for the design, if the stroke-mode is triggered by a key, then it can support Shuangpin. Do you consider this as an option?

No. That's just switching input methods.

**Comment by bohrshaw** [comment]
哦，懂了，感谢截图，这原来是一个笔画输入模式。
我错误地以为这个功能像搜狗的[笔画筛选](http://pinyin.sogou.com/help.php?list=3&q=9)一样是用拼音输入之后再用笔画来做筛选。
