### ISSUE TITLE
fcitx binded ime is not working other than terminal

### ISSUE THREAD

**Issue by lv7777** [fcitx/fcitx#323]
see detail https://github.com/fcitx/fcitx5/issues/1

I tryed `gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'fcitx'>}"`
and re-login, but the ploblem is not fixed.

**Comment by wengxt** [comment]
Try use im-config to set it to fcitx? Is Kali a debian based distro?

**Comment by lv7777** [comment]
sorry late reply.

> Try use im-config to set it to fcitx? Is Kali a debian based distro?
both yes.

I tried change config, but can't running fcitx.
so I changed to ibus.

thanks.
