### ISSUE TITLE
请问怎样隐藏fcitx运行时显示在顶部面板的图标？

### ISSUE THREAD

**Issue by SiShanZI** [fcitx/fcitx#325]
现用Ubuntu 16.04，Unity，系统设置不管用啦

**Comment by wengxt** [comment]
如果是 unity 自己显示的那个大概不能吧，如果是 fcitx 的，在经典界面里面把托盘勾掉

**Comment by SiShanZI** [comment]
![fcitx](https://cloud.githubusercontent.com/assets/20335680/23841813/e67bd6aa-07ea-11e7-8285-66ca678cf6b0.png)
像图片那样，之前版本的Ubuntu默认ibus，记得可以设置隐藏；其实是想自定义这个面板，哪些显示，哪些不显示，但是不知道unity（好像有什么白名单）或者软件的设计理念，比如这个有道词典，装了之后只要启动就会显示在面板上，软件设置里面没有相应选项
