### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode

### ISSUE THREAD

**Issue by hongyi-zhao** [fcitx/fcitx#326]
Hi,

I try to compile the git version of fcitx, but meet the following error when type the make command:

> > /home/werner/fcitx/fcitx.git/src/module/remote/remote.c: In function ‘UdAccept’:
/home/werner/fcitx/fcitx.git/src/module/remote/remote.c:124:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i =0;i<20;i++) {
     ^
/home/werner/fcitx/fcitx.git/src/module/remote/remote.c:124:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
src/module/remote/CMakeFiles/fcitx-remote-module.dir/build.make:54: recipe for target 'src/module/remote/CMakeFiles/fcitx-remote-module.dir/remote.c.o' failed
make[2]: *** [src/module/remote/CMakeFiles/fcitx-remote-module.dir/remote.c.o] Error 1
CMakeFiles/Makefile2:4168: recipe for target 'src/module/remote/CMakeFiles/fcitx-remote-module.dir/all' failed
make[1]: *** [src/module/remote/CMakeFiles/fcitx-remote-module.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wengxt** [comment]
we require c99 for now. I changed the cmake requirements to 3.1 to support the variable.
