### ISSUE TITLE
feature request: insert time quickly by typing sj

### ISSUE THREAD

**Issue by YuSuu** [fcitx/fcitx#329]
im a user from china,
here is a typing method called Sogou Pinyin .
there is a feature that can insert time quickly by typing sj
sj is an abbr. for shijian (pinyin for 时间 means time).this function 
is very convenient . i hope fcitx can add the same feature

**Comment by wengxt** [comment]
You may use:
https://github.com/lilydjwg/fcitx-lua-scripts/blob/master/date.lua

put it under ~/.config/fcitx/lua/

And type either "vdt" or ";dt" to trigger it under pinyin.

**Comment by YuSuu** [comment]
@wengxt thanks for your help,
that makes much much more convenient for me
