### ISSUE TITLE
关于fcitx pinyin的 issue

### ISSUE THREAD

**Issue by YuSuu** [fcitx/fcitx#330]
有些词组就算输入过很多次过后还是不能记住，
比如，
奥利奥。 输入aoliao，一直都是，“奥聊”，
还有，重新安装。输入chongxinasnzhuang，一直都是，“冲洗男装”
一定要有分词符，希望能解决一下！

**Comment by wengxt** [comment]
wont fix.

try sunpinyin / libpinyin
