### ISSUE TITLE
部分按键设置为翻页快捷键后无效

### ISSUE THREAD

**Issue by OrcaXS** [fcitx/fcitx#333]
Plasma 5.9.5, fcitx 4.2.9.1-2, kimpanel
`-=` `,.` `PageUp PageDown` `Up Down` `Tab Shift+Tab` 等均有效。
测试了 `[]` `;'` 这两组按键无效，且会把当前候选字 commit 并且输入对应的标点符号。

**Comment by wengxt** [comment]
因为设置冲突了啊 ´_>` …… 引号是分隔符（例如 xi'an）
[] 默认是以词定字选字用的，这个倒是可以在设置里面改。

**Comment by wengxt** [comment]
![spectacle x21043](https://cloud.githubusercontent.com/assets/259684/25446371/30813892-2a66-11e7-9033-53d8ff83263c.png)

**Comment by zyf0330** [comment]
设置为 9 和 0 也不生效，候选词长度我设置的6
