### ISSUE TITLE
Could not self-define page switcher

### ISSUE THREAD

**Issue by meijieru** [fcitx/fcitx#337]
`[]` does not make sense to when I set following in `$HOME/.config/fcitx/config`
```
PrevPageKey=PGUP [
NextPageKey=PGDN ]
```
However, `,.` could be used.
Does anyone meet the same issue?

**Comment by wengxt** [comment]
[] conflicts with some option defined in pinyin-enhance by default. you can clear that option (2rd 3nd selection)
