### ISSUE TITLE
add ppa error

### ISSUE THREAD

**Issue by tudousay** [fcitx/fcitx#340]
My os is ubuntu 16.04, when I use command: 
sudo add-apt-repository ppa:fcitx-team/stable
it's work like this:
Stable releases of Fcitx for all supported Ubuntu releases.
 More info: https://launchpad.net/~fcitx-team/+archive/ubuntu/stable
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp18bi43ns/secring.gpg' created
gpg: keyring `/tmp/tmp18bi43ns/pubring.gpg' created
gpg: requesting key 7E5FA1EE from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp18bi43ns/trustdb.gpg: trustdb created
gpg: key 7E5FA1EE: public key "Launchpad PPA for Fcitx Team PPA" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

and then i do this:
sudo apt-get update
An error has occurred：
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable Release                                                                                   
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial InRelease                                                                                   
Ign:5 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial InRelease                                                                     
Hit:6 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                   
Hit:7 http://archive.canonical.com/ubuntu xenial InRelease                                    
Hit:8 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease                            
Ign:9 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial Release  
Hit:10 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease   
Ign:11 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 Packages
Ign:12 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main i386 Packages
Ign:13 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main all Packages
Ign:14 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en_US
Ign:15 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en
Ign:16 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:17 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:11 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 Packages
Ign:12 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main i386 Packages
Ign:13 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main all Packages
Ign:14 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en_US
Ign:15 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en
Ign:16 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:17 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:11 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 Packages
Ign:12 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main i386 Packages
Ign:13 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main all Packages
Ign:14 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en_US
Ign:15 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en
Ign:16 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:17 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:11 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 Packages
Ign:12 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main i386 Packages
Ign:13 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main all Packages
Ign:14 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en_US
Ign:15 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en
Ign:16 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:17 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main DEP-11 64x64 Icons
Ign:11 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 Packages
Ign:12 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main i386 Packages
Ign:13 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main all Packages
Ign:14 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en_US
Ign:15 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en
Ign:16 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:17 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main DEP-11 64x64 Icons
Err:11 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:12 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main i386 Packages
Ign:13 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main all Packages
Ign:14 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en_US
Ign:15 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main Translation-en
Ign:16 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:17 http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial/main DEP-11 64x64 Icons
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/fcitx-team/stable/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/fcitx-team/stable/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Lin-Buo-Ren** [comment]
Hello, Fcitx PPA seems not longer be maintained and don't release any packages for Ubuntu 16.04, thus the 404 Not Found error.

Currently you can build Fcitx from source code or search if there's third-party software sources that provides newer version of Fcitx.

**Comment by wengxt** [comment]
This ppa is unmaintained for a long time, and all latest package should available in newer ubuntu release, so there's no need to maintain this ppa anymore.

**Comment by wengxt** [comment]
This ppa is unmaintained for a long time, and all latest package should available in newer ubuntu release, so there's no need to maintain this ppa anymore.
