### ISSUE TITLE
请求 Fcitx wiki 的帐号时发生 PHP mail() 错误

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [fcitx/fcitx#341]
如下图，还是本来就没有开放注册帐号？
![_040](https://user-images.githubusercontent.com/13408130/27493378-3d289678-587c-11e7-8e44-a3674f080cb5.png)

**Comment by wengxt** [comment]
换了服务器之后还没配置这个……我去看看……

**Comment by wengxt** [comment]
应该已经可以了，请收邮件时检查 spam folder
