### ISSUE TITLE
build shell scripts are not POSIX compatible

### ISSUE THREAD

**Issue by haasn** [fcitx/fcitx#342]
I get lots of errors, including but not limited to:
`
/home/nand/dev/fcitx/cmake/fcitx-merge-config.sh: 1: eval: Bad substitution
`

Changing `/bin/sh` to point to `/bin/bash` fixes it as a work-around. I was unable to identify a specific list of broken scripts, so it would probably be a good idea to just change all of them to use `/bin/bash`.

**Comment by wengxt** [comment]
@yuyichao 
I guess this should be fixed with #!/bin/bash?

**Comment by haasn** [comment]
Yes, and in fact this modification fixes it, although it may be overkill.

```find . -name '*.sh' -exec sed 's:^#!/bin/sh$:#!/bin/bash:' -i {} \+```

**Comment by Arfrever** [comment]
The following command shows that currently there are 7 scripts using `#!/usr/bin/env bash`, 1 script using `#!/bin/bash` and 7 scripts using `#!/bin/sh` shebang:
```
$ head -n1 $(find -name "*.sh" | sort)
==> ./cmake/fcitx-cmake-helper.sh <==
#!/bin/bash

==> ./cmake/fcitx-extract-confdesc.sh <==
#!/usr/bin/env bash

==> ./cmake/fcitx-extract-desktop.sh <==
#!/usr/bin/env bash

==> ./cmake/fcitx-extract-gettext.sh <==
#!/usr/bin/env bash

==> ./cmake/fcitx-extract-kde.sh <==
#!/usr/bin/env bash

==> ./cmake/fcitx-extract-po.sh <==
#!/usr/bin/env bash

==> ./cmake/fcitx-extract-qt.sh <==
#!/usr/bin/env bash

==> ./cmake/fcitx-merge-config.sh <==
#!/bin/sh

==> ./cmake/fcitx-parse-po.sh <==
#   Copyright (C) 2012~2013 by Yichao Yu

==> ./cmake/fcitx-write-po.sh <==
#   Copyright (C) 2012~2012 by Yichao Yu

==> ./data/env_setup.sh <==
#!/bin/sh

==> ./data/icon/data/gen.sh <==
#!/bin/sh

==> ./data/script/fcitx-configtool.sh <==
#!/bin/sh

==> ./data/script/fcitx-diagnose.sh <==
#!/usr/bin/env bash

==> ./src/lib/fcitx-qt/gen_dbus.sh <==
#!/bin/sh

==> ./src/lib/fcitx-utils/gen-hotkey.sh <==
#!/bin/sh

==> ./src/ui/classic/fcitx-skin-installer.sh <==
#!/bin/sh
```

I suggest to consistently use `#!/usr/bin/env bash` shebang in all scripts.

**Comment by yuyichao** [comment]
It was set to `/bin/sh` previously since `checkbashism` didn't report any issue........................
