### ISSUE TITLE
有关全角的很烦人的问题

### ISSUE THREAD

**Issue by hippyk** [fcitx/fcitx#344]
我在设置里面把触发全角的快捷键 shift space 清空了，but，经过一段不确定的时间（不一定要重启），这个快捷键又卷土重来，全角模式一不小心又会被开启

**Comment by hippyk** [comment]
os： mint 18.1

**Comment by hippyk** [comment]
目前采取了一个办法，就是不清除快捷键，而是换成一个复杂的，重启之前效果不错，再观察看看

**Comment by yuyichao** [comment]
> 设置里面把触发全角的快捷键 shift space 清空了

你具体是在哪里怎么清的.

**Comment by wengxt** [comment]
我在想没有什么代码会去保存config啊，难道是ubuntu的settings daemon干了什么？你是用ubuntu吗

哦还是说你用sogou然后sogou干了些什么？…

**Comment by hippyk** [comment]
@yuyichao fcitx的高级设置里面，好像是按esc吧，快捷键那里变成了空白

**Comment by wengxt** [comment]
@hippyk 你是不是用 搜狗 的？我隐约记得 sogou 好像会强改 fcitx 有些设置…其他情况我想像不到哪里有问题

**Comment by hippyk** [comment]
@wengxt 是用的搜狗

**Comment by hippyk** [comment]
今天重启了一次，那个设置又被重置成shift+space了

**Comment by hippyk** [comment]
这个问题实在是不能再烦人了!  强烈建议把默认快捷键改一个超级复杂的，或者干脆remove这个毫无用处的全角模式！

**Comment by hippyk** [comment]
@wengxt 可以告诉我全角的默认快捷键在代码里面设置的地方吗？

**Comment by wengxt** [comment]
老实说，默认这个是设置为空的，因为我也觉得不是什么常用功能。

在 /usr/share/fcitx/configdesc/config.desc ，所以我不知道到底是什么程序把他设置成了你的快捷键。我建议你给 sogou 汇报一下bug。

另外你可以去 addon 里面禁用一下全角大概也可以

**Comment by hippyk** [comment]
@wengxt 禁用addon果然好用啊，没想到解决办法如此简单！多谢大神那！么么哒啊！
