### ISSUE TITLE
自带剪切板的快捷键有点烦人，把我程序的快捷键给覆盖了

### ISSUE THREAD

**Issue by netjune** [fcitx/fcitx#354]
请问，如何关掉这个功能？

另外，既然是为了方便键盘操作，上下选择的快捷键是什么？如果是方向键就不方便了，可以考虑ctrl-n和ctrl-p

**Comment by wengxt** [comment]
配置里面可以选择不同的按键或者你可以禁用。

**Comment by netjune** [comment]
找到了这个文件：.config/fcitx/conf/fcitx-clipboard.config

禁用是设置TriggerKey=None吗？

另外，我设置TriggerKey=CTRL_&， 这个快捷键好像不管用。

**Comment by wengxt** [comment]
测试可用，你是不是没有重新加载配置？
禁用就什么都不写就好了。

**Comment by netjune** [comment]
问题没解决就关闭了， 晕倒。

当然重启了，确实不管用，算了。

**Comment by wengxt** [comment]
这里本来就不是提问的地方，一开始早该关了。

而且确实我测试能用啊。因此更可能是你哪里写错了。
文件 ~/.config/fcitx/conf/fcitx-clipboard.config
```code
[Clipboard]
# 将剪贴板历史保存为文件
# Available Value:
# True False
#SaveHistoryToFile=True
# 剪切板历史长度
#HistoryLength=5
# 每个候选词最大长度
#CandidateMaxLength=33
# 剪贴板历史快捷键
TriggerKey=CTRL_&
# 使用选区文字
# Available Value:
# True False
#UsePrimary=True
# 选词修饰键
# Available Value:
# None Alt Ctrl Shift
#ChooseModifier=None
# 忽略空白的剪贴板内容
# Available Value:
# True False
#IgnoreBlank=True

```
