### ISSUE TITLE
unavailable keyboards on nixos

### ISSUE THREAD

**Issue by teto** [fcitx/fcitx#357]
Hi, 

I am on nixos with a French keyboard trying to write in Japanese.
I don't know if my problem comes from nixos or a misconfiguration (or both). When I have fcitx running, everytime I hit "space", fcitx input method selection box pop ups (instead of Ctrl+space). I can select "mozc" and it works (I get japanese characters). 
The problem is in the input method selection, I can't choose a plain keyboard. French and US keyboards are marked as unavailable even though I can type with my French keyboard.

Maybe I am missing a dbus service but I don't know which. For more details you can see my post here (which has an fcitx-diagnose run):
https://groups.google.com/forum/#!forum/nix-devel

Regards

**Comment by teto** [comment]
No idea, I don't mind to do some local debugging/compilation work but any hint would be appreciated. if you need more details (screenshots etc) please ask

**Comment by wengxt** [comment]
oh, fcitx expect there is one rule file provided by xml. I suspect NixOS does not have it in its regular place.

**Comment by wengxt** [comment]
The file usually belongs to xkeyboard-config on regular distro.

You may first use "setxkbmap -print" to check the first line if it's evdev / base. And then, you can use "strace -f fcitx -D" to see which file fcitx is reading. (base.xml or evdev.xml).

And see if you can put the first to the right place, or use -DXKB_RULES_XML_FILE to hardcode a default one when compiling fcitx.

**Comment by teto** [comment]
thanks for the pointer that helps a lot !!
I indeed needed to install xkeyboard_config to get the evdev.xml file.
Now I am trying to change the fcitx package to correctly set the XKB_RULES_XML_FILE define.
It can apparently be overriden in config.h.in:
`#cmakedefine XKB_RULES_XML_FILE "${XKB_RULES_XML_FILE}"`
 but even when I add
`-DXKB_RULES_XML_FILE=" "${super.xkeyboard_config}/share/X11/xkb/rules/evdev.xml";`
to the cmakeFlags, it doesn't seem to be taken into account and keep using /usr/share/X11/xkb/rules/evdev.xml . If I trust cmake doc, https://cmake.org/cmake/help/latest/command/configure_file.html , there would need to be an `option(XKB_RULES_XML_FILE "path to evdev.xml" ON)` to take my override into account. Am I wrong or is it an omission ?


https://cmake.org/cmake/help/latest/command/configure_file.html

**Comment by teto** [comment]
My bad cmake does seem to take my override into account. Yet my XKB_RULES_XML_FILE is not used it seems :s I will do some more debugging to understand where the problem comes from.

**Comment by teto** [comment]
It seems that my XKB_RULES_XML_FILE was correctly defined but not used because it is ignored (in src/module/xkb/xkb.c) if `char *rulesName = FcitxXkbGetRulesName(xkb);` succeeds. I replaced the     `if (rulesName) {` with `if (0) {` and the problem goes away.
Now I would like to properly fix it. What does FcitxXkbGetRulesName get ? 
I guess the part `guess X11 data base directory.` will be tough for fcitx. So either I should patch the library responsible for XkbRF_GetNamesProp or we should improve the guess mechanism so that it can rely on XKB_RULES_XML_FILE (or a new XKB_RULES_XML_FOLDER). I understand that nixos is kinda of an edge case so let me know about what you think is best.

**Comment by wengxt** [comment]
Normally , XkbRF_GetNamesProp would just returns a string like evdev  / base . The "guess" code is probably outdated.

This would be the right way do it. If it doesn't help, you should ask for the solution on nix..

**Comment by teto** [comment]
it's a very helpful fix thanks.

**Comment by teto** [comment]
Here is the current nixos PR https://github.com/NixOS/nixpkgs/pull/29558. As said in that PR, I haven't been able to fully test it (yet).
