### ISSUE TITLE
gvim is still in blacklist?

### ISSUE THREAD

**Issue by mattn** [fcitx/fcitx#364]
gvim was fixed to use over-the-spot in [patch 8.0.1114](https://github.com/vim/vim/commit/4cf56bbc85f77846aeb378cfb071677336dfad6d). So I think there is not reason to add gvim into blacklist. Could you please remove it? (if still in blacklist)

**Comment by wengxt** [comment]
No, definitely not still for now.

Test with fcitx 5 today, vim would simply memory leak and create infinite input context:

Group [x11::0] has 18 InputContext(s)
  IC [b405f83940ac4aa5a18d3bb1dfb25b01] program:gvim frontend:dbus cap:6000000012 focus:0
  IC [36a6fa5b809948dfae74726e0e737c32] program:gvim frontend:dbus cap:6000000012 focus:0
  IC [f556bd6b912c48f9bbf85d3909cfb381] program:gvim frontend:dbus cap:6000000012 focus:0
  IC [99210f14933e4c048338c4ea596c4b48] program:firefox frontend:dbus cap:6000000012 focus:0
  IC [d8572f07562741ebb49a9f23660fb107] program:plasmashell frontend:dbus cap:6000800072 focus:0
  IC [9a1f7e7993a14183a9a29002150595d5] program:konsole frontend:dbus cap:6000800072 focus:1
  IC [87affd3ef4e04a1e8ebf070542212684] program:firefox frontend:dbus cap:6000000052 focus:0
  IC [b809a59185894d05b7f27355654b5040] program:kwin_x11 frontend:dbus cap:6000800072 focus:0
  IC [40db8ee9292546b0ba87f0216f16636e] program:krunner frontend:dbus cap:6000800072 focus:0
  IC [359029a0cc074267a15097d8f6a8f2fe] program:firefox frontend:dbus cap:6000000012 focus:0
  IC [adc0dee17ef14a2bb9dc5a79934b5451] program:firefox frontend:dbus cap:6000000012 focus:0
  IC [f6ca3b81090d4697864377f6fce396c0] program:firefox frontend:dbus cap:6000000012 focus:0
  IC [2c05c0e6e9a747baa1284aaaeb91619a] program:plasmashell frontend:dbus cap:6000800072 focus:0
  IC [1cec0cf546d040199daf4d4ca53b28e8] program:gvim frontend:dbus cap:6000000012 focus:0
  IC [b05b6e3524db4143b96224dfae1a5d1d] program:plasmashell frontend:dbus cap:6000800072 focus:0
  IC [7fdb4765506040289519e35a587cfb4d] program:gvim frontend:dbus cap:6000000012 focus:0
