### ISSUE TITLE
CentOS 7 系统更新后，无法在系统的文件管理器，以及 atom 中使用 fcitx

### ISSUE THREAD

**Issue by fenghou1st** [fcitx/fcitx#368]
症状是输入法切换不了，不论使用快捷键，还是点击状态栏图标。
但是在 Firefox 和 Chrome 里就能正常切换，也能正常输入中文。

通过 fcitx-diagnose 也查看不出什么症状，一切结果和更新系统之前没有什么不同。

OS: CentOS Linux release 7.4.1708 (Core)
Kernel: Linux 3.10.0-693.2.2.el7.x86_64
fcitx: 4.2.9.2

**Comment by wengxt** [comment]
firefox 可能和 chrome 都是 gtk2？…

https://fcitx-im.org/wiki/Note_for_GNOME_Later_than_3.6 ？

**Comment by fenghou1st** [comment]
谢谢 @wengxt 这么快给出建议！
之前都没意识到是 GNOME 更新后导致的问题，于是我把之前安装时要执行的修改系统配置的命令都执行了一遍，重启了机器后，在 atom 中就可以切换输入法了。
再次感谢！
现在就只剩下系统的文件管理器中无法切换了，有了头绪之后就好办了，我再去找找 GNOME 方面的消息。

**Comment by fenghou1st** [comment]
最新进展： 其实使用了 @wengxt 链接中提到的命令
```
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'fcitx'>}"
```
就可以在文件管理器中切换输入法了，不过有一点小问题：打开文件管理器后，第一次打开搜索框无法切换输入法，要等搜索框关闭后再开，或者失去焦点后再得到焦点，此时再切换才能生效。

**Comment by wengxt** [comment]
你最后说的是那个是 gnome 很久以前就有的文件管理器自己的 bug，请回报给 gnome。
