### ISSUE TITLE
Where to get support?

### ISSUE THREAD

**Issue by rlue** [fcitx/fcitx#374]
It's hard to find support for fcitx, apart from the wiki. I noticed in issue #277 that @wengxt directed a question to the mailing list (fcitx@googlegroups.com). 

Would the team be alright with mentioning the mailing list either in the README or on the wiki?

I'd be happy to help with any English documentation, once I understand how fcitx works a little better.

**Comment by rlue** [comment]
I just tried to send an email to fcitx@googlegroups.com, and received this response:

> Hello hello@ryanlue.com,
> 
> We're writing to let you know that the group you tried to contact (fcitx) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
> * You might have spelled or formatted the group name incorrectly.
> * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
> * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.
> 
> Thanks,
> 
> Google Groups

**Comment by wengxt** [comment]
Try send empty email to fcitx+subscribe@googlegroups.com

I thought the old behavior is anyone can post but need moderate.. not sure when this changed..

**Comment by rlue** [comment]
Unfortunately, I've subscribed and I still can't post new messages to the group. Any ideas?

**Comment by rlue** [comment]
Whoops! It took a couple tries to sign up successfully, but I've finally got a message submitted and awaiting moderation. (Actually, I think I accidentally submitted it twice.)

@wengxt, would you be open to putting a reference to the Google Group either in the README or on the wiki? Where do you think would be more appropriate?
