### ISSUE TITLE
Can`t use fcitx input method in flatpak app

### ISSUE THREAD

**Issue by michaeldyl520** [fcitx/fcitx#384]
How to resolve this problem? Thanks.

**Comment by wengxt** [comment]
Hi, I recently ask flatpak to include fcitx im module, it's already merged upstream in both freedesktop sdk and kde flatpak, but the runtime may not be updated so soon. If you need them right now you'll probably need to build your own version.

Also, you'll need at least fcitx 4.2.9.5 to work with them.

**Comment by wengxt** [comment]
FYI:

https://github.com/flatpak/freedesktop-sdk-images/pull/58

https://phabricator.kde.org/D8739
