### ISSUE TITLE
build: ability to override downloaded files

### ISSUE THREAD

**Issue by teto** [fcitx/fcitx#390]
I am trying to compile fcitx from source from nixos sandboxed mode (i.e., without internet access once the source is downloaded). So I download in advance the dicts and table.tar.gz and would like the build system to refer to those local files instead. Is there an easy way to do this with  the current build system ?
like for instance override  SPELL_EN_DICT_URL, TABLE_URL ?

**Comment by wengxt** [comment]
you should use the tarball with  _dict in filename. If you’re compiling
from git clone, you may put the data file in the right place so cmake will
not try to download them.

**Comment by teto** [comment]
I had guessed that there was a technique since the tarball included the dicts. I just found the solution and that fixed it thank you very much !
