### ISSUE TITLE
cmake通过依赖检查，但是make时报错

### ISSUE THREAD

**Issue by ellicefix** [fcitx/fcitx#391]
$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/share
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") 
-- Found DOXYFILE_IN: /home/fen/Documents/1/fcitx/Doxyfile.in  
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for dgettext
-- Looking for dgettext - found
-- Found Libintl: /usr/include  
-- Looking for iconv_open
-- Looking for iconv_open - found
-- Performing Test ICONV_HAVE_WERROR
-- Performing Test ICONV_HAVE_WERROR - Success
-- Performing Test LIBICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test LIBICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Libiconv: /usr/local/include  
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Found Pthread: /usr/include  
-- Looking for backtrace
-- Looking for backtrace - found
-- Found LibExecinfo: /usr/include  
-- Could NOT find GettextPo (missing:  GETTEXTPO_LIBRARIES GETTEXTPO_INCLUDE_DIR) 
-- Found XKBCommon_XKBCommon: /usr/lib/x86_64-linux-gnu/libxkbcommon.so (found version "0.7.1") 
-- Found XKBCommon: /usr/lib/x86_64-linux-gnu/libxkbcommon.so (found suitable version "0.7.1", minimum required is "0.5.0") found components:  XKBCommon 
-- Checking for module 'enchant'
--   Found enchant, version 1.6.0
-- Performing Test ENCHANT_HAVE_WERROR
-- Performing Test ENCHANT_HAVE_WERROR - Success
-- Performing Test ENCHANT_API_COMPATIBLE
-- Performing Test ENCHANT_API_COMPATIBLE - Success
-- Found Enchant: /usr/lib/x86_64-linux-gnu/libenchant.so  
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.4") 
-- Checking for module 'iso-codes'
--   Found iso-codes, version 3.75
-- Found IsoCodes: /usr/share/xml/iso-codes/iso_639.xml  
-- Checking for module 'xkbfile'
--   Found xkbfile, version 1.0.9
-- Found XkbFile: /usr/lib/x86_64-linux-gnu/libxkbfile.so  
-- Performing Test PRESAGE_HAVE_WERROR
-- Performing Test PRESAGE_HAVE_WERROR - Success
-- Performing Test PRESAGE_API_COMPATIBLE
-- Performing Test PRESAGE_API_COMPATIBLE - Success
-- Found Presage: /usr/lib/x86_64-linux-gnu/libpresage.so  
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found suitable version "4.8.7", minimum required is "4.8") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found XKeyboardConfig: /usr/share/X11/xkb (found version "2.19") 
-- Checking for module 'cairo-xlib>=1.0'
--   Found cairo-xlib, version 1.14.10
-- Checking for module 'pangocairo>=1.0'
--   Found pangocairo, version 1.40.4
-- Checking for module 'dbus-1>=1.1.0'
--   Found dbus-1, version 1.10.20
-- Checking for module 'opencc'
--   Found opencc, version 1.0.4
-- Performing Test OPENCC_HAVE_WERROR
-- Performing Test OPENCC_HAVE_WERROR - Success
-- Performing Test OPENCC_API_COMPATIBLE
-- Performing Test OPENCC_API_COMPATIBLE - Success
-- Found OpenCC: /usr/lib/x86_64-linux-gnu/libopencc.so  
-- Checking for module 'gio-2.0>=2.26'
--   Found gio-2.0, version 2.53.4
-- Checking for module 'gobject-introspection-1.0'
--   Found gobject-introspection-1.0, version 1.50.0
-- Adding Fcitx Addon x11
-- Adding Fcitx Addon xkb
-- Adding Fcitx Addon xkbdbus
-- Adding Fcitx Addon chttrans
-- Adding Fcitx Addon punc
-- Adding Fcitx Addon spell
-- Adding Fcitx Addon pinyin-enhance
-- Adding Fcitx Addon quickphrase
-- Adding Fcitx Addon autoeng
-- Adding Fcitx Addon fullwidth-char
-- Adding Fcitx Addon remote-module
-- Adding Fcitx Addon imselector
-- Adding Fcitx Addon clipboard
-- Adding Fcitx Addon vk
-- Adding Fcitx Addon dbus
-- Adding Fcitx Addon lua
-- Adding Fcitx Addon unicode
-- Adding Fcitx Addon freedesktop-notify
-- Adding Fcitx Addon notificationitem
-- Adding Fcitx Addon pinyin
-- Adding Fcitx Addon keyboard
-- Adding Fcitx Addon table
-- Adding Fcitx Addon qw
-- Adding Fcitx Addon xim
-- Adding Fcitx Addon ipc
-- Checking for module 'uuid'
--   Found uuid, version 2.29.2
-- Adding Fcitx Addon ipcportal
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.53.4
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.31
-- Adding Fcitx Addon classic-ui
-- Adding Fcitx Addon kimpanel-ui
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fen/Documents/1/fcitx/build
fen@i5:~/Documents/1/fcitx/build$ make
Scanning dependencies of target fcitx-addon-fcitx-kimpanel-ui--headers-1
[  0%] Built target fcitx-addon-fcitx-kimpanel-ui--headers-1
Scanning dependencies of target fcitx-utils
[  0%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/utf8.c.o
[  1%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/utils.c.o
[  1%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/log.c.o
[  1%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/qsort_r.c.o
[  2%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/msort_r.c.o
[  2%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/memory.c.o
[  2%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/handler-table.c.o
[  2%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/objpool.c.o
[  3%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/desktop-parse.c.o
[  3%] Building C object src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/stringmap.c.o
[  3%] Linking C shared library libfcitx-utils.so
CMakeFiles/fcitx-utils.dir/log.c.o：在函数‘FcitxLogFuncV’中：
log.c:(.text+0x2ea)：对‘libiconv_open’未定义的引用
log.c:(.text+0x393)：对‘libiconv’未定义的引用
collect2: error: ld returned 1 exit status
src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/build.make:328: recipe for target 'src/lib/fcitx-utils/libfcitx-utils.so.0.1' failed
make[2]: *** [src/lib/fcitx-utils/libfcitx-utils.so.0.1] Error 1
CMakeFiles/Makefile2:803: recipe for target 'src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/all' failed
make[1]: *** [src/lib/fcitx-utils/CMakeFiles/fcitx-utils.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ellicefix** [comment]
依赖正常的情况下，make怎么会报错呢？
报错的信息似乎指向log.c，请求指点。

**Comment by wengxt** [comment]
你是bsd？

**Comment by ellicefix** [comment]
这是debian，发行版是deepin linux，报错的信息，这个问题我排查了3天啦，没有头绪。

**Comment by ellicefix** [comment]
啊，原来是作者大大的回复，请求指点

**Comment by wengxt** [comment]
这个，你的 include 里面装了什么奇怪的 iconv 吗？
glibc 里面应该是自带 iconv 的，而且不应该叫 libiconv_open，看起来你是include 了一个什么非 libc 的 iconv.h 才出现这样的问题的

类似这个问题：http://tonybai.com/2013/04/25/a-libiconv-linkage-problem/

**Comment by ellicefix** [comment]
泪流满面，原来是我以前编译的GNU LIBICONV在作怪，把它删掉之后，fcitx主程序编译通过了，这真是痛苦的教训。

大大，我尝试编译 fcitx-rime，可是依然检查依赖通过，而make受阻，您能再指点一下吗？fcitx-rime在诸多发行版里，都是4年前的版本，那时的rime组件——librime是有bug的，会造成五笔用户困扰。请您指点 一下，下面又是哪个依赖出了问题？


$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/share
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'fcitx'
--   No package 'fcitx' found
-- Checking for module 'fcitx-config'
--   No package 'fcitx-config' found
-- Checking for module 'fcitx-utils'
--   No package 'fcitx-utils' found
-- fcitx4-config found /usr/share/bin/fcitx4-config
-- Found Fcitx: 4.2.9.5 (Required is at least version "4.2.8.1") 
-- Checking for module 'rime>=1.0.0'
--   Found rime, version 1.2.9
-- Found Brise: /usr/share/rime-data  
-- Precompiler macro RIME_DATA_DIR is set to "/usr/share/rime-data"
-- Adding Fcitx Addon rime
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fen/Documents/1/fcitx-rime-0.3.2/build
fen@i5:~/Documents/1/fcitx-rime-0.3.2/build$ make
Scanning dependencies of target fcitx-addon-fcitx-rime--headers-1
[  0%] Built target fcitx-addon-fcitx-rime--headers-1
Scanning dependencies of target fcitx-scan-addons.target
[  0%] Built target fcitx-scan-addons.target
Scanning dependencies of target fcitx-rime
[ 25%] Building C object src/CMakeFiles/fcitx-rime.dir/fcitx-rime.c.o
/home/fen/Documents/1/fcitx-rime-0.3.2/src/fcitx-rime.c:1:28: fatal error: fcitx/instance.h: 没有那个文件或目录
 #include <fcitx/instance.h>
                            ^
compilation terminated.
src/CMakeFiles/fcitx-rime.dir/build.make:62: recipe for target 'src/CMakeFiles/fcitx-rime.dir/fcitx-rime.c.o' failed
make[2]: *** [src/CMakeFiles/fcitx-rime.dir/fcitx-rime.c.o] Error 1
CMakeFiles/Makefile2:706: recipe for target 'src/CMakeFiles/fcitx-rime.dir/all' failed
make[1]: *** [src/CMakeFiles/fcitx-rime.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wengxt** [comment]
看看这个：https://fcitx-im.org/wiki/Compile_from_source#Use_non_standard_path_to_install

另外你的 prefix 设置成 /usr/share 了？…

**Comment by wengxt** [comment]
话说 debian 源里面有 fcitx，为什么要自己编译？

**Comment by ellicefix** [comment]
fcitx-rime受到 librime 的影响，有个严重的bug，『四码唯一自动上屏』的功能无法正常使用，必须要在
 rime 的码表里特别添加『开启逐渐提示』的参数，才能用五笔，非常别扭。

Librime 升级，消除了这个bug。我尝试在 fcitx-rime 上替成较新的 Librime组件，但是不能正常工作。就试着编译 fcitx-rime 了。

谢谢您的提示，我再细看一下。

[rime的bug之一](http://tieba.baidu.com/p/4054640112?pid=76095703837&cid=0#76095703837)
