### ISSUE TITLE
chrome及chromium内核所有浏览器在HiDPI下定位不准

### ISSUE THREAD

**Issue by ellicefix** [fcitx/fcitx#393]
近几个月以来，chrome 以及所有使用 chromium 内核的开源浏览器（ chromium & opera & vivaldi ），在高分屏（ 比如4K ）下放大2倍使用时，都有输入法定位不准的问题。

据小小输入法作者周永讲，这是 chrome 使用了与别的应用程序不同的输入区反馈逻辑造成的。

http://yong.dgod.net/read.php?tid=3606&fid=2&page=1

同样的反馈，在这里还看到这个： 

https://github.com/fcitx/fcitx/issues/351

Google 大概不会修复这个问题了， KDE 似乎还特别为之做了修正。

希望大大可以参考周永的做法，给 fcitx 打个补丁。

**Comment by wengxt** [comment]
会修正的吧我回报给chrome了

**Comment by wengxt** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=774974#c9

**Comment by ellicefix** [comment]
大大您在啊？

无论是安装fcitx-rime源里的最新版，还是手动编译加入开发版的librime引擎，都有四码唯一自动上屏的bug，请您查证一下：

fcitx-rime

https://github.com/fcitx/fcitx-rime/issues/39

**Comment by wengxt** [comment]
我不会给fcitx打的，在不同版本的chrome下有些修复了有些没有，几年前我就有回报这个问题了。
不可能从fcitx判断chrome的版本来hack。

我可以给你概括一下，比较老的gtk2的chrome没修复，5x的某个版本的gtk2的好了。之后换到gtk3之后又出了新问题，就是上面的链接。我没法判断chrome是否真的修复了。请等上游修复。

**Comment by ellicefix** [comment]
好的，谢谢说明。我是近几个月发现的，反正用五笔，看不看候选窗，干扰不大，可能拼音用户会比较痛苦，哈哈。

**Comment by ljhui** [comment]
我也发现这种情况，找到这里来了，不知什么时候能修复？每次输入候选框都跑到右下角去了

**Comment by chyelang** [comment]
同样期待该问题的修复
