### ISSUE TITLE
st终端中一些问题

### ISSUE THREAD

**Issue by yadex** [fcitx/fcitx#397]
st终端（https://st.suckless.org）非常省资源，对字体支持比urxvt好，但是偏偏对fcitx支持不好，快捷键有冲突，选择框靠下。这一点，反倒是urxvt更好。
![_ _20180129221951](https://user-images.githubusercontent.com/20081672/35515392-fe9e3b04-0543-11e8-8d3f-2625e76e5b7b.png)

**Comment by yuyichao** [comment]
快捷键冲突这个得自己改吧....

选字窗口位置是终端的问题不是 fcitx 的问题

**Comment by yadex** [comment]
看来urxvt还不能删

**Comment by wengxt** [comment]
输入框位置是他们自己支持不好。和 fcitx 无关。
