### ISSUE TITLE
gnome-shell 无法切换皮肤

### ISSUE THREAD

**Issue by amitbha** [fcitx/fcitx#400]
gnome-shell：3.26.2
fcitx：4.2.9.5
gnome-shell-extension-kimpanel：20171209-2

托盘菜单里找不到切换皮肤的地方，配置文件里也不知道怎么配置皮肤。

**Comment by wengxt** [comment]
设计如此，用kimpanel的时候就没皮肤。

**Comment by amitbha** [comment]
我去，把 gnome-shell-extension-kimpanel 卸载掉就可以了
世间安得双全法，不负如来不负卿。
