### ISSUE TITLE
fedora 27 tiny UI interface and font under highdpi

### ISSUE THREAD

**Issue by ljhui** [fcitx/fcitx#404]
最近从fedora 26 升级到 fedora 27,fedora 26时还可以，候选框大小正常，右键选项大小也正常，除了托盘图标一直非常小外，在Highdpi下表现正常，但feodra 27下fcitx对highdpi显示不正常，除了一直未修复的托盘图标外，界面和字体都非常小
![screenshot from 2018-03-06 11-15-35](https://user-images.githubusercontent.com/16174049/37013032-b079eab2-2132-11e8-9c9e-0eff29b1b3fa.png)
但是选择restart,界面和字体就会恢复正常，和fedora 26表现一样了
![screenshot from 2018-03-06 11-16-18](https://user-images.githubusercontent.com/16174049/37013042-bcac1d28-2132-11e8-9196-d6076f58a7b1.png)
但是每次启动fedora,再次重启一下让fcitx适应highdpi,挺麻烦的，怎么解决这个bug?

**Comment by wengxt** [comment]
… fcitx 怎么启动太早在启动之后 Xft.dpi 变了吧，配置里面暂时加一下延迟启动？

**Comment by ljhui** [comment]
谢谢，修改sceonds sleep before fcitx really start 为10s成功解决了问题！
