### ISSUE TITLE
Fcitx Frontend 解除强制依赖 on Ubuntu 18.04

### ISSUE THREAD

**Issue by ghostplant** [fcitx/fcitx#406]
环境：系统缺省gtk3桌面环境，没有其他qt5/qt4/gtk2的应用；
fcitx最新版本貌似需要全部安装fcitx-frontend-*才能比较正常的使用，但问题是需要强制安装大量不必要的依赖，例如：
fcitx-frontend-gtk2 需要强制安装 libgtk2.0-0, libgtk2.0-common （包含了gtk2应用的各种资源）；
fcitx-frontend-qt5 需要强制安装libqt5coreXXX, gt5guiXX, qt5xxx（包含了qt5 应用的各种资源）；

能否在Ubuntu18.04上对 fcitx-frontend-gtk2, fcitx-frontend-qt5 等库解除非平台“强制”资源依赖？因为这些库在真正有gtk2/qt5应用安装时通过依赖约束自然就会被安装，毕竟很多时候平台根本不需要这些资源运行库，而有需要完整安装fcitx组件以保证环境配置正常。

Ubuntu很多软件包已经逐渐解除了gtk2等运行库的“强制”依赖，例如：gtk2-engines-murrine等。

**Comment by wengxt** [comment]
打包问题不归我们管，请汇报给ubuntu上游。选报给 im-config 包。
