### ISSUE TITLE
双击直接打开的文件无法使用 Fcitx 输入

### ISSUE THREAD

**Issue by Zangwill** [fcitx/fcitx#407]
以打开一个 `txt` 文件编辑为例：

1. 直接双击，无论设置默认打开的软件是 `leafpad`、`mousepad`、`Sublime text` 还是 `VSCode`，都无法使用 `fcitx`；
2. 先用右键点击，在`打开方式`中使用“用XXX打开”，也无法输入；
3. 先打开编辑软件，再在软件中打开文件编辑，可以输入；
4. 命令行用 `xdg-open txt` 命令打开，可以输入。

请问如何解决，不能直接打开编辑很麻烦。 

补充：桌面是 Xfce4。

**Comment by wengxt** [comment]
配置问题吧。把环境变量设置在shell能起作用但是没有对桌面起作用的地方。

**Comment by Zangwill** [comment]
@wengxt，谢谢，以前一直能用所以没想到是环境变量的问题，在 `/etc/profile` 里面添加了那三行就好了：
```bash
su
cat << EOF >> /etc/profile
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
EOF
```

**Comment by Zangwill** [comment]
@wengxt，首先，设置了环境变量，在 `/etc/profile` 里面添加了下面三行，但是双击打开的文件仍然不能输入，之前右键中的"用 xxx 打开"可以输入但是现在又不行了，想不通这是什么问题导致的。
```bash
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
```
这是录屏：
<https://img.vim-cn.com/c1/581ad4c8858ec829b50caf3cc864ac8b074512.gif>

**Comment by SosirisTseng** [comment]
@Zangwill Would you like to close this issue after the problem is resolved?
