### ISSUE TITLE
Clicking on fcitx applet hangs Ubuntu MATE

### ISSUE THREAD

**Issue by alkisg** [fcitx/fcitx#411]
Method to reproduce in 1 minute:
1) Download the Ubuntu MATE 18.04 live CD.
2) Press space while booting to display the syslinux language menu. Select Ελληνικά (Greek) in order for fcitx to autorun. I guess the same will happen in other languages too.
3) Select Δοκιμάστε το Ubuntu MATE χωρίς εγκατάσταση (Try Ubuntu MATE without installing).
4) When the live session becomes available, the following applets show:
en [keyboard icon] ...
At that point, clicking on the keyboard icon causes no issues.
5) Open anything that displays a cursor, e.g. a terminal. Now the following applets show:
en [keyboard icon] us
It is a bug that the language is shown twice. But the main problem now is that if one clicks at the keyboard icon, an unpopulated (hanged) menu shows up, and the keyboard/mouse no longer work; no interaction with the desktop is possible.
6) If one presses Alt+Ctrl+F2 to switch to vt2, logs in with ubuntu-mate and empty pass, and types `killall fcitx`, and then presses Alt+Ctrl+F7 to switch back to vt7, the UI is unfrozen and works properly.

![Hanged menu screenshot](https://launchpadlibrarian.net/367837136/VirtualBox_bionic-mate-sch64_29_04_2018_11_07_26.png "Hanged menu screenshot")

I also reported this in [launchpad](https://bugs.launchpad.net/ubuntu/+source/fcitx/+bug/1767765).

**Comment by wengxt** [comment]
Already fixed by https://github.com/fcitx/fcitx/commit/a3432fcb2d9d45f8702d811d7017ba6c0d7367dd
