### ISSUE TITLE
关于图标的问题

### ISSUE THREAD

**Issue by AlephAlpha** [fcitx/fcitx#414]
我现在用的图标主题（[papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme)）包含了一个 fcitx 的图标。于是出现了奇怪的问题：所有 fcitx 开头的图标，包括输入法的图标、全角半角的图标等，都显示成了 fcitx 的图标的样子：

![截图](https://user-images.githubusercontent.com/3600593/39957678-7db8b7a8-5629-11e8-91e3-698d380c8c2d.png)

之前用的另一个图标主题（[Evolvere-Icons](https://github.com/franksouza183/Evolvere-Icons)）也有同样的问题。

不知道是图标主题的问题还是 fcitx 的问题。我用的操作系统是 Linux Mint 18.3，桌面环境是 xfce。

**Comment by wengxt** [comment]
这个算是 xdg 标准的问题，如果图标 a-b 找不到就会使用同主题的 a。姑且是这么规定的……
所以 fcitx-pinyin 找不到会 fallback 到同主题的 fcitx 而不是 hicolor  的 fcitx-pinyin ……比较意料之外。
意思就是在目前的命名方式下，你要做就要做全套的图标（或者 symlink 一下 hicolor？）。
