### ISSUE TITLE
火狐浏览器中打字fcitx死了

### ISSUE THREAD

**Issue by yiifburj** [fcitx/fcitx#423]
非必现，但是刚才在这里打字连续死了两次。其他地方会不会死还不确定。

我用的是fcitx-sunpinyin

uname -a
Linux yiifburj-Aspire-V3-371 5.0.0-36-generic #39-Ubuntu SMP Tue Nov 12 09:46:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[crash.log](https://github.com/fcitx/fcitx/files/3907683/crash.log)

fcitx-diagnose > diagnose.txt

[diagnose.txt](https://github.com/fcitx/fcitx/files/3907682/diagnose.txt)

**Comment by wengxt** [comment]
cloudpinyin 的 bug，在最新的 cloudpinyin 里修复了。
