### ISSUE TITLE
Crash when enable Baidu in Cloud Pinyin

### ISSUE THREAD

**Issue by suokunlong** [fcitx/fcitx#424]
In a fresh openSUSE Tumbleweed install, when I enable Baidu in the Cloud Pinyin plugin, fcitx crashes.

Steps to Reproduce:
1. Enable Baidu in the Cloud Pinyin plugin.
2. Type some Chinese chars in any input area.
--> Crash.

The crash log is:
=========================
FCITX 4.2.9.5 -- Get Signal No.: 11
Date: try "date -d @1575209395" if you are using GNU date ***
ProcessID: 4751
fcitx(+0x1978)[0x55961b8b7978]
/lib64/libc.so.6(+0x3c150)[0x7f9a3ef77150]
/lib64/libc.so.6(+0xa7e6d)[0x7f9a3efe2e6d]
/usr/lib64/fcitx/fcitx-cloudpinyin.so(+0x9422)[0x7f9a3e0c8422]
/usr/lib64/fcitx/fcitx-cloudpinyin.so(+0x59a0)[0x7f9a3e0c49a0]
/usr/lib64/fcitx/fcitx-cloudpinyin.so(+0x4ff1)[0x7f9a3e0c3ff1]
/usr/lib64/libfcitx-core.so.0(+0x1b3ea)[0x7f9a3f1743ea]
/usr/lib64/libfcitx-core.so.0(FcitxInstanceRun+0x57)[0x7f9a3f174e97]
fcitx(+0x132e)[0x55961b8b732e]
/lib64/libc.so.6(__libc_start_main+0xeb)[0x7f9a3ef61e0b]
fcitx(_start+0x2a)[0x55961b8b73fa]

If further debug is needed to fix this issue, please advice me how to use the debug symbols so that I can try.

**Comment by wengxt** [comment]
Fixed in cloudpinyin 0.3.7
