### ISSUE TITLE
PrevPageKey and NextPageKey do not work as expected

### ISSUE THREAD

**Issue by 372046933** [fcitx/fcitx#429]
With the folloing versions and settings, `-` does not go to previous page and `+` does not go to next. But `,` and `.` work
```
fcitx 4.2.9.7-1
fcitx-cloudpinyin 0.3.7-1
fcitx-gtk3 4.2.9.7-1
fcitx-qt5 1.2.4-1
kcm-fcitx 0.5.5-2
```
Part of `~/.config/fcitx/config`
```
# Prev Page
PrevPageKey=UP , -
# Next Page
NextPageKey=DOWN . =
```

**Comment by wengxt** [comment]
it's expected behavior. only 2 different keys are supported in fcitx 4.

**Comment by 372046933** [comment]
Hahaha, Thank you!
