### ISSUE TITLE
fcitx-rime在高分屏下开机字体极小，只有重新启动输入法字体大小才正常

### ISSUE THREAD

**Issue by thep0y** [fcitx/fcitx#435]
Linux Mint 19.3和Ubuntu18.04都是如此，字体小得可怜，后来才发现重新启动输入法后显示正常。
每次开机都要重启输入法有些麻烦， 该如何解决？

**Comment by baraja** [comment]
顶，期待解决

**Comment by chenzhiwei** [comment]
请问你们两个解决这个问题了吗？

如果一直没解决方法的话，我可能会考虑使用 ibus 了。

**Comment by wengxt** [comment]
配置里有个延迟启动设置一下 workaround

**Comment by chenzhiwei** [comment]
多谢！

延迟5秒启动解决了这个问题。
