### ISSUE TITLE
libexecinfo dependency - is it hardcoded?

### ISSUE THREAD

**Issue by jmokuzai** [fcitx/fcitx#436]
Hi,

I was building fcitx on gentoo musl and failed with the following error: 

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBEXECINFO_INCLUDE_DIR (ADVANCED)

After some digging, I found this [link](https://www.mail-archive.com/search?l=gentoo-dev@lists.gentoo.org&q=subject:%22%5C%5Bgentoo%5C-dev%5C%5D+Last+rites%5C%3A+dev%5C-libs%5C%2Flibexecinfo%2C+net%5C-analyzer%5C%2Fbsnmp%2C+sys%5C-apps%5C%2Fflock%2C+sys%5C-auth%5C%2Fopenpam%2C+sys%5C-block%5C%2Feject%5C-bsd%2C+sys%5C-process%5C%2Fpidof%5C-bsd%22&o=newest) on gentoo dev, which is relatively recent, so libexecinfo is gone, how do I stop fcitx from looking for it?

Thanks

**Comment by wengxt** [comment]
-DENABLE_BACKTRACE=Off
