### ISSUE TITLE
Fcitx Mozc does not work with Discord

### ISSUE THREAD

**Issue by miss-looptux** [fcitx/fcitx#440]
Hello, When I was trying to type on discord on Japanese with mozc on fcitx,
It dosen't show in hiragana/katakana when I type in discord. Fortunately it only happens on discord and not elsewhere.

Specs:
kernel = 5.5.9-arch1-2
OS: Arch Linux
Fcitx version: latest i presume?

Thanks if you can help.

**Comment by miss-looptux** [comment]
I don't know if it's related to discord itself or fcitx.

**Comment by wengxt** [comment]
is this a web page in browser? or some standalone app?

**Comment by miss-looptux** [comment]
It is an app, not the webpage

**Comment by wengxt** [comment]
I tried the discord under archlinux and found no problem. So I'd close this.

Please refer to following page to check your configuration:
https://wiki.archlinux.org/index.php/fcitx
https://fcitx-im.org/wiki/Configure_(Other)

Most likely, you didn't configure fcitx gtk3 im module correctly.
