### ISSUE TITLE
Does not work with x11 forwarding over ssh

### ISSUE THREAD

**Issue by graywolf** [fcitx/fcitx#443]
I've tried to use this with x11 forwarding over ssh but did not manage to get it to work. Programs launched on the other end just did not register the input method. I did have

```
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```

set on both ends. I manage to work around this by using xim module, but I wonder if there is some configuration I was missing somewhere. Is is possible to get this working with fcitx module?

**Comment by wengxt** [comment]
you need to use xim if fcitx need to be run on the other side.
