### ISSUE TITLE
Failed to load fcitx-keyboard and fctix-xkbdbus

### ISSUE THREAD

**Issue by Samega7Cattac** [fcitx/fcitx#444]
# System Info:
1.  `uname -a`:

        Linux S7C-Arch 5.6.7-arch1-1 #1 SMP PREEMPT Thu, 23 Apr 2020 09:13:56 +0000 x86_64 GNU/Linux

2.  `lsb_release -a`:

        LSB Version:    1.4
        Distributor ID: Arch
        Description:    Arch Linux
        Release:        rolling
        Codename:       n/a

3.  `lsb_release -d`:

        Description:    Arch Linux

4.  `/etc/lsb-release`:

        LSB_VERSION=1.4
        DISTRIB_ID=Arch
        DISTRIB_RELEASE=rolling
        DISTRIB_DESCRIPTION="Arch Linux"

5.  `/etc/os-release`:

        NAME="Arch Linux"
        PRETTY_NAME="Arch Linux"
        ID=arch
        BUILD_ID=rolling
        ANSI_COLOR="0;36"
        HOME_URL="https://www.archlinux.org/"
        DOCUMENTATION_URL="https://wiki.archlinux.org/"
        SUPPORT_URL="https://bbs.archlinux.org/"
        BUG_REPORT_URL="https://bugs.archlinux.org/"
        LOGO=archlinux

6.  Desktop Environment:

    Desktop environment is `kde`.

7.  Bash Version:

        BASH_VERSION='5.0.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

2.  Keyboard Layout:

    1.  `setxkbmap`:

            xkb_keymap {
                xkb_keycodes  { include "evdev+aliases(qwerty)" };
                xkb_types     { include "complete"      };
                xkb_compat    { include "complete"      };
                xkb_symbols   { include "pc+jp+pt:2+inet(evdev)"        };
                xkb_geometry  { include "pc(pc101)"     };
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc101", "jp,pt", ",", ""

3.  Locale:

    1.  All locale:

            C
            en_US.utf8
            ja_JP
            ja_JP.eucjp
            ja_JP.ujis
            ja_JP.utf8
            japanese
            japanese.euc
            POSIX

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=en_US.UTF-8

4.  Directories:

    1.  Home:

            /home/samega7cattac

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is set to `/home/samega7cattac/.config`.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/samega7cattac/.config`).

    3.  Fcitx Settings Directory:

        Current fcitx settings directory is `~/.config/fcitx` (`/home/samega7cattac/.config/fcitx`).

5.  Current user:

    The script is run as samega7cattac (1000).

# Fcitx State:
1.  executable:

    Found fcitx at `/usr/bin/fcitx`.

2.  version:

    Fcitx version: `4.2.9.7`

3.  process:

    Found 2 fcitx processes:

           3732 fcitx
           3749 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx` is `:1.250`.

    PID of DBus name `org.fcitx.Fcitx` owner is `3732`.

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx-configtool at `/usr/bin/fcitx-configtool`.

2.  Config GUI for gtk2:

    **Config GUI for gtk2 not found.**

3.  Config GUI for gtk3:

    Found `fcitx-config-gtk3` at `/usr/bin/fcitx-config-gtk3`.

4.  Config GUI for kde:

    **`kcmshell4` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    Xim server name is the same with that set in the environment variable.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    Found fcitx im module for Qt5: `/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found unknown fcitx qt module: `/usr/lib/qt/plugins/kcm_fcitx.so`.
    Found fcitx qt module: `/usr/lib/fcitx/qt/libfcitx-quickphrase-editor5.so`.
    **Cannot find fcitx input method module for Qt4.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        Found `gtk-query-immodules` for gtk `2.24.32` at `/usr/bin/gtk-query-immodules-2.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.32

        Found fcitx im modules for gtk `2.24.32`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        Found `gtk-query-immodules` for gtk `2.24.32` at `/usr/bin/gtk-query-immodules-2.0-32`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.32

        **Failed to find fcitx in the output of `/usr/bin/gtk-query-immodules-2.0-32`**

    2.  gtk 3:

        Found `gtk-query-immodules` for gtk `3.24.20` at `/usr/bin/gtk-query-immodules-3.0`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.20

        Found fcitx im modules for gtk `3.24.20`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        Found `gtk-query-immodules` for gtk `3.24.18` at `/usr/bin/gtk-query-immodules-3.0-32`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.18

        **Failed to find fcitx in the output of `/usr/bin/gtk-query-immodules-3.0-32`**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.32` at `/usr/lib/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-2.0 from gtk+-2.24.32

        Found fcitx im modules for gtk `2.24.32`.

            "/usr/lib/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        Found immodules cache for gtk `2.24.32` at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by usr/bin/gtk-query-immodules-2.0-32 from gtk+-2.24.32

        **Failed to find fcitx in immodule cache at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.20` at `/usr/lib/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0 from gtk+-3.24.20

        Found fcitx im modules for gtk `3.24.20`.

            "/usr/lib/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

        Found immodules cache for gtk `3.24.18` at `/usr/lib32/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/bin/gtk-query-immodules-3.0-32 from gtk+-3.24.18

        **Failed to find fcitx in immodule cache at `/usr/lib32/gtk-3.0/3.0.0/immodules.cache`**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx addon config directory: `/usr/share/fcitx/addon`.

2.  Addon List:

    1.  Found 27 enabled addons:

            fcitx-autoeng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-imselector
            fcitx-ipc
            fcitx-ipcportal
            fcitx-keyboard
            fcitx-kimpanel-ui
            fcitx-mozc
            fcitx-notificationitem
            fcitx-pinyin
            fcitx-pinyin-enhance
            fcitx-punc
            fcitx-quickphrase
            fcitx-remote
            fcitx-spell
            fcitx-table
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  Found 1 disabled addons:

            fcitx-qw

3.  Addon Libraries:

    **Cannot find following required libraries for `fcitx-keyboard.so` of addon `fcitx-keyboard`.**

        libjson-c.so.5

    **Cannot find following required libraries for `fcitx-xkbdbus.so` of addon `fcitx-xkbdbus`.**

        libjson-c.so.5

4.  User Interface:

    Found 2 enabled user interface addons:

        fcitx-classic-ui
        fcitx-kimpanel-ui

## Input Methods:
1.  Found 2 enabled input methods:

        mozc
        fcitx-keyboard-pt

2.  Default input methods:

    **Your first (default) input method is mozc instead of a keyboard input method. You may have trouble deactivate fcitx.**

# Log:
1.  `date`:

        Wed 29 Apr 2020 01:30:04 AM WEST

2.  `~/.config/fcitx/log/`:

        total 4
        -rw-r--r-- 1 samega7cattac samega7cattac 44 Oct 10  2019 crash.log

3.  `~/.config/fcitx/log/crash.log`:

        fcitx: BadWindow (invalid Window parameter)

**Comment by Samega7Cattac** [comment]
`json-c` is installed

**Comment by wengxt** [comment]
sounds like your fcitx need rebuild. please check the so version.

**Comment by Samega7Cattac** [comment]
wdym it's all from official repos

**Comment by wengxt** [comment]
then probably you need to report to your distro.

**Comment by mnixry** [comment]
I found some way to fix this problem in #447 

soft link libjson

`sudo ln -s /usr/lib/libjson-c.so /usr/lib/libjson-c.so.5`

i think it‘s not a good way to fix it but it really works.
