### ISSUE TITLE
fcitx 英文键盘indicator反复切换

### ISSUE THREAD

**Issue by sudoyang** [fcitx/fcitx#445]
fcitx的英文键盘状态反复切换，很烦。

我用的是ubuntu的unity

附两个截图， 就是这两图标之间反复跳， 应该是系统检测到输入光标状态来决定图标的，我希望能固定用一个图标。

![Captured_20200428_23:59:29_001](https://user-images.githubusercontent.com/2531404/80559760-a0994180-89ac-11ea-9277-e822198c01a7.png)

![Captured_20200428_23:59:43_001](https://user-images.githubusercontent.com/2531404/80559765-a2630500-89ac-11ea-9024-81cb283bca87.png)

这里有个类似的问题
https://askubuntu.com/questions/1036516/unity-18-04-remove-language-selector-next-to-keyboard-icon

**Comment by wengxt** [comment]
this may helps: da3318ab1fc15189ecb2cb6b05071dba725d7f4a
otherwise there's nothing we can do about it because the right state need to be shown.
