### ISSUE TITLE
项目调试

### ISSUE THREAD

**Issue by ShawZG** [fcitx/fcitx#446]
您好，由于国内VPN最近很不稳定，没法在dev论坛里提问。只能在这问了，抱歉。

1. 请问下Addon里如何能把日志输出来？
我把守护进程注释了，CMake中的ENABLE_DEBUG设置为ON，从终端启动Fcitx，看不到src目录下代码的输出日志。

2. 再想请问下，Fcitx源码如何调试呢，用gdb，一会就卡住没有响应了。

ps：公司让处理一些输入法问题，只能硬着头皮上了。之后如果能解决问题，会把解决办法同步给您这。我的邮箱 blueshaw@163.com。如果您手上有Fcitx一些文档资料，是否能发一份给我学习下。现在对整个Fcitx如何实现输入法功能，还有点懵圈。

**Comment by wengxt** [comment]
调试的话最简单就是用一个禁用了输入法环境的终端

个人一般XMODIFIER=@im=none xterm开一个xterm然后gdb attach上去

我不知道你怎么输出的日志，但反正printf总可以的吧。

**Comment by ShawZG** [comment]
抱歉，又打扰了。
我在某个应用中想输入中文“新加坡”三个字，如果我每个字单独输入，xin可以输出中文“新”，但是输入“j”这个字母时，这个字母没有出现在输入法控件中，直接显示在编辑框中了。后续再输入“ia”时，又显示在输入法控件中了。

我打印出了ipc中IPCProcessKey处理的key，发现了一些问题。当我输入第一个“新”字后，无论是空格还是数字键选测候选字，IPCProcessKey中只空格只打印出key press消息，没有key release消息。字母“j”只有key release消息，没有key press消息。

原本我想寻这个问题，确认下是否发送dbus消息的地方是否有问题，为什么key的press和release消息没有对应发送出来。无奈我觉得有可能发送dbus的代码（frontend\qt, lib\fcitx-qt），我用printf，或是qdebug，或是FcitxLog都没法打印出来消息。目前我也没法确认这个dbus消息是谁发送过来的。

请问下
1. 这个ipc中的IPCProcessKey消息，是frontend\qt中QFcitxInputContext::x11FilterEvent发送出来的吗？
2. 目前的定位思路是否正确？如果不是，麻烦您指导一、二。

有问题的日志
数字键选中候选词
(DEBUG-83305 ipc.c:955) KeyRelease=0  state=0  KEYCODE=10  KEYSYM=49 OLDCHAR=1 NEWCHAR=1
(DEBUG-83305 ipc.c:914) ProcessKeyEvent IPCProcessKey return: 1
(DEBUG-83305 ipc.c:915) ProcessKeyEvent dbus_message_new_method_return return: 34687104
(DEBUG-83305 ipc.c:955) KeyRelease=1  state=0  KEYCODE=44  KEYSYM=106 OLDCHAR=j NEWCHAR=j
(DEBUG-83305 ipc.c:914) ProcessKeyEvent IPCProcessKey return: 0
(DEBUG-83305 ipc.c:915) ProcessKeyEvent dbus_message_new_method_return return: 23322464

空格选中默认词
(DEBUG-83305 ipc.c:955) KeyRelease=0  state=0  KEYCODE=65  KEYSYM=32 OLDCHAR=  NEWCHAR= 
(DEBUG-83305 ipc.c:914) ProcessKeyEvent IPCProcessKey return: 1
(DEBUG-83305 ipc.c:915) ProcessKeyEvent dbus_message_new_method_return return: 34690560
(DEBUG-83305 ipc.c:955) KeyRelease=1  state=0  KEYCODE=44  KEYSYM=106 OLDCHAR=j NEWCHAR=j
(DEBUG-83305 ipc.c:914) ProcessKeyEvent IPCProcessKey return: 0
(DEBUG-83305 ipc.c:915) ProcessKeyEvent dbus_message_new_method_return return: 34708848

正常日志
(DEBUG-83305 ipc.c:955) KeyRelease=0  state=0  KEYCODE=44  KEYSYM=106 OLDCHAR=j NEWCHAR=j
(DEBUG-83305 ipc.c:914) ProcessKeyEvent IPCProcessKey return: 1
(DEBUG-83305 ipc.c:915) ProcessKeyEvent dbus_message_new_method_return return: 34708880
(DEBUG-83305 ipc.c:955) KeyRelease=1  state=0  KEYCODE=44  KEYSYM=106 OLDCHAR=j NEWCHAR=j
(DEBUG-83305 ipc.c:914) ProcessKeyEvent IPCProcessKey return: 0
(DEBUG-83305 ipc.c:915) ProcessKeyEvent dbus_message_new_method_return return: 23307760
