### ISSUE TITLE
Massive CPU usage + shortcuts do not work anymore

### ISSUE THREAD

**Issue by CLOVIS-AI** [fcitx/fcitx#448]
Hi,

I'm using `fcitx` and `fcitx-mozc` on ArchLinux, for multiple months now. In the last update (I'm running `fcitx 4.2.9.7`), the icon doesn't appear anymore in the KDE tray, and my keyboard shortcut to switch to Japanese doesn't do anything anymore. The `fcitx` process is running, and has a consistent 100% CPU usage (the RAM usage is at 0.1%, so that's normal).

According to `fcitx-diagnose`, I do have 2 enabled input methods, as expected (`fcitx-keyboard-fr` and `mozc`), of which the first one is the default input method.

The only information in red in `fcitx-diagnose` are:

```
4.  `fcitx-remote`:
    **Cannot connect to fcitx correctly.**

2.  Config GUI for gtk2:
    **Config GUI for gtk2 not found.**
3.  Config GUI for gtk3:
    **Config GUI for gtk3 not found.**
4.  Config GUI for kde:
    **`kcmshell4` not found.**
    **Cannot find a GUI config tool, please install one of `kcm-fcitx`, `fcitx-config-gtk2`, or `fcitx-config-gtk3`.**

2.  XIM_SERVERS on root window:
    **Cannot find xim_server on root window.**

3.  XIM for Emacs:
    **Your LC_CTYPE is set to en_US.UTF-8 instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

    **Cannot find fcitx input method module for Qt4.**

        **Failed to find fcitx in the output of `/usr/bin/gtk-query-immodules-2.0-32`**

        **Failed to find fcitx in immodule cache at `/usr/lib32/gtk-2.0/2.10.0/immodules.cache`**
```

I do have `kcm-fcitx` installed, so that warning is strange. I rarely use Emacs so I don't think that's relevant, but just in case I added the warning in.

Running `fcitx-remote` gives the output `Not get reply`.

When running the Fcitx Configuration (via the KDE launcher), it starts with the title 'System settings Module' and doesn't show any available method (including when 'Only show current language' is unset), and the 'Appearance' tab shows 'Cannot load current used user interface info'. It's the first time I start it this way though (I always start it via the KDE tray), so I don't know if that's related or not.

Do you have any idea what is the cause of the issue ? It might be a configuration issue during an update, if so please tell me how to fix it.

**Comment by wengxt** [comment]
Try killall fcitx and see if anything in ~/.config/fcitx/crash.log 

I heard people recently get json-c update and need rebuild or sth. Not sure if that's related.

**Comment by CLOVIS-AI** [comment]
On lundi 4 mai 2020 19:33:44 CEST Weng Xuetian wrote:
> Try killall fcitx and see if anything in ~/.config/fcitx/crash.log 
> 
> I heard people recently get json-c update and need rebuild or sth. Not sure if that's related.
> 
> 

`killall fcitx` displays the following:

========================= 


The file `crash.log` does not exist.

**Comment by wengxt** [comment]
so indeed looks like related to json-c for whatever reason.

Did you have all package up to date? Namely, latest version that found on archlinux.org. (json-c 0.14-1 fcitx 4.2.9.7-3)

**Comment by CLOVIS-AI** [comment]
On lundi 4 mai 2020 19:52:48 CEST Weng Xuetian wrote:
> so indeed looks like related to json-c for whatever reason.
> 
> Did you have all package up to date? Namely, latest version that found on archlinux.org. (json-c 0.14-1 fcitx 4.2.9.7-3)
> 
> 

Yes, I have exactly those versions.

**Comment by wengxt** [comment]
To be honest, I don't really know, but did you do any hack during this json-c update? (like install an older version or do manual symlink?)

$ ls /usr/lib/libjson-c.so* -l
lrwxrwxrwx 1 root root    14  4月 20 11:50 /usr/lib/libjson-c.so -> libjson-c.so.5
lrwxrwxrwx 1 root root    18  4月 20 11:50 /usr/lib/libjson-c.so.5 -> libjson-c.so.5.0.0
-rwxr-xr-x 1 root root 67520  4月 20 11:50 /usr/lib/libjson-c.so.5.0.0

$ ldd /usr/lib/fcitx/fcitx-xkbdbus.so 
        linux-vdso.so.1 (0x00007ffe51dea000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f51022ab000)
        libjson-c.so.5 => /usr/lib/libjson-c.so.5 (0x00007f5102299000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f51020d3000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f51020b1000)
        libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f5102003000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f510234a000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f5101ff8000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f5101fce000)
        liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f5101fac000)
        libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f5101e8e000)
        libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f5101e6c000)

I also use archlinux but I can't reproduce your problem.

**Comment by CLOVIS-AI** [comment]
I updated with pacman -Syyuu, I don't recall doing anything manually.

— Ivan Canet

Le lun. 4 mai 2020 à 20:10, Weng Xuetian <notifications@github.com> a
écrit :

**Comment by wengxt** [comment]
here's my suggestion.

Check if your fcitx json-c library is the one from repo, don't do manual downgrade if you have ever did.
Reinstall them to make sure. Maybe also do a Syu to make sure system up to date.

Also, a reboot might help, because systemd also link json-c and all process is started by systemd, which means that might have some relevant thing in it.

**Comment by CLOVIS-AI** [comment]
On lundi 4 mai 2020 20:10:12 CEST Weng Xuetian wrote:
> To be honest, I don't really know, but did you do any hack during this json-c update? (like install an older version or do manual symlink?)
> 
> $ ls /usr/lib/libjson-c.so* -l
> lrwxrwxrwx 1 root root    14  4月 20 11:50 /usr/lib/libjson-c.so -> libjson-c.so.5
> lrwxrwxrwx 1 root root    18  4月 20 11:50 /usr/lib/libjson-c.so.5 -> libjson-c.so.5.0.0
> -rwxr-xr-x 1 root root 67520  4月 20 11:50 /usr/lib/libjson-c.so.5.0.0
> 
> $ ldd /usr/lib/fcitx/fcitx-xkbdbus.so 
>         linux-vdso.so.1 (0x00007ffe51dea000)
>         libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f51022ab000)
>         libjson-c.so.5 => /usr/lib/libjson-c.so.5 (0x00007f5102299000)
>         libc.so.6 => /usr/lib/libc.so.6 (0x00007f51020d3000)
>         libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f51020b1000)
>         libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f5102003000)
>         /usr/lib64/ld-linux-x86-64.so.2 (0x00007f510234a000)
>         librt.so.1 => /usr/lib/librt.so.1 (0x00007f5101ff8000)
>         liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f5101fce000)
>         liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f5101fac000)
>         libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f5101e8e000)
>         libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f5101e6c000)
> 
> I also use archlinux but I can't reproduce your problem.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fcitx/fcitx/issues/448#issuecomment-623619996
> 

I think everything is the same?

~ → ls /usr/lib/libjson-c.so* -l 
*/usr/lib/libjson-c.so* -> libjson-c.so.5 
*/usr/lib/libjson-c.so.5* -> libjson-c.so.5.0.0 
*/usr/lib/libjson-c.so.5.0.0* 
~ → ldd /usr/lib/fcitx/fcitx-xkbdbus.so

**Comment by CLOVIS-AI** [comment]
On lundi 4 mai 2020 20:16:27 CEST Weng Xuetian wrote:
> here's my suggestion.
> 
> Check if your fcitx json-c library is the one from repo, don't do manual downgrade if you have ever did.
> Reinstall them to make sure. Maybe also do a Syu to make sure system up to date.
> 
> Also, a reboot might help, because systemd also link json-c and all process is started by systemd, which means that might have some relevant thing in it.
> 
> 
> 
> 
> 
> 

Reinstalled everything with 'sudo pacman -Syyuu json-c fcitx fcitx-mozc' but same results.

**Comment by wengxt** [comment]
I noticed there're some bug in json-c (reported to arch). Looks like they are directly related to this issue (break json_c_get_random_seed).
Please check the json-c update. (Probably the one in testing. json-c 0.14-4)

https://github.com/json-c/json-c/issues/588

**Comment by CLOVIS-AI** [comment]
I do have a Ryzen CPU so that's probably the issue. Thanks :)

**Comment by CLOVIS-AI** [comment]
(if anyone else has the same problem, I can confirm that updating `json-c` fixes it)
