### ISSUE TITLE
中英文相互切换，第一个字母直接输入到文本框中，没有经过输入法

### ISSUE THREAD

**Issue by ShawZG** [fcitx/fcitx#449]
您好，我在中文和英文间通过shift键进行切换，有时会遇到下图的情况，当前为拼音输入法时，第一个字母直接输入到文本框中，没有在输入法框中显示，后续输入中文就正常了。

![截图录屏_选择区域_20200520154639](https://user-images.githubusercontent.com/22807878/82419988-b7b1e780-9ab1-11ea-8cdb-f427622c771c.png)

我是用的wine微信，出现的频率比较高。

[fcitx-dianose](https://github.com/fcitx/fcitx/files/4655378/dianose.txt)

已经安装了fcitx-frontend-gtk2 fcitx-frontend-gtk3。

**Comment by wengxt** [comment]
这种情况一般是程序本身的问题，wine的微信用的是xim……那我也确实不知道能有什么可能的办法来 hack。建议给 uos 的这个包报 bug 看看上游有什么办法。

我在 archlinux 运行同样的并不能重现问题，可能是 wine 的版本不一样。
