### ISSUE TITLE
Trying fcitx led me to an unusable keyboard layout

### ISSUE THREAD

**Issue by rafaelcn** [fcitx/fcitx#463]
]]I tried to add the Japanese input method and so I installed fcitx to do so as I read it was the best. It didn't work so I uninstalled the fcitx software after that and I don't know how but I ended up with every layout remapped to some weird layout as shown in the pictures. The first picture is from an English keyboard layout and the second one is from a Portuguese keyboard layout.

![fucked keyboard](https://user-images.githubusercontent.com/3271143/90305579-cdf5f680-de9a-11ea-9b5f-d9597abe971f.png)
![fucked keyboard 2](https://user-images.githubusercontent.com/3271143/90305580-cfbfba00-de9a-11ea-8116-fa7b1f9c687c.png)

My `setxkbmap -print -verbose 10` can be seen below, showing that the configuration is locked to some weird options.

```
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     br,us
variant:    ,
options:    grp:alt_shift_toggle,japan:hztg_escape,japan:nicola_f_bs,japan:kana_lock
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete+japan(kana_lock)
symbols:    pc+br+us:2+inet(evdev)+group(alt_shift_toggle)+jp(nicola_f_bs)+jp(hztg_escape)
geometry:   pc(pc105)
xkb_keymap {
    xkb_keycodes  { include "evdev+aliases(qwerty)" };
    xkb_types     { include "complete"  };
    xkb_compat    { include "complete+japan(kana_lock)" };
    xkb_symbols   { include "pc+br+us:2+inet(evdev)+group(alt_shift_toggle)+jp(nicola_f_bs)+jp(hztg_escape)"    };
    xkb_geometry  { include "pc(pc105)" };
};
```

How can I go back to the default?

**Comment by wengxt** [comment]
So I'm pretty sure fcitx working as intended.

I'm not so sure about what is your desired setup, but fcitx would manage your layout and you can do that by in fcitx settings. But also, input method may have a default layout to be used mozc is probably bind to jp layout by default so you end up with jp in the xkb setup, but you may also use fcitx-configtool to change the per input method layout to be used with mozc (e.g. to force mozc to use br layout).

If you can't make it just work as the way you like, you also just simply disable the layout changing functionality with in fcitx and relogin the system (Option in fcitx's Xkb addon).
