### ISSUE TITLE
Didn't show pre-edit window when input to WPS Office.

### ISSUE THREAD

**Issue by Marusoftware** [fcitx/fcitx#466]
I'm using WPS Office 11.1.0.9615.XA on Linux Mint 20(fcitx is 4.2.9.7).
But pre-edit window didn't show when I input to WPS Office.
I try this:
・change input method mozc to anthy.
・change Config Tool > Addon > fcitx XIM Front-end > on the spot.. to true
・CTRL + ALT + P (it is work, but it isn't show on text area)
![screenshot1](https://user-images.githubusercontent.com/61912820/93717996-34fe7d80-fbb4-11ea-8674-3a76c4bb1e80.png)

But I can input to Firefox without problem.
![screenshot2](https://user-images.githubusercontent.com/61912820/93718221-a12db100-fbb5-11ea-9970-19299c6c6c84.png)

Thank you.

**Comment by ayalhw** [comment]
It seems the limit of XIM,
Unless WPS uses Qt5, there should be no other way to do it once and for all.
One workaround is to enable `On The Spot` in `Fcitx Setting/Addons Setting/X Input Method Frontend`,
but this will make the cursor not follow (XIM limitation).

**Comment by Marusoftware** [comment]
I understand...
Thank you.

**Comment by trmdi** [comment]
> Unless WPS uses Qt5, there should be no other way to do it once and for all.

Any update on this? The current version of WPS is using Qt5.
