### ISSUE TITLE
一个恼人的有关 arch 下双屏使用, 输入焦点和候选词组菜单不在同一个显示器上显示的问题。

### ISSUE THREAD

**Issue by zw963** [fcitx/fcitx#476]
这个 bug 大概就是这个样子。

1. 正常启动，fcitx 在双屏下正常使用, 我这样说的意思是： 无论我的光标在副屏还是主屏，当我输入中文时，那些悬浮的候选词组选项，总是随着我的光标的。

2. 拔了外置显示器, 在主屏上使用 fcitx 输入一些内容，此时主屏显示是正常的。

3.  再插上外置的 (type-c) 接口的显示器，屏幕闪一下，然后两个屏幕都显示正常。

4. 问题来了，此时在副屏上打字（要求当时单屏时，使用 fcitx 在主屏上输入过内容），只能看到当前输入的悬浮字符，但是，单词候选选项却在主屏上。

下面是一些手机拍的图片来演示一下这个 bug:

这是我在副屏的控制台输入一些字符:

![微信图片_20201111175849](https://user-images.githubusercontent.com/549126/98797616-cae1b680-2447-11eb-8fc2-39daee25e2c9.jpg)

然后候选菜单在另一个屏幕（电脑主屏）上，超级崩溃。

![微信图片_20201111180118](https://user-images.githubusercontent.com/549126/98797716-ec42a280-2447-11eb-81b6-e96d835bcfc6.jpg)

## 解决办法：

重启 fcitx 可解决。 但是这又带来其他问题，例如，fcitx 重启后，Emacs 也得重启，否则无法激活输入法 ....

## 我的环境

Arch linux 滚动版, 我使用的输入法为: fcitx-sunpinyin.

```
 ╰─ $ fcitx --version
fcitx version: 4.2.9.7
 ╰─ $ pacman -Q |grep fcitx
fcitx 4.2.9.8-1
fcitx-configtool 0.4.10-4
fcitx-qt5 1.2.5-2
fcitx-rime 0.3.2-3
fcitx-sunpinyin 0.4.2-2


```

**Comment by zw963** [comment]
I create a ticket on arch form here, https://bbs.archlinux.org/viewtopic.php?pid=1938703#p1938703

maybe it is not fcitx specified issue.

**Comment by wengxt** [comment]
是 X11 还是 Wayland？

**Comment by zw963** [comment]
> 是 X11 还是 Wayland？

Wayland 呀.

**Comment by zw963** [comment]
我新增了一些更详细的 reproduce 信息在 Arch 的 bbs, 请看这里。

https://bbs.archlinux.org/viewtopic.php?pid=1939039#p1939039

**Comment by wengxt** [comment]
如果 X11 的没有问题的话，那就是你的 X wayland 的 xrandr 有啥问题吧……

**Comment by zw963** [comment]
嘿，这个问题似乎已经解决了， 在最近的升级之后，因为好一阵子没有重现了.

非常感谢.

**Comment by zw963** [comment]
这个问题似乎并没有解决。而且，似乎，Firefox 菜单的问题并未再次出现，反倒是，Fcitx 还是同样的问题。

**Comment by everyx** [comment]
同样有这个问题，Fcitx 只会显示在主屏幕上，除了屏幕不对，相对位置都是对的 囧

**Comment by KairuiLiu** [comment]
遇到了同样的问题, 在 sway 的 chrome 下, 候选框出现在了另一块屏幕上相对位置相同的地方

**Comment by neilhhw** [comment]
我也有同样的问题，我是在wayland上的google chrome就会有这样。

**Comment by wengxt** [comment]
请用 fcitx5 ，然后阅读 https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland 并非所有 compositor 都能让 chrome 在 wayland 上有很正常的体验。
