### ISSUE TITLE
Support GTK_IM_MODULE="fcitx4" and QT_IM_MODULE="fcitx4"

### ISSUE THREAD

**Issue by Arfrever** [fcitx/fcitx#477]
Since these commits:
https://github.com/fcitx/fcitx5-gtk/commit/950301ce19cb212fba9c58d9b723c6b27f9f7869
https://github.com/fcitx/fcitx5-qt/commit/6fe447439cd4dec0bce825ccfd2059eb35aacf79
Fcitx 5 supports both `fcitx` and `fcitx5` as values of `GTK_IM_MODULE` and `QT_IM_MODULE` environmental variables.

Currently Fcitx 4 supports only `GTK_IM_MODULE="fcitx"` and `QT_IM_MODULE="fcitx"`.
`GTK_IM_MODULE="fcitx"` and `QT_IM_MODULE="fcitx"` are ambiguous in regard to Fcitx version.

In order to allow to unambiguously select Fcitx 4 on systems with both Fcitx 4 and Fcitx 5 installed, I suggest to add support for `GTK_IM_MODULE="fcitx4"` and `QT_IM_MODULE="fcitx4"` in Fcitx 4.

Patch: [fcitx-fcitx4_key.patch.txt](https://github.com/fcitx/fcitx/files/5526068/fcitx-fcitx4_key.patch.txt)

**Comment by wengxt** [comment]
I don't see a reason to do so. fcitx 4 can also work with fcitx 5 im module.
