### ISSUE TITLE
interface to adjust candidate window position 能否有控制输入候选框位置的接口

### ISSUE THREAD

**Issue by xulihang** [fcitx/fcitx#481]
fcitx在我用JavaFX编写的应用上似乎不能让输入候选框跟随光标，不知道能不能提供一个接口，由javafx程序提供光标位置，调整fcitx的输入候选框位置

![2020-11-26_12-41-34](https://user-images.githubusercontent.com/5462205/100309693-7103f380-2fe6-11eb-99b3-6dab43106b68.png)

**Comment by wengxt** [comment]
本来就有那种接口，问题是在 javafx 那边

**Comment by xulihang** [comment]
我给javafx提交了bugreport但一直没处理，所以想能不能先有一个workaround，让javafx的应用和fcitx直接交互

**Comment by wengxt** [comment]
首先，你不觉得fcitx本来就支持么……否则别的程序怎么通知的候选框位置？但是你设想的思路不太对 可能难以实现

另外不知道这个有没有帮助 https://github.com/prehonor/myJetBrainsRuntime/blob/master/idea.patch

**Comment by xulihang** [comment]
了解了，那还是得和操作系统的输入法框架交互
