### ISSUE TITLE
How to keep the comment window open

### ISSUE THREAD

**Issue by ekaunt** [fcitx/fcitx#483]
Is there a way to always keep the comment window open?

It's very cumbersome to press ctrl+alt+h (or whatever shortcut you set it to) every time I want to check the definition/comment...

Here are examples of what I mean (from Microsoft IME, Google IME, and ATOK):

![microsoft-ime](https://user-images.githubusercontent.com/62402760/100692465-e3fbca00-3358-11eb-95c3-c8e2a80996de.gif)
![google-ime](https://user-images.githubusercontent.com/62402760/100692467-e4946080-3358-11eb-9573-8938dd85ddaa.gif)
![atok-ime](https://user-images.githubusercontent.com/62402760/100692468-e4946080-3358-11eb-87d0-aa7b8c13a4b6.gif)

Here's an example of how fcitx currently works:

![fcitx-ime](https://user-images.githubusercontent.com/62402760/100692464-e3fbca00-3358-11eb-9117-bc52f81c5b96.gif)

As you can see, I can't see the definitions as I scroll by. Instead, I have to press ctrl+alt+h every time I want to check the definition.

I use this feature a lot for my custom user dictionary entries, and for the built in dictionary entries, and it's very annoying to have to keep on pressing ctrl+alt+h.  
ᅠ
ᅠ
Is there a way to always keep the comment window open so that I can see the comments/definitions at a glance without needing to press ctrl+alt+h nonstop?

**Comment by yuyichao** [comment]
Dup of https://github.com/fcitx/fcitx/issues/482

**Comment by ekaunt** [comment]
I mistakenly posted this twice. sorry
