### ISSUE TITLE
大家遇到过这个现象吗：拼音输入法中，按下“[” 和 “]” ，输出为“·” 和 “「”

### ISSUE THREAD

**Issue by Dreamer-Fantasy** [fcitx/fcitx#485]
系统及相关包信息图片：
![Screenshot_20210120_210820](https://user-images.githubusercontent.com/58366528/105180525-a7349e00-5b65-11eb-8188-099449650bc1.png)

**Comment by wengxt** [comment]
fcitx就是这么默认设置的
