### ISSUE TITLE
Force Window Position

### ISSUE THREAD

**Issue by cagnulein** [fcitx/fcitx#486]
Hi, is there a way to force a position (x,y) for fcitx window? If not, could you point me to the source code line where you set the coordinate in order to force it?
Thanks

**Comment by EliaTolin** [comment]
Hi! I have the same problem. I use fcitx with my application but when it show fcitx it going up on onboard keyboard (it's in fix position). Is it possible fix the position of fcitx?

**Comment by cagnulein** [comment]
implemented here https://github.com/cagnulein/fcitx/commit/56852920036d452a1185aa9fdd8cd49d585e771c
