### ISSUE TITLE
Using compose strings longer than 1 character only displays the first char

### ISSUE THREAD

**Issue by qwertfisch** [fcitx/fcitx#487]
The compose feature on Linux can be extended by a user defined `.XCompose` file in a user’s home directory. Most compose sequences work, e.g.
```
<dead_acute> <a> : "á"
<Multi_key> <apostrophe> <I> : "Í"
```
where `Multi_key` is the defined compose key.

If the string to be composed contains more than one character, only the first character will be displayed:

```
<Multi_key> <t> <space> : "abc"
```
Typing the sequence above (Multikey, t, Space) space results only in `a` instead of `abc`. If I am using IBus or even XIM, the result is as expected `abc`.

**Comment by wengxt** [comment]
I suggest you update to fcitx 5 if possible. There was a similar bug but was fixed.

https://github.com/fcitx/fcitx5/issues/198

**Comment by qwertfisch** [comment]
I didn’t know there was a new version, managed as a different project. So I could not find the issue here.

My distribution Linux Mint does not provide the necessary 5.04+ version of fcitx5 yet, but it seems the issue will be fixed then.

**Comment by wengxt** [comment]
If you want to try fcitx 5 with flatpak: https://fcitx-im.org/wiki/Install_Fcitx_5
If you want to try some similar functionality that allows you customize some shortcut for typing, https://fcitx-im.org/wiki/QuickPhrase

**Comment by qwertfisch** [comment]
Thanks. The QuickPhrase addon seems indeed more useful for this purpose. I give it a try and see if it works better for me.
