### ISSUE TITLE
Ctrl-5 breaks other ctrl-numbers when fcitx is loaded(?)

### ISSUE THREAD

**Issue by jamshark70** [fcitx/fcitx#489]
I'm wondering if there is a special meaning for ctrl-5 in fcitx that I can't find in the interface.

The reason:

For one of my courses, I'm using a "graphical patcher" program called Pure Data (tcl/tk front-end).

This software uses ctrl-numbers to put objects onto a canvas (ctrl-1 = object, ctrl-2 = message, ctrl-3 = number input box, ctrl-4 = string input box, ctrl-5 = comment).

I've disabled auto-starting Fcitx Qt IMPanel because when this is auto-started, these keystrokes just don't work.

Without that auto starting (but with fcitx loaded), ctrl-1 to ctrl-4 are usually OK. But, if I hit ctrl-5, then a/ nothing happens in Pure Data and b/ maybe the other ctrl-numbers are broken after that (until I click something, or use a menu, or switch to another window or... something, it's hard to pin down).

So I have to assume that fcitx is swallowing ctrl-5 and that this temporarily alters the way keystrokes are processed.

I wouldn't call this a high priority -- if I need to do some serious pd patching, I can quit fcitx during that time. But, I'm teaching in China, so I do need simplified Chinese input at times. When I'm working on lecture outlines, I often need to switch between inputting Chinese characters and using Pd, and it becomes inconvenient to have to quit/relaunch/quit/relaunch again and again.

Is there another way?

**Comment by wengxt** [comment]
ctrl + 5 by default is "reload config" in fcitx, as defined here: https://github.com/fcitx/fcitx/blob/289b2f674d95651d4e0d0c77a48e3a2f0da40efe/data/config.desc#L81

You may easily change it via configure tool. (Click "show advance option" in global config section).
Or, open ~/.config/fcitx/config, find the ReloadConfig=CTRL_5 , and set it to empty (or any other value).

**Comment by jamshark70** [comment]
OK, thanks! I just overlooked it... changed to ctrl-shift-5 and it's all fine now. Thanks for the quick answer!

(BTW fcitx is great -- especially after my Ubuntu 20.04 upgrade, it *just works*.)
