### ISSUE TITLE
快速定位到第N 个输入法

### ISSUE THREAD

**Issue by pypeetpy** [fcitx/fcitx#491]
我需要用到3种输入法，fcitx5 之前有个addon 能让我快速定位到我想要的输入法，到了fcitx 5的时候 ，好像没有了。
具体的使用方法就是，
 ctrl + shift + 1 , 英文
ctrl + shift + 2 ， 泰文
ctrl + shift + 3 , 五笔拼音 
谢谢开发者。如果这个addon 还在麻烦说一下在哪里。

**Comment by wengxt** [comment]
有的，自己找一下。输入法选择器
