### ISSUE TITLE
对于输入`hz` `zz`如何不显示一些乱七八糟的字符

### ISSUE THREAD

**Issue by u5n** [fcitx/fcitx#496]
环境:
+ fcitx版本`4.2.9.7`
+ ubuntu 20.04 LTS gnome 3.36
复现方法, 如上操作系统中, 安装`fcitx`, `fcitx-pinyin`. 而后在`fcitx-configtool`中加入任意拼音输入法, 如`shuangpin`. 使用该输入法, 输入`zz`, 得到如图所示结果

![image](https://user-images.githubusercontent.com/26353598/120361780-d8f01980-c33c-11eb-8a0c-d1470ddb05ae.png)
![image](https://user-images.githubusercontent.com/26353598/120364177-7e0bf180-c33f-11eb-90da-8a86547f3950.png)

不论采用`fcitx-googlepinyin`还是`fcitx-pinyin`, 不论是双拼还是全拼, 都有这些莫名奇妙的输出, 我在`fcitx-configtool`中没有找到相关的选项
而且这些输出还排在正常的字前面, 比如我想打'奏'字, 按小鹤双拼我按`zz`, '奏'在`第三页`

**Comment by u5n** [comment]
现已查明是fcitx插件`Enchance pinyin input in Fcitx`导致
fcitx configtool addon 勾选advanced 可以进行禁用, 具体原因不明
此外禁用fcitx插件会可能会导致fcitx无法使用, 这时候可以删除`~/.config/fcitx`文件夹然后`killall fcitx` 然后重启`fcitx`

**Comment by wengxt** [comment]
那是笔画输入功能 hszpn 表示横撇竖折捺
