### ISSUE TITLE
gnome 活动界面搜索框无法输入中文

### ISSUE THREAD

**Issue by quanzhuo** [fcitx/fcitx#510]
gnome 版本：3.38.5
fcitx version: 4.2.9.8
输入法：搜狗输入法

我不太清楚这个是不是fcitx的问题。在其它应用程序中都可以正常输入中文，gnome 应用搜索界面无法调出搜狗输入法。

**Comment by quanzhuo** [comment]
# 系统信息:
1.  `uname -a`:

        Linux debian 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

2.  `lsb_release -a`:

        No LSB modules are available.
        Distributor ID:	Debian
        Description:	Debian GNU/Linux 11 (bullseye)
        Release:	11
        Codename:	bullseye

3.  `lsb_release -d`:

        Description:	Debian GNU/Linux 11 (bullseye)

4.  `/etc/lsb-release`:

    `/etc/lsb-release` 未找到.

5.  `/etc/os-release`:

        PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
        NAME="Debian GNU/Linux"
        VERSION_ID="11"
        VERSION="11 (bullseye)"
        VERSION_CODENAME=bullseye
        ID=debian
        HOME_URL="https://www.debian.org/"
        SUPPORT_URL="https://www.debian.org/support"
        BUG_REPORT_URL="https://bugs.debian.org/"

6.  桌面环境:

    桌面环境为 `gnome3`。

7.  Bash 版本:

        BASH_VERSION='5.1.4(1)-release'

# 环境:
1.  DISPLAY:

        DISPLAY=':1'

2.  键盘布局:

    1.  `setxkbmap`:

            xkb_keymap {
            	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
            	xkb_types     { include "complete"	};
            	xkb_compat    { include "complete"	};
            	xkb_symbols   { include "pc+us+cn:2+inet(evdev)+level3(ralt_switch)"	};
            	xkb_geometry  { include "pc(pc105)"	};
            };

    2.  `xprop`:

            _XKB_RULES_NAMES(STRING) = "evdev", "pc105", "us,cn", ",", "lv3:ralt_switch"

3.  Locale:

    1.  全部可用 locale:

            C
            C.UTF-8
            en_US.utf8
            POSIX
            zh_CN.utf8

    2.  当前 locale:

            LANG=zh_CN.UTF-8
            LANGUAGE=
            LC_CTYPE="zh_CN.UTF-8"
            LC_NUMERIC="zh_CN.UTF-8"
            LC_TIME="zh_CN.UTF-8"
            LC_COLLATE="zh_CN.UTF-8"
            LC_MONETARY="zh_CN.UTF-8"
            LC_MESSAGES="zh_CN.UTF-8"
            LC_PAPER="zh_CN.UTF-8"
            LC_NAME="zh_CN.UTF-8"
            LC_ADDRESS="zh_CN.UTF-8"
            LC_TELEPHONE="zh_CN.UTF-8"
            LC_MEASUREMENT="zh_CN.UTF-8"
            LC_IDENTIFICATION="zh_CN.UTF-8"
            LC_ALL=

4.  目录：

    1.  主目录：

            /home/quan

    2.  `${XDG_CONFIG_HOME}`:

        环境变量 `XDG_CONFIG_HOME` 没有设定。

        `XDG_CONFIG_HOME` 的当前值是 `~/.config` (`/home/quan/.config`)。

    3.  Fcitx 设置目录：

        当前 fcitx 设置目录是 `~/.config/fcitx` (`/home/quan/.config/fcitx`)。

5.  当前用户：

    脚本作为 quan (1000) 运行。

# Fcitx 状态:
1.  可执行文件:

    在 `/usr/bin/fcitx` 找到了 fcitx.

2.  版本:

    Fcitx 版本: `4.2.9.8`

3.  进程:

    找到了 2 个 fcitx 进程:

          11961 fcitx
          11974 fcitx-dbus-watc

4.  `fcitx-remote`:

    `fcitx-remote` 工作正常.

5.  DBus 界面:

    使用 `dbus-send` 来检查 dbus。

    DBus 名称 `org.fcitx.Fcitx` 的所有者是 `:1.6`。

    DBus 名称 `org.fcitx.Fcitx` 的 PID 所有者是 `11961`。

# Fcitx 配置界面:
1.  配置工具封装：

    在 `/usr/bin/fcitx-configtool` 找到了 fcitx-configtool。

2.  用于 GTK+-2.0 的配置界面：

    **未找到 gtk2 的配置界面.**

3.  用于 GTK+-3.0 的配置界面：

    在 `/usr/bin/fcitx-config-gtk3` 找到了 `fcitx-config-gtk3`。

4.  KDE 的配置界面：

    **`kcmshell4` 未找到.**

# 前端设置:
## Xim:
1.  `${XMODIFIERS}`:

    环境变量 XMODIFIERS 已经正确地设为了 "@im=fcitx".
    从环境变量中获取的 Xim 服务名称为 fcitx.

2.  根窗口上的 XIM_SERVERS:

    Xim 服务的名称与环境变量中设置的相同.

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".

2.  qt5 - `${QT_IM_MODULE}`:

    环境变量 QT_IM_MODULE 已经正确地设为了 "fcitx".

3.  Qt 输入法模块文件:

    找到了 fcitx 的 qt 模块: `/usr/lib/x86_64-linux-gnu/fcitx/qt/libfcitx-quickphrase-editor5.so`.
    找到了 Qt5 的输入法模块: `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    **无法找到 Qt4 的 fcitx 输入法模块.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    环境变量 GTK_IM_MODULE 已经正确地设为了 "fcitx".

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **无法找到 gtk 2 的 `gtk-query-immodules`.**

        **无法找到 gtk 2 的 fcitx 输入法模块.**

    2.  gtk 3:

        **无法找到 gtk 3 的 `gtk-query-immodules`.**

        **无法找到 gtk 3 的 fcitx 输入法模块.**

3.  Gtk 输入法模块缓存:

    1.  gtk 2:

        在 `/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache` 找到了 gtk `2.24.33` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.33

        已找到 gtk `2.24.33` 的 fcitx 输入法模块.

            "/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

    2.  gtk 3:

        在 `/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache` 找到了 gtk `3.24.24` 的输入法模块缓存.
        版本行:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.24

        已找到 gtk `3.24.24` 的 fcitx 输入法模块.

            "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-fcitx.so" 
            "fcitx" "Fcitx (Flexible Input Method Framework)" "fcitx" "/usr/share/locale" "ja:ko:zh:*" 

4.  Gtk 输入法模块文件:

    1.  gtk 2:

        找到的全部 Gtk 2 输入法模块文件均存在.

    2.  gtk 3:

        找到的全部 Gtk 3 输入法模块文件均存在.

# 配置:
## Fcitx 插件:
1.  插件配置文件目录:

    找到了 fcitx 插件配置目录: `/usr/share/fcitx/addon`.

2.  插件列表:

    1.  找到了 26 个已启用的插件:

            fcitx-autoeng
            fcitx-chttrans
            fcitx-classic-ui
            fcitx-clipboard
            fcitx-dbus
            fcitx-freedesktop-notify
            fcitx-fullwidth-char
            fcitx-imselector
            fcitx-ipc
            fcitx-ipcportal
            fcitx-keyboard
            fcitx-lua
            fcitx-notificationitem
            fcitx-pinyin
            fcitx-pinyin-enhance
            fcitx-punc
            fcitx-quickphrase
            fcitx-remote
            fcitx-sogoupinyin
            fcitx-spell
            fcitx-unicode
            fcitx-vk
            fcitx-x11
            fcitx-xim
            fcitx-xkb
            fcitx-xkbdbus

    2.  找到了 1 个被禁用的插件:

            fcitx-kimpanel-ui

3.  插件库: 

    所有插件所需的库都被找到。

4.  用户界面:

    找到了 1 个已启用的用户界面插件:

        fcitx-classic-ui

## 输入法:
1.  找到了 6 个启用的输入法:

        fcitx-keyboard-us
        sogoupinyin
        pinyin-libpinyin
        shuangpin-libpinyin
        sunpinyin
        zhuyin-libpinyin

2.  默认输入法:

    您已经正确的将一个键盘输入法 "fcitx-keyboard-us" 设为默认.

# 日志:
1.  `date`:

        2021年 11月 17日 星期三 14:12:06 CST

2.  `~/.config/fcitx/log/`:

        总用量 4
        -rw-r--r-- 1 quan quan 1984 11月 17 12:49 crash.log

3.  `~/.config/fcitx/log/crash.log`:

        =========================
        FCITX 4.2.9.8 -- Get Signal No.: 6
        Date: try "date -d @1637124590" if you are using GNU date ***
        ProcessID: 18036
        /usr/bin/fcitx(+0x191f)[0x56328925a91f]
        /lib/x86_64-linux-gnu/libc.so.6(+0x3bd60)[0x7fe6f0615d60]
        /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x141)[0x7fe6f0615ce1]
        /lib/x86_64-linux-gnu/libc.so.6(abort+0x123)[0x7fe6f05ff537]
        /lib/x86_64-linux-gnu/libc.so.6(+0x7e768)[0x7fe6f0658768]
        /lib/x86_64-linux-gnu/libc.so.6(+0x85a5a)[0x7fe6f065fa5a]
        /lib/x86_64-linux-gnu/libc.so.6(+0x86d55)[0x7fe6f0660d55]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x346e4)[0x7fe6ebaa16e4]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x34635)[0x7fe6ebaa1635]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x34561)[0x7fe6ebaa1561]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x3437e)[0x7fe6ebaa137e]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x33e19)[0x7fe6ebaa0e19]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x33df6)[0x7fe6ebaa0df6]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x33ae2)[0x7fe6ebaa0ae2]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x3476c)[0x7fe6ebaa176c]
        /lib/x86_64-linux-gnu/libc.so.6(+0x3e4d7)[0x7fe6f06184d7]
        /lib/x86_64-linux-gnu/libc.so.6(+0x3e67a)[0x7fe6f061867a]
        /lib/x86_64-linux-gnu/libX11.so.6(+0x465fe)[0x7fe6efb0a5fe]
        /lib/x86_64-linux-gnu/libX11.so.6(_XIOError+0x67)[0x7fe6efb0a967]
        /lib/x86_64-linux-gnu/libX11.so.6(_XReply+0x443)[0x7fe6efb08843]
        /lib/x86_64-linux-gnu/libX11.so.6(XSync+0x4b)[0x7fe6efb03e2b]
        /lib/x86_64-linux-gnu/libX11.so.6(XCloseDisplay+0x7b)[0x7fe6efae4b7b]
        /usr/lib/x86_64-linux-gnu/fcitx/fcitx-sogoupinyin.so(+0x3710c)[0x7fe6ebaa410c]
        /lib/x86_64-linux-gnu/libfcitx-core.so.0(+0xa7da)[0x7fe6f07fb7da]
        /lib/x86_64-linux-gnu/libfcitx-core.so.0(FcitxInstanceRun+0x57)[0x7fe6f07fbad7]
        /usr/bin/fcitx(+0x12bf)[0x56328925a2bf]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea)[0x7fe6f0600d0a]
        /usr/bin/fcitx(+0x133a)[0x56328925a33a]

**Comment by wengxt** [comment]
请用 fcitx 5.

**Comment by xingwozhonghua** [comment]
这个问题是你缺少，fcitx的gtk插件，“sudo apt install libfcitx-gclient1”

**Comment by wengxt** [comment]
@xingwozhonghua 你说的不对，不要误导了。fcitx4 是没办法在这个版本的 gnome shell 搜索框用的，因为gnome shell 代码直接调用了 ibus 接口，不再经过 gtk im module。fcitx5 能使用是因为模拟了 ibus 的接口实现的。

**Comment by chenshijie-uos** [comment]
> @xingwozhonghua 你说的不对，不要误导了。fcitx4 是没办法在这个版本的 gnome shell 搜索框用的，因为gnome shell 代码直接调用了 ibus 接口，不再经过 gtk im module。fcitx5 能使用是因为模拟了 ibus 的接口实现的。

好的，除了这个我还发现好多应用都是直接设置输入法环境变量为ibus,感觉可能也是和gnome桌面强绑定ibus有关系。
看情况确实fcitx4如果不添加 ibus 的接口必然会被淘汰。还存在wayland,和各个gui软件依赖库的问题。

**Comment by quanzhuo** [comment]
@wengxt @xingwozhonghua @chenshijie-uos  感谢各位的回复, 安装 fcitx5之后问题已经解决. 
但是fcitx5 在 gnome 41 上面的搜索框里面可以打出汉字, 但是看不到输入项候选面板

**Comment by wengxt** [comment]
@quanzhuo 那个只能通过使用这个扩展解决：https://extensions.gnome.org/extension/261/kimpanel/

通常情况下没有窗口可以显示在gnome shell窗口上方

**Comment by quanzhuo** [comment]
安装该插件之后就可以了,感谢您
________________________________
发件人: Weng Xuetian ***@***.***>
发送时间: 2021年12月3日 3:58
收件人: fcitx/fcitx ***@***.***>
抄送: Quan Zhuo ***@***.***>; Mention ***@***.***>
主题: Re: [fcitx/fcitx] gnome 活动界面搜索框无法输入中文 (Issue #510)


@quanzhuo<https://github.com/quanzhuo> 那个只能通过使用这个扩展解决：https://extensions.gnome.org/extension/261/kimpanel/

通常情况下没有窗口可以显示在gnome shell窗口上方

―

**Comment by xiamuguizhi** [comment]
... 我也遇到这个问题了, 感觉无解啊.
