### ISSUE TITLE
Blinking UI when typing on preedit enabled under Wayland

### ISSUE THREAD

**Issue by outloudvi** [fcitx/fcitx#511]
Reproduction steps:

* Run `QT_QPA_PLATFORM=wayland telegram-desktop`, and enable preedit, the UI will disappear and then display (i.e. blink) when typing

Other info:

* It does not happen on `QT_QPA_PLATFORM=xcb telegram-desktop` under Wayland
* It does not happen under X Server
* It does not happen when preedit is disabled

**Comment by wengxt** [comment]
I assume you're using fcitx 5? See for the reason https://fcitx-im.org/wiki/FAQ#Candidate_window_is_blinking_under_wayland_with_Fcitx_5

Which input method are you referring to ? Actually common Chinese input method are using fixed cursor position. So it tries not to blink as much as possible. We can also fix others too.

**Comment by outloudvi** [comment]
Thanks for your explanation! I'm actually using RIME and have set `PreeditInApplication=True`, and I do noticed that stock pinyin is not having such problems with the same configuration on my side.
