### ISSUE TITLE
unable switch fcitx to any other language in calibre

### ISSUE THREAD

**Issue by wu-math-fan** [fcitx/fcitx#517]
https://www.mobileread.com/forums/showthread.php?t=347971
after reading:
https://fcitx-im.org/wiki/Input_method_related_environment_variables/zh-hans
https://fcitx-im.org/wiki/Configure_(Other)/zh-hans
https://fcitx-im.org/wiki/Setup_Fcitx_5#Binary_Qt_application
i added these to ~/.bash_profile:
  GNU nano 5.4                      .bash_profile                               
  GNU nano 5.4              /etc/X11/xinit/xinput.d/fcitx
XIM=fcitx
XIM_PROGRAM=/usr/bin/fcitx
XIM_ARGS=""
XMODIFIERS DEFAULT=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=ibus
DEPENDS="fcitx"

after finished, i relogin. but the problem still remains.

**Comment by wu-math-fan** [comment]
the os is debian 11.
the desktop is kde plasma.

**Comment by wu-math-fan** [comment]
after adding ~/.config/plasma-workspace/env/im.sh
XMODIFIERS=@im=fcitx
GTK_IM_MODULE=fcitx
QT_IM_MODULE=ibus

**Comment by bluehtt** [comment]
Calibre looks like uses Qt: [https://calibre-ebook.com/whats-new](https://calibre-ebook.com/whats-new). Maybe you should change you config property `QT_IM_MODULE`?

**Comment by wengxt** [comment]
why would you set QT_IM_MODULE=ibus? you should set QT_IM_MODULE=fcitx if you want to use fcitx.
